import { useState } from 'react';
import { HypebitUser, getDefaultView, canAccess } from './auth';
import LoginScreen from './LoginScreen';

// ─── Design tokens ──────────────────────────────────────────────────────────
const C = {
  bg: '#0B0F1A', surface: '#111827', surface2: '#1F2937', surface3: '#374151',
  border: 'rgba(255,255,255,0.06)', border2: 'rgba(255,255,255,0.1)',
  text: '#F9FAFB', text2: '#9CA3AF', text3: '#4B5563',
  blue: '#3B82F6', blueD: '#1D4ED8', blueAlpha: 'rgba(59,130,246,0.12)',
  purple: '#8B5CF6', purpleAlpha: 'rgba(139,92,246,0.12)',
  green: '#10B981', greenAlpha: 'rgba(16,185,129,0.12)',
  red: '#EF4444', redAlpha: 'rgba(239,68,68,0.12)',
  yellow: '#F59E0B', yellowAlpha: 'rgba(245,158,11,0.12)',
  mono: '"JetBrains Mono", "Fira Code", monospace',
  ui: 'Inter, -apple-system, sans-serif',
};

// ─── Demo data ───────────────────────────────────────────────────────────────
const DEMO_DATA = {
  mrr: 47832, mrr_growth: 12.4, arr: 573984,
  active_users: 1847, active_users_growth: 8.2,
  conversion_rate: 3.8, conversion_change: 0.4,
  churn_rate: 2.1, churn_change: -0.3,
  cac: 284, ltv: 2840, ltv_cac_ratio: 10.0,
  trial_started: 234, trial_converted: 89,
  revenue_history: [
    { month: 'Apr', mrr: 32100 }, { month: 'May', mrr: 34800 },
    { month: 'Jun', mrr: 36200 }, { month: 'Jul', mrr: 37900 },
    { month: 'Aug', mrr: 39400 }, { month: 'Sep', mrr: 41200 },
    { month: 'Oct', mrr: 42800 }, { month: 'Nov', mrr: 43900 },
    { month: 'Dec', mrr: 44700 }, { month: 'Jan', mrr: 45600 },
    { month: 'Feb', mrr: 46500 }, { month: 'Mar', mrr: 47832 },
  ],
  funnel: [
    { stage: 'Visitors',   count: 24800, pct: 100  },
    { stage: 'Sign-ups',   count: 1847,  pct: 7.4  },
    { stage: 'Trials',     count: 234,   pct: 0.94 },
    { stage: 'Customers',  count: 89,    pct: 0.36 },
  ],
  activity: [
    { time: '2 min',  icon: '💳', text: 'New subscription: TechCorp ($299/mo)' },
    { time: '14 min', icon: '👤', text: 'New trial started: sarah@startup.io' },
    { time: '1h',     icon: '🎯', text: 'Campaign "Q1 SaaS" hit 15% CTR' },
    { time: '2h',     icon: '⚠️', text: 'Churn alert: Acme Corp (3 months inactive)' },
    { time: '3h',     icon: '📈', text: 'Feature "Export" used by 234 users today' },
    { time: '4h',     icon: '🔑', text: 'New API key generated by admin@acme.com' },
  ],
  customers: [
    { name: 'TechCorp AB',  email: 'billing@techcorp.se',  mrr: 2400, status: 'active',   score: 92, plan: 'Enterprise', since: 'Jan 2024' },
    { name: 'StartupX Inc', email: 'cfo@startupx.com',     mrr: 1800, status: 'active',   score: 88, plan: 'Growth',     since: 'Mar 2024' },
    { name: 'GrowthLabs',   email: 'ops@growthlabs.io',    mrr: 1600, status: 'at-risk',  score: 61, plan: 'Growth',     since: 'Jun 2023' },
    { name: 'Acme Corp',    email: 'admin@acme.com',        mrr: 1200, status: 'churning', score: 34, plan: 'Starter',    since: 'Aug 2023' },
    { name: 'Nimble SaaS',  email: 'ceo@nimble.co',         mrr: 990,  status: 'active',   score: 95, plan: 'Growth',     since: 'Nov 2024' },
    { name: 'CloudPeak Ltd',email: 'ops@cloudpeak.io',      mrr: 850,  status: 'active',   score: 79, plan: 'Starter',    since: 'Feb 2025' },
    { name: 'Zenith Labs',  email: 'finance@zenith.dev',    mrr: 720,  status: 'at-risk',  score: 58, plan: 'Starter',    since: 'Apr 2024' },
  ],
  automations: [
    { name: 'Trial → Paid Nudge',   status: 'running', triggered_today: 47, success_rate: 34, last_run: '3 min ago' },
    { name: 'Churn Prevention',      status: 'running', triggered_today: 12, success_rate: 28, last_run: '11 min ago' },
    { name: 'Onboarding Sequence',   status: 'running', triggered_today: 89, success_rate: 72, last_run: '1 min ago' },
    { name: 'Win-back Campaign',     status: 'paused',  triggered_today: 0,  success_rate: 18, last_run: '2 days ago' },
    { name: 'Upsell — Power Users',  status: 'running', triggered_today: 23, success_rate: 41, last_run: '8 min ago' },
    { name: 'NPS Survey Trigger',    status: 'running', triggered_today: 34, success_rate: 61, last_run: '22 min ago' },
  ],
  campaigns: [
    { name: 'Q1 SaaS Founders',  channel: 'Email',   sent: 4200, opens: 1386, clicks: 630, ctr: '15.0%', status: 'live' },
    { name: 'Retargeting — PPC', channel: 'Google',  sent: 8900, opens: 8900, clicks: 534, ctr: '6.0%',  status: 'live' },
    { name: 'LinkedIn ABM',      channel: 'LinkedIn',sent: 2100, opens: 945,  clicks: 189, ctr: '9.0%',  status: 'live' },
    { name: 'Jan Win-back',      channel: 'Email',   sent: 1800, opens: 360,  clicks: 72,  ctr: '4.0%',  status: 'ended' },
    { name: 'Product Hunt Drop', channel: 'Social',  sent: 5200, opens: 2860, clicks: 1040,ctr: '20.0%', status: 'ended' },
  ],
};

// ─── Nav config ──────────────────────────────────────────────────────────────
const NAV_ITEMS = [
  { id: 'overview',   label: 'Overview',    icon: '◈', desc: 'KPIs & live feed' },
  { id: 'growth',     label: 'Growth',      icon: '⬆', desc: 'Funnel & campaigns' },
  { id: 'revenue',    label: 'Revenue',     icon: '◎', desc: 'MRR, ARR, churn' },
  { id: 'product',    label: 'Product',     icon: '⬡', desc: 'Features & cohorts' },
  { id: 'automation', label: 'Automation',  icon: '⚙', desc: 'Flows & sequences' },
  { id: 'customers',  label: 'Customers',   icon: '◉', desc: 'Accounts & health' },
  { id: 'system',     label: 'System',      icon: '⬢', desc: 'Integrations & team' },
];

// ─── Shared UI components ─────────────────────────────────────────────────────
function Card({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return (
    <div style={{
      background: C.surface, border: `1px solid ${C.border}`,
      borderRadius: 12, padding: 20, ...style,
    }}>
      {children}
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ fontSize: 11, fontWeight: 600, color: C.text3, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 16 }}>
      {children}
    </div>
  );
}

function MetricCard({
  label, value, sub, trend, trendUp, color = C.blue, mono = true,
}: {
  label: string; value: string; sub?: string; trend?: string; trendUp?: boolean; color?: string; mono?: boolean;
}) {
  return (
    <Card style={{ flex: 1, minWidth: 160 }}>
      <div style={{ fontSize: 11, fontWeight: 600, color: C.text3, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 10 }}>
        {label}
      </div>
      <div style={{
        fontSize: 28, fontWeight: 700, color: C.text, letterSpacing: '-1px',
        fontFamily: mono ? C.mono : C.ui, marginBottom: 6,
      }}>
        {value}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
        {trend && (
          <span style={{
            fontSize: 12, fontWeight: 600,
            color: trendUp ? C.green : C.red,
            background: trendUp ? C.greenAlpha : C.redAlpha,
            padding: '2px 7px', borderRadius: 4,
            fontFamily: C.mono,
          }}>
            {trendUp ? '↑' : '↓'} {trend}
          </span>
        )}
        {sub && <span style={{ fontSize: 12, color: C.text3 }}>{sub}</span>}
      </div>
    </Card>
  );
}

function StatusPill({ status }: { status: string }) {
  const map: Record<string, { color: string; bg: string; label: string }> = {
    running: { color: C.green,  bg: C.greenAlpha,  label: '● Running' },
    paused:  { color: C.yellow, bg: C.yellowAlpha, label: '⏸ Paused' },
    failed:  { color: C.red,    bg: C.redAlpha,    label: '✕ Failed' },
    live:    { color: C.green,  bg: C.greenAlpha,  label: '● Live' },
    ended:   { color: C.text3,  bg: C.surface3,    label: '◼ Ended' },
    active:  { color: C.green,  bg: C.greenAlpha,  label: 'Active' },
    'at-risk':{ color: C.yellow,bg: C.yellowAlpha, label: 'At Risk' },
    churning:{ color: C.red,    bg: C.redAlpha,    label: 'Churning' },
  };
  const s = map[status] || { color: C.text2, bg: C.surface2, label: status };
  return (
    <span style={{
      fontSize: 11, fontWeight: 600, color: s.color, background: s.bg,
      padding: '3px 8px', borderRadius: 5, whiteSpace: 'nowrap',
    }}>
      {s.label}
    </span>
  );
}

function HealthScore({ score }: { score: number }) {
  const color = score > 80 ? C.green : score > 60 ? C.yellow : C.red;
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
      <div style={{
        width: 48, height: 4, borderRadius: 2, background: C.surface3, overflow: 'hidden',
      }}>
        <div style={{ width: `${score}%`, height: '100%', background: color, borderRadius: 2, transition: 'width 0.3s' }} />
      </div>
      <span style={{ fontSize: 13, fontWeight: 600, color, fontFamily: C.mono }}>{score}</span>
    </div>
  );
}

// ─── Bar chart (CSS only) ─────────────────────────────────────────────────────
function BarChart({ data, color = C.blue, height = 120 }: {
  data: { month: string; mrr: number }[]; color?: string; height?: number;
}) {
  const max = Math.max(...data.map(d => d.mrr));
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: 4, height, paddingBottom: 20, position: 'relative' }}>
      {data.map((d, i) => {
        const h = Math.round((d.mrr / max) * (height - 24));
        const isLast = i === data.length - 1;
        return (
          <div key={d.month} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
            <div
              title={`$${d.mrr.toLocaleString()}`}
              style={{
                width: '100%', height: h,
                background: isLast ? color : `${color}66`,
                borderRadius: '3px 3px 0 0',
                transition: 'background 0.15s',
                cursor: 'default',
                borderTop: isLast ? `2px solid ${color}` : 'none',
              }}
              onMouseEnter={e => { (e.currentTarget as HTMLDivElement).style.background = color; }}
              onMouseLeave={e => { (e.currentTarget as HTMLDivElement).style.background = isLast ? color : `${color}66`; }}
            />
            <span style={{ fontSize: 9, color: C.text3, fontFamily: C.mono }}>{d.month}</span>
          </div>
        );
      })}
    </div>
  );
}

// ─── Views ────────────────────────────────────────────────────────────────────

function OverviewView() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* KPI row */}
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="MRR" value={`$${DEMO_DATA.mrr.toLocaleString()}`} trend={`${DEMO_DATA.mrr_growth}%`} trendUp sub="vs last month" />
        <MetricCard label="Active Users" value={DEMO_DATA.active_users.toLocaleString()} trend={`${DEMO_DATA.active_users_growth}%`} trendUp sub="30-day active" color={C.purple} />
        <MetricCard label="Conversion" value={`${DEMO_DATA.conversion_rate}%`} trend={`+${DEMO_DATA.conversion_change}pp`} trendUp sub="trial → paid" color={C.green} />
        <MetricCard label="Churn Rate" value={`${DEMO_DATA.churn_rate}%`} trend={`${Math.abs(DEMO_DATA.churn_change)}pp`} trendUp={DEMO_DATA.churn_change < 0} sub="monthly churn" color={C.yellow} />
      </div>

      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        {/* MRR chart */}
        <Card style={{ flex: 2, minWidth: 280 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <div>
              <SectionTitle>MRR — 12 months</SectionTitle>
              <div style={{ fontSize: 22, fontWeight: 700, color: C.text, fontFamily: C.mono, letterSpacing: '-0.5px' }}>
                $47,832 <span style={{ fontSize: 13, color: C.green, fontFamily: C.ui }}>↑ 12.4%</span>
              </div>
            </div>
            <div style={{ fontSize: 11, color: C.text3, textAlign: 'right' }}>
              <div style={{ color: C.text2, fontFamily: C.mono }}>ARR</div>
              <div style={{ color: C.blue, fontFamily: C.mono, fontSize: 14, fontWeight: 600 }}>$573,984</div>
            </div>
          </div>
          <BarChart data={DEMO_DATA.revenue_history} height={130} />
        </Card>

        {/* Activity feed */}
        <Card style={{ flex: 1, minWidth: 260 }}>
          <SectionTitle>Live Activity</SectionTitle>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
            {DEMO_DATA.activity.map((a, i) => (
              <div key={i} style={{
                display: 'flex', gap: 10, padding: '10px 0',
                borderBottom: i < DEMO_DATA.activity.length - 1 ? `1px solid ${C.border}` : 'none',
                alignItems: 'flex-start',
              }}>
                <span style={{ fontSize: 16, flexShrink: 0, marginTop: 1 }}>{a.icon}</span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 13, color: C.text, lineHeight: 1.4 }}>{a.text}</div>
                  <div style={{ fontSize: 11, color: C.text3, marginTop: 2, fontFamily: C.mono }}>{a.time}</div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Secondary KPIs */}
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="LTV" value={`$${DEMO_DATA.ltv.toLocaleString()}`} sub="avg lifetime value" color={C.purple} />
        <MetricCard label="CAC" value={`$${DEMO_DATA.cac}`} sub="cost to acquire" color={C.yellow} />
        <MetricCard label="LTV:CAC" value={`${DEMO_DATA.ltv_cac_ratio}×`} sub="ratio (>3 = healthy)" trend="Excellent" trendUp color={C.green} />
        <MetricCard label="Trial → Paid" value={`${Math.round((DEMO_DATA.trial_converted / DEMO_DATA.trial_started) * 100)}%`} sub={`${DEMO_DATA.trial_converted} of ${DEMO_DATA.trial_started}`} color={C.blue} />
      </div>
    </div>
  );
}

function GrowthView() {
  const maxCount = DEMO_DATA.funnel[0].count;
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        {/* Funnel */}
        <Card style={{ flex: 1, minWidth: 300 }}>
          <SectionTitle>Acquisition Funnel</SectionTitle>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {DEMO_DATA.funnel.map((f, i) => {
              const colors = [C.blue, C.purple, C.green, C.yellow];
              const w = (f.count / maxCount) * 100;
              return (
                <div key={f.stage}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                    <span style={{ fontSize: 13, color: C.text2 }}>{f.stage}</span>
                    <div style={{ display: 'flex', gap: 12 }}>
                      <span style={{ fontSize: 13, fontWeight: 600, color: C.text, fontFamily: C.mono }}>{f.count.toLocaleString()}</span>
                      <span style={{ fontSize: 12, color: C.text3, fontFamily: C.mono, width: 40, textAlign: 'right' }}>{f.pct}%</span>
                    </div>
                  </div>
                  <div style={{ height: 8, background: C.surface2, borderRadius: 4, overflow: 'hidden' }}>
                    <div style={{ width: `${w}%`, height: '100%', background: colors[i], borderRadius: 4, transition: 'width 0.5s ease' }} />
                  </div>
                </div>
              );
            })}
          </div>
          <div style={{ marginTop: 16, padding: '12px', background: C.surface2, borderRadius: 8 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ fontSize: 12, color: C.text3 }}>Overall conversion</span>
              <span style={{ fontSize: 13, fontWeight: 700, color: C.green, fontFamily: C.mono }}>0.36%</span>
            </div>
          </div>
        </Card>

        {/* A/B Tests */}
        <Card style={{ flex: 1, minWidth: 280 }}>
          <SectionTitle>A/B Tests — Active</SectionTitle>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {[
              { name: 'Homepage Hero Copy', varA: 42.1, varB: 38.7, winner: 'A', status: 'running', confidence: 94 },
              { name: 'Pricing CTA Button', varA: 3.2, varB: 4.8, winner: 'B', status: 'running', confidence: 87 },
              { name: 'Trial Length (7 vs 14d)', varA: 28.4, varB: 31.2, winner: 'B', status: 'ended', confidence: 99 },
            ].map(t => (
              <div key={t.name} style={{ padding: 12, background: C.surface2, borderRadius: 8 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                  <span style={{ fontSize: 13, color: C.text, fontWeight: 500 }}>{t.name}</span>
                  <StatusPill status={t.status} />
                </div>
                <div style={{ display: 'flex', gap: 8, marginBottom: 6 }}>
                  {['A', 'B'].map(v => (
                    <div key={v} style={{
                      flex: 1, padding: '6px 10px', borderRadius: 6,
                      background: t.winner === v && t.status === 'ended' ? C.greenAlpha : C.surface,
                      border: `1px solid ${t.winner === v && t.status === 'ended' ? C.green : C.border}`,
                    }}>
                      <div style={{ fontSize: 10, color: C.text3, marginBottom: 2 }}>Variant {v}</div>
                      <div style={{ fontSize: 16, fontWeight: 700, color: C.text, fontFamily: C.mono }}>
                        {v === 'A' ? t.varA : t.varB}%
                        {t.winner === v && t.status === 'ended' && <span style={{ fontSize: 11, color: C.green, marginLeft: 4 }}>✓ Winner</span>}
                      </div>
                    </div>
                  ))}
                </div>
                <div style={{ fontSize: 11, color: C.text3 }}>Confidence: <span style={{ color: t.confidence > 95 ? C.green : C.yellow, fontFamily: C.mono }}>{t.confidence}%</span></div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Campaign table */}
      <Card>
        <SectionTitle>Campaigns</SectionTitle>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${C.border}` }}>
              {['Campaign', 'Channel', 'Sent', 'Opens', 'Clicks', 'CTR', 'Status'].map(h => (
                <th key={h} style={{ padding: '6px 12px 10px', textAlign: 'left', color: C.text3, fontWeight: 500, fontSize: 11, letterSpacing: '0.06em', textTransform: 'uppercase' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {DEMO_DATA.campaigns.map((c, i) => (
              <tr key={i}
                style={{ borderBottom: `1px solid ${C.border}`, transition: 'background 0.1s', cursor: 'default' }}
                onMouseEnter={e => (e.currentTarget.style.background = C.surface2)}
                onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
              >
                <td style={{ padding: '12px 12px', color: C.text, fontWeight: 500 }}>{c.name}</td>
                <td style={{ padding: '12px 12px' }}>
                  <span style={{ fontSize: 11, color: C.blue, background: C.blueAlpha, padding: '2px 8px', borderRadius: 4 }}>{c.channel}</span>
                </td>
                <td style={{ padding: '12px 12px', color: C.text2, fontFamily: C.mono }}>{c.sent.toLocaleString()}</td>
                <td style={{ padding: '12px 12px', color: C.text2, fontFamily: C.mono }}>{c.opens.toLocaleString()}</td>
                <td style={{ padding: '12px 12px', color: C.text2, fontFamily: C.mono }}>{c.clicks.toLocaleString()}</td>
                <td style={{ padding: '12px 12px', color: C.green, fontFamily: C.mono, fontWeight: 600 }}>{c.ctr}</td>
                <td style={{ padding: '12px 12px' }}><StatusPill status={c.status} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    </div>
  );
}

function RevenueView() {
  const breakdown = [
    { plan: 'Enterprise', customers: 12, mrr: 18400, color: C.blue },
    { plan: 'Growth',     customers: 47, mrr: 21300, color: C.purple },
    { plan: 'Starter',    customers: 156,mrr: 8132,  color: C.green },
  ];
  const totalMrr = breakdown.reduce((s, b) => s + b.mrr, 0);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="MRR" value="$47,832" trend="12.4%" trendUp sub="vs last month" />
        <MetricCard label="ARR" value="$573,984" trend="12.4%" trendUp sub="annualized" color={C.purple} />
        <MetricCard label="New MRR" value="$4,820" sub="this month" trend="+18%" trendUp color={C.green} />
        <MetricCard label="Churned MRR" value="$1,240" sub="this month" trend="-8%" trendUp={false} color={C.red} />
      </div>

      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        {/* MRR Chart */}
        <Card style={{ flex: 2, minWidth: 300 }}>
          <SectionTitle>MRR Growth — Last 12 Months</SectionTitle>
          <BarChart data={DEMO_DATA.revenue_history} height={160} />
        </Card>

        {/* Plan breakdown */}
        <Card style={{ flex: 1, minWidth: 220 }}>
          <SectionTitle>Revenue by Plan</SectionTitle>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {breakdown.map(b => (
              <div key={b.plan}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}>
                  <div>
                    <span style={{ fontSize: 13, color: C.text, fontWeight: 500 }}>{b.plan}</span>
                    <span style={{ fontSize: 11, color: C.text3, marginLeft: 8 }}>{b.customers} customers</span>
                  </div>
                  <span style={{ fontSize: 13, fontWeight: 700, color: C.text, fontFamily: C.mono }}>
                    ${b.mrr.toLocaleString()}
                  </span>
                </div>
                <div style={{ height: 6, background: C.surface2, borderRadius: 3, overflow: 'hidden' }}>
                  <div style={{ width: `${(b.mrr / totalMrr) * 100}%`, height: '100%', background: b.color, borderRadius: 3 }} />
                </div>
                <div style={{ fontSize: 11, color: C.text3, marginTop: 3, fontFamily: C.mono }}>
                  {Math.round((b.mrr / totalMrr) * 100)}% of MRR
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Churn metrics */}
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <Card style={{ flex: 1 }}>
          <SectionTitle>Churn Analysis</SectionTitle>
          <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
            {[
              { label: 'Logo Churn', value: '2.1%', sub: 'customers leaving', good: true },
              { label: 'Revenue Churn', value: '1.4%', sub: 'MRR at risk', good: true },
              { label: 'Net Revenue Retention', value: '118%', sub: 'expansion > churn', good: true },
              { label: 'Avg Days Before Churn', value: '94d', sub: 'from signup', good: false },
            ].map(m => (
              <div key={m.label} style={{ flex: '1 1 140px' }}>
                <div style={{ fontSize: 11, color: C.text3, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 6 }}>{m.label}</div>
                <div style={{ fontSize: 22, fontWeight: 700, color: C.text, fontFamily: C.mono, letterSpacing: '-0.5px' }}>{m.value}</div>
                <div style={{ fontSize: 12, color: C.text3, marginTop: 2 }}>{m.sub}</div>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
}

function ProductView() {
  const features = [
    { name: 'Dashboard',     dau: 1640, wau: 1847, trend: '+5%',  color: C.blue },
    { name: 'Export',        dau: 234,  wau: 891,  trend: '+18%', color: C.green },
    { name: 'Automations',   dau: 312,  wau: 734,  trend: '+11%', color: C.purple },
    { name: 'Reports',       dau: 189,  wau: 620,  trend: '+3%',  color: C.blue },
    { name: 'Integrations',  dau: 87,   wau: 340,  trend: '-2%',  color: C.yellow },
    { name: 'Team Mgmt',     dau: 64,   wau: 210,  trend: '+7%',  color: C.green },
    { name: 'API Access',    dau: 420,  wau: 680,  trend: '+22%', color: C.purple },
    { name: 'Webhooks',      dau: 145,  wau: 390,  trend: '+9%',  color: C.blue },
  ];

  const cohorts = [
    { cohort: 'Jan 2025', w1: 100, w2: 74, w4: 61, w8: 48, w12: 41 },
    { cohort: 'Feb 2025', w1: 100, w2: 71, w4: 58, w8: 45, w12: 39 },
    { cohort: 'Mar 2025', w1: 100, w2: 76, w4: 63, w8: 51, w12: null },
    { cohort: 'Apr 2025', w1: 100, w2: 78, w4: 65, w8: null, w12: null },
    { cohort: 'May 2025', w1: 100, w2: 80, w4: null, w8: null, w12: null },
  ];

  function retentionColor(val: number | null): React.CSSProperties {
    if (val === null) return { background: C.surface2, color: C.text3 };
    if (val >= 70) return { background: 'rgba(16,185,129,0.25)', color: C.green };
    if (val >= 50) return { background: 'rgba(59,130,246,0.2)', color: C.blue };
    if (val >= 30) return { background: 'rgba(245,158,11,0.2)', color: C.yellow };
    return { background: 'rgba(239,68,68,0.15)', color: C.red };
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="DAU" value="1,640" trend="+5.2%" trendUp sub="daily active users" />
        <MetricCard label="WAU" value="1,847" trend="+8.2%" trendUp sub="weekly active users" color={C.purple} />
        <MetricCard label="Avg Session" value="12m" sub="per user" trend="+1.4m" trendUp color={C.green} />
        <MetricCard label="Feature Adoption" value="68%" sub="used 3+ features" trend="+4pp" trendUp color={C.yellow} />
      </div>

      {/* Feature heatmap */}
      <Card>
        <SectionTitle>Feature Usage — This Week</SectionTitle>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 10 }}>
          {features.map(f => {
            const intensity = f.dau / 1847;
            return (
              <div key={f.name} style={{
                padding: '12px 14px', background: C.surface2, borderRadius: 8,
                border: `1px solid ${C.border}`,
                borderLeft: `3px solid ${f.color}`,
              }}>
                <div style={{ fontSize: 12, color: C.text2, marginBottom: 6 }}>{f.name}</div>
                <div style={{ fontSize: 18, fontWeight: 700, color: C.text, fontFamily: C.mono }}>{f.dau.toLocaleString()}</div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 6 }}>
                  <span style={{ fontSize: 11, color: C.text3 }}>WAU: {f.wau.toLocaleString()}</span>
                  <span style={{ fontSize: 11, fontFamily: C.mono, color: f.trend.startsWith('+') ? C.green : C.red }}>{f.trend}</span>
                </div>
                <div style={{ marginTop: 8, height: 3, background: C.surface3, borderRadius: 2 }}>
                  <div style={{ width: `${intensity * 100}%`, height: '100%', background: f.color, borderRadius: 2 }} />
                </div>
              </div>
            );
          })}
        </div>
      </Card>

      {/* Cohort retention */}
      <Card>
        <SectionTitle>Cohort Retention</SectionTitle>
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: '3px', fontSize: 13 }}>
            <thead>
              <tr>
                <th style={{ padding: '6px 10px', textAlign: 'left', color: C.text3, fontSize: 11, fontWeight: 500 }}>Cohort</th>
                {['Week 1', 'Week 2', 'Week 4', 'Week 8', 'Week 12'].map(h => (
                  <th key={h} style={{ padding: '6px 10px', color: C.text3, fontSize: 11, fontWeight: 500, textAlign: 'center', minWidth: 70 }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {cohorts.map(row => (
                <tr key={row.cohort}>
                  <td style={{ padding: '4px 10px', color: C.text2, fontSize: 12, fontFamily: C.mono }}>{row.cohort}</td>
                  {[row.w1, row.w2, row.w4, row.w8, row.w12].map((v, i) => (
                    <td key={i} style={{ padding: 3, textAlign: 'center' }}>
                      <div style={{
                        padding: '8px 6px', borderRadius: 6, fontSize: 13, fontWeight: 600,
                        fontFamily: C.mono, ...retentionColor(v),
                      }}>
                        {v !== null ? `${v}%` : '—'}
                      </div>
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}

function AutomationView() {
  const [automations, setAutomations] = useState(DEMO_DATA.automations.map(a => ({ ...a })));

  function toggleStatus(i: number) {
    setAutomations(prev => prev.map((a, idx) =>
      idx === i ? { ...a, status: a.status === 'running' ? 'paused' : 'running' } : a
    ));
  }

  const totalTriggered = automations.reduce((s, a) => s + a.triggered_today, 0);
  const avgSuccess = Math.round(automations.filter(a => a.status === 'running').reduce((s, a) => s + a.success_rate, 0) / automations.filter(a => a.status === 'running').length);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="Triggered Today" value={totalTriggered.toString()} sub="across all flows" trend="+12%" trendUp />
        <MetricCard label="Avg Success Rate" value={`${avgSuccess}%`} sub="active automations" trend="+3pp" trendUp color={C.green} />
        <MetricCard label="Active Flows" value={automations.filter(a => a.status === 'running').length.toString()} sub={`of ${automations.length} total`} color={C.purple} />
        <MetricCard label="Emails Sent" value="892" sub="last 24h" trend="+7%" trendUp color={C.yellow} />
      </div>

      <Card>
        <SectionTitle>Automation Flows</SectionTitle>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {automations.map((a, i) => (
            <div key={a.name} style={{
              display: 'flex', alignItems: 'center', gap: 14,
              padding: '14px 16px', background: C.surface2, borderRadius: 10,
              border: `1px solid ${C.border}`,
              transition: 'border-color 0.15s',
            }}
              onMouseEnter={e => (e.currentTarget.style.borderColor = C.border2)}
              onMouseLeave={e => (e.currentTarget.style.borderColor = C.border)}
            >
              {/* Status indicator */}
              <div style={{
                width: 10, height: 10, borderRadius: '50%', flexShrink: 0,
                background: a.status === 'running' ? C.green : C.yellow,
                boxShadow: a.status === 'running' ? `0 0 8px ${C.green}88` : 'none',
              }} />

              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 14, fontWeight: 500, color: C.text, marginBottom: 2 }}>{a.name}</div>
                <div style={{ fontSize: 11, color: C.text3 }}>Last run: {a.last_run}</div>
              </div>

              {/* Stats */}
              <div style={{ display: 'flex', gap: 20, flexShrink: 0 }}>
                <div style={{ textAlign: 'center', minWidth: 60 }}>
                  <div style={{ fontSize: 18, fontWeight: 700, color: C.text, fontFamily: C.mono }}>{a.triggered_today}</div>
                  <div style={{ fontSize: 10, color: C.text3, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Triggered</div>
                </div>
                <div style={{ textAlign: 'center', minWidth: 60 }}>
                  <div style={{ fontSize: 18, fontWeight: 700, fontFamily: C.mono, color: a.success_rate > 50 ? C.green : a.success_rate > 25 ? C.yellow : C.red }}>
                    {a.success_rate}%
                  </div>
                  <div style={{ fontSize: 10, color: C.text3, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Success</div>
                </div>
              </div>

              <StatusPill status={a.status} />

              <button
                onClick={() => toggleStatus(i)}
                style={{
                  padding: '6px 14px', background: 'none',
                  border: `1px solid ${C.border2}`, borderRadius: 6,
                  color: C.text2, fontSize: 12, cursor: 'pointer',
                  fontFamily: C.ui, transition: 'all 0.15s',
                  flexShrink: 0,
                }}
                onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.background = C.surface3; }}
                onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.background = 'none'; }}
              >
                {a.status === 'running' ? 'Pause' : 'Resume'}
              </button>
            </div>
          ))}
        </div>
      </Card>

      {/* Flow builder teaser */}
      <Card>
        <SectionTitle>Automation Templates</SectionTitle>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 10 }}>
          {[
            { name: 'Trial Expiry',     icon: '⏰', desc: 'Remind 3, 1 day before' },
            { name: 'NPS Follow-up',    icon: '⭐', desc: 'Segment by score' },
            { name: 'Usage Milestone',  icon: '🎯', desc: 'Celebrate activation' },
            { name: 'Upsell Trigger',   icon: '📈', desc: 'Power user detection' },
            { name: 'Re-engagement',    icon: '🔁', desc: '14d inactivity rule' },
            { name: 'Welcome Series',   icon: '👋', desc: '5-email onboarding' },
          ].map(t => (
            <div key={t.name} style={{
              padding: 14, background: C.surface2, borderRadius: 8,
              border: `1px dashed ${C.border2}`, cursor: 'pointer',
              transition: 'all 0.15s',
            }}
              onMouseEnter={e => {
                (e.currentTarget as HTMLDivElement).style.borderColor = C.blue;
                (e.currentTarget as HTMLDivElement).style.background = C.blueAlpha;
              }}
              onMouseLeave={e => {
                (e.currentTarget as HTMLDivElement).style.borderColor = C.border2;
                (e.currentTarget as HTMLDivElement).style.background = C.surface2;
              }}
            >
              <div style={{ fontSize: 20, marginBottom: 6 }}>{t.icon}</div>
              <div style={{ fontSize: 13, fontWeight: 500, color: C.text, marginBottom: 3 }}>{t.name}</div>
              <div style={{ fontSize: 11, color: C.text3 }}>{t.desc}</div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

function CustomersView() {
  const [search, setSearch] = useState('');
  const [segment, setSegment] = useState('all');

  const filtered = DEMO_DATA.customers.filter(c => {
    const matchSearch = c.name.toLowerCase().includes(search.toLowerCase()) || c.email.toLowerCase().includes(search.toLowerCase());
    const matchSegment = segment === 'all' || c.status === segment;
    return matchSearch && matchSegment;
  });

  const segments = [
    { id: 'all',      label: 'All',      count: DEMO_DATA.customers.length },
    { id: 'active',   label: 'Active',   count: DEMO_DATA.customers.filter(c => c.status === 'active').length },
    { id: 'at-risk',  label: 'At Risk',  count: DEMO_DATA.customers.filter(c => c.status === 'at-risk').length },
    { id: 'churning', label: 'Churning', count: DEMO_DATA.customers.filter(c => c.status === 'churning').length },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
        <MetricCard label="Total Accounts" value={DEMO_DATA.customers.length.toString()} sub="paying customers" />
        <MetricCard label="Avg MRR/Account" value="$1,394" sub="per customer" trend="+6.2%" trendUp color={C.purple} />
        <MetricCard label="At-Risk Accounts" value="2" sub="need attention" color={C.yellow} />
        <MetricCard label="Health Score Avg" value="72" sub="out of 100" color={C.green} />
      </div>

      <Card>
        {/* Filters */}
        <div style={{ display: 'flex', gap: 10, marginBottom: 16, flexWrap: 'wrap', alignItems: 'center' }}>
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search customers…"
            style={{
              flex: 1, minWidth: 200, height: 36, padding: '0 12px',
              background: C.surface2, border: `1px solid ${C.border}`,
              borderRadius: 8, color: C.text, fontSize: 13, outline: 'none',
              fontFamily: C.ui,
            }}
          />
          <div style={{ display: 'flex', gap: 4 }}>
            {segments.map(s => (
              <button key={s.id} onClick={() => setSegment(s.id)} style={{
                padding: '6px 12px', borderRadius: 6, border: 'none', cursor: 'pointer',
                fontFamily: C.ui, fontSize: 12, fontWeight: 500, transition: 'all 0.15s',
                background: segment === s.id ? C.blue : C.surface2,
                color: segment === s.id ? '#fff' : C.text2,
              }}>
                {s.label} <span style={{ opacity: 0.7, fontFamily: C.mono }}>{s.count}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Table */}
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${C.border}` }}>
              {['Company', 'Contact', 'Plan', 'MRR', 'Health', 'Since', 'Status'].map(h => (
                <th key={h} style={{ padding: '6px 12px 10px', textAlign: 'left', color: C.text3, fontWeight: 500, fontSize: 11, letterSpacing: '0.06em', textTransform: 'uppercase' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map((c, i) => (
              <tr key={i}
                style={{ borderBottom: `1px solid ${C.border}`, transition: 'background 0.1s', cursor: 'pointer' }}
                onMouseEnter={e => (e.currentTarget.style.background = C.surface2)}
                onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
              >
                <td style={{ padding: '12px 12px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div style={{
                      width: 30, height: 30, borderRadius: 6, background: C.blueAlpha,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: 11, fontWeight: 700, color: C.blue, flexShrink: 0,
                    }}>
                      {c.name.slice(0, 2).toUpperCase()}
                    </div>
                    <span style={{ fontWeight: 500, color: C.text }}>{c.name}</span>
                  </div>
                </td>
                <td style={{ padding: '12px 12px', color: C.text3, fontSize: 12 }}>{c.email}</td>
                <td style={{ padding: '12px 12px' }}>
                  <span style={{ fontSize: 11, color: C.purple, background: C.purpleAlpha, padding: '2px 8px', borderRadius: 4 }}>{c.plan}</span>
                </td>
                <td style={{ padding: '12px 12px', color: C.text, fontWeight: 600, fontFamily: C.mono }}>${c.mrr.toLocaleString()}</td>
                <td style={{ padding: '12px 12px' }}><HealthScore score={c.score} /></td>
                <td style={{ padding: '12px 12px', color: C.text3, fontFamily: C.mono, fontSize: 12 }}>{c.since}</td>
                <td style={{ padding: '12px 12px' }}><StatusPill status={c.status} /></td>
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && (
          <div style={{ textAlign: 'center', padding: '32px', color: C.text3, fontSize: 13 }}>No customers match your filter</div>
        )}
      </Card>
    </div>
  );
}

function SystemView() {
  const integrations = [
    { name: 'Stripe',     icon: '💳', status: 'connected', desc: 'Payments & subscriptions', color: C.green },
    { name: 'Shopify',    icon: '🛍',  status: 'connected', desc: 'E-commerce data sync',    color: C.green },
    { name: 'HubSpot',    icon: '🔶',  status: 'disconnected', desc: 'CRM integration',      color: C.text3 },
    { name: 'Slack',      icon: '💬',  status: 'connected', desc: 'Notifications & alerts',  color: C.green },
    { name: 'Segment',    icon: '⬡',   status: 'connected', desc: 'Event tracking',          color: C.green },
    { name: 'Intercom',   icon: '💭',  status: 'disconnected', desc: 'Customer support',      color: C.text3 },
    { name: 'Mixpanel',   icon: '📊',  status: 'pending',   desc: 'Product analytics',       color: C.yellow },
    { name: 'Sendgrid',   icon: '✉️',  status: 'connected', desc: 'Email delivery',          color: C.green },
  ];

  const team = [
    { name: 'Alex Chen',     email: 'ceo@demo.hypebit.com',     role: 'Owner',   avatar: 'AC', lastSeen: '1 min ago' },
    { name: 'Jordan Taylor', email: 'growth@demo.hypebit.com',  role: 'Growth',  avatar: 'JT', lastSeen: '4h ago' },
    { name: 'Sam Rivera',    email: 'analyst@demo.hypebit.com', role: 'Analyst', avatar: 'SR', lastSeen: 'Yesterday' },
    { name: 'Morgan Lee',    email: 'admin@demo.hypebit.com',   role: 'Admin',   avatar: 'ML', lastSeen: '3 min ago' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      {/* API Keys */}
      <Card>
        <SectionTitle>API Keys</SectionTitle>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {[
            { name: 'Production', key: 'hb_live_sk_••••••••••••••••3f8a', created: 'Jan 15, 2025', last_used: '2 min ago' },
            { name: 'Staging',    key: 'hb_test_sk_••••••••••••••••9c2d', created: 'Feb 3, 2025',  last_used: '1h ago' },
          ].map(k => (
            <div key={k.name} style={{
              display: 'flex', alignItems: 'center', gap: 14,
              padding: '12px 16px', background: C.surface2, borderRadius: 8,
              border: `1px solid ${C.border}`, flexWrap: 'wrap',
            }}>
              <div style={{
                width: 8, height: 8, borderRadius: '50%', background: C.green,
                boxShadow: `0 0 6px ${C.green}88`, flexShrink: 0,
              }} />
              <span style={{ fontSize: 13, fontWeight: 500, color: C.text, minWidth: 80 }}>{k.name}</span>
              <span style={{ fontFamily: C.mono, fontSize: 13, color: C.text2, flex: 1, minWidth: 200 }}>{k.key}</span>
              <span style={{ fontSize: 11, color: C.text3, minWidth: 120 }}>Created: {k.created}</span>
              <span style={{ fontSize: 11, color: C.green, minWidth: 120 }}>Used: {k.last_used}</span>
              <button style={{ padding: '4px 10px', background: C.surface3, border: 'none', borderRadius: 5, color: C.text2, fontSize: 11, cursor: 'pointer', fontFamily: C.ui }}>Revoke</button>
            </div>
          ))}
          <button style={{
            padding: '10px 16px', background: 'none', border: `1px dashed ${C.border2}`,
            borderRadius: 8, color: C.blue, fontSize: 13, cursor: 'pointer', fontFamily: C.ui,
            textAlign: 'left', transition: 'background 0.1s',
          }}
            onMouseEnter={e => (e.currentTarget.style.background = C.blueAlpha)}
            onMouseLeave={e => (e.currentTarget.style.background = 'none')}
          >
            + Generate new API key
          </button>
        </div>
      </Card>

      {/* Integrations */}
      <Card>
        <SectionTitle>Integrations</SectionTitle>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 10 }}>
          {integrations.map(int => (
            <div key={int.name} style={{
              padding: '14px 16px', background: C.surface2, borderRadius: 8,
              border: `1px solid ${int.status === 'connected' ? 'rgba(16,185,129,0.2)' : C.border}`,
              display: 'flex', alignItems: 'center', gap: 12,
              transition: 'border-color 0.15s',
            }}>
              <span style={{ fontSize: 20 }}>{int.icon}</span>
              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
                  <span style={{ fontSize: 13, fontWeight: 500, color: C.text }}>{int.name}</span>
                  <span style={{ fontSize: 11, color: int.color }}>
                    {int.status === 'connected' ? '✓' : int.status === 'pending' ? '⌛' : '○'}
                  </span>
                </div>
                <div style={{ fontSize: 11, color: C.text3 }}>{int.desc}</div>
              </div>
              <button style={{
                padding: '4px 10px', background: 'none',
                border: `1px solid ${int.status === 'connected' ? C.border : C.blue}`,
                borderRadius: 5, fontSize: 11, cursor: 'pointer', fontFamily: C.ui,
                color: int.status === 'connected' ? C.text3 : C.blue,
              }}>
                {int.status === 'connected' ? 'Config' : 'Connect'}
              </button>
            </div>
          ))}
        </div>
      </Card>

      {/* Team */}
      <Card>
        <SectionTitle>Team Members</SectionTitle>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {team.map((m, i) => (
            <div key={m.email} style={{
              display: 'flex', alignItems: 'center', gap: 14,
              padding: '12px 0', borderBottom: i < team.length - 1 ? `1px solid ${C.border}` : 'none',
            }}>
              <div style={{
                width: 34, height: 34, borderRadius: 8, background: C.blueAlpha,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 12, fontWeight: 700, color: C.blue, flexShrink: 0,
              }}>{m.avatar}</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 13, fontWeight: 500, color: C.text }}>{m.name}</div>
                <div style={{ fontSize: 12, color: C.text3 }}>{m.email}</div>
              </div>
              <span style={{
                fontSize: 11, padding: '2px 8px', borderRadius: 4, fontWeight: 600,
                background: m.role === 'Owner' ? C.purpleAlpha : C.surface2,
                color: m.role === 'Owner' ? C.purple : C.text2,
              }}>{m.role}</span>
              <span style={{ fontSize: 11, color: C.text3, minWidth: 80, textAlign: 'right' }}>{m.lastSeen}</span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

// ─── Main App ─────────────────────────────────────────────────────────────────
export default function App() {
  const [user, setUser] = useState<HypebitUser | null>(null);
  const [activeView, setActiveView] = useState('overview');
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [notifOpen, setNotifOpen] = useState(false);

  function handleLogin(u: HypebitUser) {
    setUser(u);
    setActiveView(getDefaultView(u.role));
  }

  if (!user) return <LoginScreen onLogin={handleLogin} />;

  const SIDEBAR_W = sidebarCollapsed ? 60 : 220;

  function renderView() {
    switch (activeView) {
      case 'overview':   return <OverviewView />;
      case 'growth':     return <GrowthView />;
      case 'revenue':    return <RevenueView />;
      case 'product':    return <ProductView />;
      case 'automation': return <AutomationView />;
      case 'customers':  return <CustomersView />;
      case 'system':     return <SystemView />;
      default:           return <OverviewView />;
    }
  }

  const currentNav = NAV_ITEMS.find(n => n.id === activeView);

  return (
    <div style={{ display: 'flex', height: '100vh', background: C.bg, fontFamily: C.ui, color: C.text, overflow: 'hidden' }}>

      {/* ── Sidebar ── */}
      <div style={{
        width: SIDEBAR_W, flexShrink: 0, background: C.surface,
        borderRight: `1px solid ${C.border}`,
        display: 'flex', flexDirection: 'column',
        transition: 'width 0.2s ease', overflow: 'hidden',
      }}>
        {/* Logo */}
        <div style={{
          height: 56, display: 'flex', alignItems: 'center',
          padding: sidebarCollapsed ? '0 14px' : '0 18px',
          borderBottom: `1px solid ${C.border}`, flexShrink: 0,
          gap: 10, overflow: 'hidden',
        }}>
          <svg width="24" height="24" viewBox="0 0 32 32" fill="none" style={{ flexShrink: 0 }}>
            <rect width="32" height="32" rx="7" fill="#111827"/>
            <rect x="4" y="16" width="6" height="12" rx="1" fill="#3B82F6"/>
            <rect x="13" y="10" width="6" height="18" rx="1" fill="#8B5CF6"/>
            <rect x="22" y="4" width="6" height="24" rx="1" fill="#10B981"/>
          </svg>
          {!sidebarCollapsed && (
            <span style={{ fontSize: 16, fontWeight: 700, color: C.text, letterSpacing: '-0.3px', whiteSpace: 'nowrap' }}>hypebit</span>
          )}
          <div style={{ flex: 1 }} />
          <button onClick={() => setSidebarCollapsed(p => !p)} style={{
            background: 'none', border: 'none', cursor: 'pointer', color: C.text3,
            fontSize: 14, padding: 2, flexShrink: 0,
          }}>
            {sidebarCollapsed ? '→' : '←'}
          </button>
        </div>

        {/* Nav */}
        <nav style={{ flex: 1, padding: '10px 8px', overflow: 'hidden' }}>
          {NAV_ITEMS.map(item => {
            const accessible = canAccess(user.role, item.id);
            const active = activeView === item.id;
            return (
              <button key={item.id}
                onClick={() => accessible && setActiveView(item.id)}
                title={sidebarCollapsed ? item.label : ''}
                style={{
                  width: '100%', display: 'flex', alignItems: 'center', gap: 10,
                  padding: sidebarCollapsed ? '10px 0' : '9px 10px',
                  justifyContent: sidebarCollapsed ? 'center' : 'flex-start',
                  marginBottom: 2, borderRadius: 8, border: 'none', cursor: accessible ? 'pointer' : 'not-allowed',
                  background: active ? C.blueAlpha : 'none',
                  color: active ? C.blue : accessible ? C.text2 : C.text3,
                  fontFamily: C.ui, fontSize: 13, fontWeight: active ? 600 : 400,
                  transition: 'all 0.12s', overflow: 'hidden',
                  opacity: accessible ? 1 : 0.4,
                  borderLeft: active ? `2px solid ${C.blue}` : '2px solid transparent',
                }}
                onMouseEnter={e => { if (accessible && !active) (e.currentTarget as HTMLButtonElement).style.background = C.surface2; }}
                onMouseLeave={e => { if (!active) (e.currentTarget as HTMLButtonElement).style.background = 'none'; }}
              >
                <span style={{ fontSize: 15, flexShrink: 0, fontFamily: 'monospace' }}>{item.icon}</span>
                {!sidebarCollapsed && (
                  <span style={{ whiteSpace: 'nowrap' }}>{item.label}</span>
                )}
              </button>
            );
          })}
        </nav>

        {/* User area */}
        <div style={{
          padding: sidebarCollapsed ? '12px 8px' : '12px 14px',
          borderTop: `1px solid ${C.border}`, flexShrink: 0,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, overflow: 'hidden' }}>
            <div style={{
              width: 30, height: 30, borderRadius: 7, background: C.blueAlpha,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 11, fontWeight: 700, color: C.blue, flexShrink: 0,
            }}>{user.avatar}</div>
            {!sidebarCollapsed && (
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 12, fontWeight: 600, color: C.text, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{user.name}</div>
                <div style={{ fontSize: 10, color: C.text3, whiteSpace: 'nowrap' }}>{user.role.toUpperCase()}</div>
              </div>
            )}
            {!sidebarCollapsed && (
              <button onClick={() => setUser(null)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: C.text3, fontSize: 12, padding: 4, flexShrink: 0 }} title="Sign out">⎋</button>
            )}
          </div>
        </div>
      </div>

      {/* ── Main area ── */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

        {/* Topbar */}
        <div style={{
          height: 56, display: 'flex', alignItems: 'center',
          padding: '0 24px', borderBottom: `1px solid ${C.border}`,
          background: C.surface, flexShrink: 0, gap: 12,
        }}>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 15, fontWeight: 600, color: C.text }}>{currentNav?.label || 'Dashboard'}</div>
            <div style={{ fontSize: 11, color: C.text3 }}>{currentNav?.desc}</div>
          </div>

          {/* Search */}
          <div style={{ position: 'relative' }}>
            <input placeholder="Search…" style={{
              height: 32, width: 200, padding: '0 12px 0 32px',
              background: C.surface2, border: `1px solid ${C.border}`,
              borderRadius: 8, color: C.text, fontSize: 13, outline: 'none', fontFamily: C.ui,
            }} />
            <span style={{ position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: C.text3, fontSize: 13 }}>⌕</span>
          </div>

          {/* Notifications */}
          <div style={{ position: 'relative' }}>
            <button onClick={() => setNotifOpen(p => !p)} style={{
              width: 34, height: 34, borderRadius: 8, background: C.surface2,
              border: `1px solid ${C.border}`, color: C.text2, fontSize: 15,
              cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
              position: 'relative',
            }}>
              🔔
              <span style={{
                position: 'absolute', top: 4, right: 4, width: 8, height: 8,
                background: C.blue, borderRadius: '50%', border: `2px solid ${C.surface}`,
              }} />
            </button>
            {notifOpen && (
              <div style={{
                position: 'absolute', top: 42, right: 0, width: 280,
                background: C.surface, border: `1px solid ${C.border2}`,
                borderRadius: 10, overflow: 'hidden', zIndex: 100,
                boxShadow: '0 8px 24px rgba(0,0,0,0.4)',
              }}>
                <div style={{ padding: '12px 16px', borderBottom: `1px solid ${C.border}`, fontSize: 12, fontWeight: 600, color: C.text2 }}>
                  Notifications
                </div>
                {DEMO_DATA.activity.slice(0, 3).map((a, i) => (
                  <div key={i} style={{ padding: '10px 16px', borderBottom: `1px solid ${C.border}`, display: 'flex', gap: 10 }}>
                    <span style={{ fontSize: 14 }}>{a.icon}</span>
                    <div>
                      <div style={{ fontSize: 12, color: C.text, lineHeight: 1.4 }}>{a.text}</div>
                      <div style={{ fontSize: 10, color: C.text3, marginTop: 2, fontFamily: C.mono }}>{a.time}</div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Avatar */}
          <div style={{
            width: 34, height: 34, borderRadius: 8, background: `linear-gradient(135deg, ${C.blue}, ${C.purple})`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 12, fontWeight: 700, color: '#fff', cursor: 'pointer', flexShrink: 0,
          }}>
            {user.avatar}
          </div>
        </div>

        {/* Content */}
        <div style={{ flex: 1, overflowY: 'auto', padding: 24 }} onClick={() => notifOpen && setNotifOpen(false)}>
          <div style={{ maxWidth: 1200 }}>
            {renderView()}
          </div>
        </div>
      </div>
    </div>
  );
}
