// ─── Legal Document System ────────────────────────────────────────────────

export type SigningLevel = 'L1' | 'L2' | 'L3'
export type DocStatus = 'proposed' | 'draft' | 'pending_signature' | 'signed' | 'expired' | 'rejected'
export type SignMethod = 'click' | 'email_otp' | 'bankid' | 'eid_eidas' | 'docusign'

export interface LegalDocument {
  id: string
  type: LegalDocType
  title: string
  party_a: string
  party_b: string
  signing_level: SigningLevel
  sign_method: SignMethod
  status: DocStatus
  created_at: string
  signed_at?: string
  expires_at?: string
  description: string
  required: boolean
  auto_proposed: boolean
  amount?: number
  currency?: string
  royalty_rate?: number
}

export type LegalDocType =
  | 'ip_license'
  | 'management_agreement'
  | 'service_agreement'
  | 'shareholder_agreement'
  | 'intercompany_loan'
  | 'employment_contract'
  | 'nda'
  | 'data_processing_agreement'
  | 'board_resolution'
  | 'founder_agreement'
  | 'option_agreement'
  | 'consulting_agreement'
  | 'vendor_contract'
  | 'gdpr_policy'
  | 'terms_of_service'
  | 'investment_agreement'
  // ── Nya typer ──────────────────────────────────────────────────────────
  | 'trademark_license'
  | 'transfer_pricing_policy'
  | 'non_compete'
  | 'equity_plan'
  | 'contractor_agreement'
  | 'platform_agreement'
  | 'mission_terms'
  | 'payout_terms'
  | 'ip_assignment'
  | 'enterprise_agreement'
  | 'sla'
  | 'pilot_agreement'
  | 'subcontractor_agreement'
  | 'payment_processing'
  | 'articles_of_association'
  | 'convertible_loan'
  | 'safe_agreement'
  | 'privacy_policy'
  | 'cookie_policy'
  | 'aml_policy'
  | 'kyc_procedures'
  | 'whistleblower_policy'
  | 'information_security_policy'
  | 'gdpr_compliance_framework'

export const DOC_TYPE_LABELS: Record<LegalDocType, string> = {
  ip_license: 'IP-licensavtal',
  management_agreement: 'Management Agreement',
  service_agreement: 'Service Agreement',
  shareholder_agreement: 'Aktieägaravtal',
  intercompany_loan: 'Koncernlån',
  employment_contract: 'Anställningsavtal',
  nda: 'Sekretessavtal (NDA)',
  data_processing_agreement: 'Personuppgiftsbiträdesavtal (DPA)',
  board_resolution: 'Styrelsebeslut',
  founder_agreement: 'Grundaravtal',
  option_agreement: 'Optionsavtal (ESOP)',
  consulting_agreement: 'Konsultavtal',
  vendor_contract: 'Leverantörsavtal',
  gdpr_policy: 'Integritetspolicy (GDPR)',
  terms_of_service: 'Användarvillkor',
  investment_agreement: 'Investeringsavtal',
  // ── Nya ──────────────────────────────────────────────────────────────
  trademark_license: 'Varumärkeslicensavtal',
  transfer_pricing_policy: 'Transfer Pricing Policy',
  non_compete: 'Konkurrensklausul',
  equity_plan: 'Equity/VSOP-plan',
  contractor_agreement: 'Uppdragsavtal (Contractor)',
  platform_agreement: 'Plattformsavtal (Zoomer)',
  mission_terms: 'Uppdragsvillkor (Mission)',
  payout_terms: 'Utbetalningsvillkor',
  ip_assignment: 'IP-överlåtelse',
  enterprise_agreement: 'Enterprise-avtal (SaaS)',
  sla: 'SLA (Service Level Agreement)',
  pilot_agreement: 'Pilotavtal (PoC)',
  subcontractor_agreement: 'Underleverantörsavtal',
  payment_processing: 'Payment Processing Agreement',
  articles_of_association: 'Bolagsordning',
  convertible_loan: 'Konvertibellån',
  safe_agreement: 'SAFE Agreement',
  privacy_policy: 'Privacy Policy (extern)',
  cookie_policy: 'Cookie Policy',
  aml_policy: 'AML Policy',
  kyc_procedures: 'KYC-rutiner',
  whistleblower_policy: 'Visselblåsarpolicy',
  information_security_policy: 'Informationssäkerhetspolicy',
  gdpr_compliance_framework: 'GDPR Compliance Framework',
}

export const SIGNING_LEVEL_LABELS: Record<SigningLevel, string> = {
  L1: 'Klick-signatur',
  L2: 'E-signatur',
  L3: 'Kvalificerad signatur',
}

export const SIGN_METHOD_LABELS: Record<SignMethod, string> = {
  click: '🖱️ Klick',
  email_otp: '📧 E-post OTP',
  bankid: '🇸🇪 BankID',
  eid_eidas: '🇪🇺 eIDAS',
  docusign: '🖊️ DocuSign',
}

export const DOC_TYPE_SIGNING_LEVEL: Record<LegalDocType, SigningLevel> = {
  ip_license: 'L3',
  management_agreement: 'L2',
  service_agreement: 'L2',
  shareholder_agreement: 'L3',
  intercompany_loan: 'L2',
  employment_contract: 'L2',
  nda: 'L1',
  data_processing_agreement: 'L2',
  board_resolution: 'L2',
  founder_agreement: 'L3',
  option_agreement: 'L3',
  consulting_agreement: 'L2',
  vendor_contract: 'L2',
  gdpr_policy: 'L1',
  terms_of_service: 'L1',
  investment_agreement: 'L3',
  // ── Nya ──────────────────────────────────────────────────────────────
  trademark_license: 'L3',
  transfer_pricing_policy: 'L2',
  non_compete: 'L2',
  equity_plan: 'L3',
  contractor_agreement: 'L2',
  platform_agreement: 'L1',
  mission_terms: 'L1',
  payout_terms: 'L1',
  ip_assignment: 'L3',
  enterprise_agreement: 'L2',
  sla: 'L2',
  pilot_agreement: 'L2',
  subcontractor_agreement: 'L2',
  payment_processing: 'L2',
  articles_of_association: 'L3',
  convertible_loan: 'L3',
  safe_agreement: 'L3',
  privacy_policy: 'L1',
  cookie_policy: 'L1',
  aml_policy: 'L1',
  kyc_procedures: 'L1',
  whistleblower_policy: 'L1',
  information_security_policy: 'L1',
  gdpr_compliance_framework: 'L2',
}

// BankID = Sweden only. Other jurisdictions get fallback.
export function getSignMethod(jurisdiction: string, level: SigningLevel): SignMethod {
  if (level === 'L1') return 'click'
  if (level === 'L3') {
    if (jurisdiction === 'SE') return 'bankid'
    if (jurisdiction.startsWith('EU')) return 'eid_eidas'
    return 'docusign'
  }
  // L2
  if (jurisdiction === 'SE') return 'bankid'
  if (jurisdiction.startsWith('EU')) return 'eid_eidas'
  return 'email_otp'
}

export const LEGAL_DOCUMENTS: LegalDocument[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // BEFINTLIGA DOKUMENT (bevarade intakta)
  // ══════════════════════════════════════════════════════════════════════════

  // ── IP-licensavtal ──────────────────────────────────────────────────────
  {
    id: 'ip-001',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group Dubai (IP Holding) → Wavult Operations',
    party_a: 'wavult-group',
    party_b: 'wavult-operations',
    signing_level: 'L3',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Exklusiv licens för all IP utvecklad inom Wavult Operations. Royalty 10% av nettointäkter.',
    required: true,
    auto_proposed: true,
    royalty_rate: 10,
  },
  {
    id: 'ip-002',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group Dubai (IP Holding) → QuiXzoom UAB',
    party_a: 'wavult-group',
    party_b: 'quixzoom-uab',
    signing_level: 'L3',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Icke-exklusiv licens för QuiXzoom-plattformen i EU. Royalty 5%.',
    required: true,
    auto_proposed: true,
    royalty_rate: 5,
  },
  {
    id: 'ip-003',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group Dubai (IP Holding) → Landvex Inc',
    party_a: 'wavult-group',
    party_b: 'landvex-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Icke-exklusiv licens för Landvex i USA. Royalty 8%.',
    required: true,
    auto_proposed: true,
    royalty_rate: 8,
  },
  {
    id: 'ip-004',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult Group Dubai (IP Holding) → Landvex AB',
    party_a: 'wavult-group',
    party_b: 'landvex-ab',
    signing_level: 'L3',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'IP-licens för Landvex-plattformen i Sverige/EU. Landvex AB äger INTE IP — licensierar från Dubai-holdingen. Royalty 7% av nettointäkter.',
    required: true,
    auto_proposed: true,
    royalty_rate: 7,
  },

  // ── Management Agreement ─────────────────────────────────────────────────
  {
    id: 'ma-001',
    type: 'management_agreement',
    title: 'Management Agreement — Landvex AB → Wavult Operations',
    party_a: 'wavult-group',
    party_b: 'wavult-operations',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Lednings- och konsulttjänster. Holding tillhandahåller strategisk ledning, juridik och ekonomi.',
    required: true,
    auto_proposed: true,
    amount: 25000,
    currency: 'SEK',
  },

  // ── Service Agreements ───────────────────────────────────────────────────
  {
    id: 'sa-001',
    type: 'service_agreement',
    title: 'Service Agreement — Wavult Operations → QuiXzoom UAB',
    party_a: 'wavult-operations',
    party_b: 'quixzoom-uab',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Tekniska plattformstjänster: hosting, API, support.',
    required: true,
    auto_proposed: true,
    amount: 3000,
    currency: 'EUR',
  },
  {
    id: 'sa-002',
    type: 'service_agreement',
    title: 'Service Agreement — Wavult Operations → Landvex Inc',
    party_a: 'wavult-operations',
    party_b: 'landvex-inc',
    signing_level: 'L2',
    sign_method: 'email_otp',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'Tekniska plattformstjänster för Landvex US.',
    required: true,
    auto_proposed: true,
    amount: 2500,
    currency: 'USD',
  },

  // ── Data Processing Agreements ───────────────────────────────────────────
  {
    id: 'dpa-001',
    type: 'data_processing_agreement',
    title: 'DPA — Wavult Operations ↔ QuiXzoom UAB',
    party_a: 'wavult-operations',
    party_b: 'quixzoom-uab',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-25',
    description: 'GDPR: reglerar behandling av personuppgifter mellan EU-bolag.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'dpa-002',
    type: 'data_processing_agreement',
    title: 'DPA — Wavult Operations ↔ Landvex Inc',
    party_a: 'wavult-operations',
    party_b: 'landvex-inc',
    signing_level: 'L2',
    sign_method: 'email_otp',
    status: 'draft',
    created_at: '2026-03-26',
    description: 'Reglerar behandling av personuppgifter för användare i USA och EU. Standardklausuler enligt SCCs inkluderade.',
    required: true,
    auto_proposed: false,
  },

  // ── Anställningsavtal ────────────────────────────────────────────────────
  {
    id: 'emp-001',
    type: 'employment_contract',
    title: 'Anställningsavtal — Erik Svensson',
    party_a: 'landvex-ab',
    party_b: 'erik-svensson',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Anställningsavtal för Erik Svensson som Chairman of the Board & Group CEO vid Landvex AB.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'emp-002',
    type: 'employment_contract',
    title: 'Anställningsavtal — Leon Russo De Cerame',
    party_a: 'landvex-ab',
    party_b: 'leon-russo',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Anställningsavtal för Leon Russo De Cerame som CEO Wavult Operations vid Landvex AB.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'emp-003',
    type: 'employment_contract',
    title: 'Anställningsavtal — Winston Bjarnemark',
    party_a: 'landvex-ab',
    party_b: 'winston-bjarnemark',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Anställningsavtal för Winston Bjarnemark som CFO vid Landvex AB.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'emp-004',
    type: 'employment_contract',
    title: 'Anställningsavtal — Dennis Bjarnemark',
    party_a: 'landvex-ab',
    party_b: 'dennis-bjarnemark',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Anställningsavtal för Dennis Bjarnemark som Chief Legal & Operations (Interim) vid Landvex AB.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'emp-005',
    type: 'employment_contract',
    title: 'Anställningsavtal — Johan Berglund',
    party_a: 'landvex-ab',
    party_b: 'johan-berglund',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Anställningsavtal för Johan Berglund som Group CTO vid Landvex AB.',
    required: true,
    auto_proposed: false,
  },

  // ── NDA ──────────────────────────────────────────────────────────────────
  {
    id: 'nda-001',
    type: 'nda',
    title: 'NDA — QuiXzoom Inc ↔ Potentiell investerare',
    party_a: 'quixzoom-inc',
    party_b: 'external-investor',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-26',
    description: 'Ömsesidigt sekretessavtal inför due diligence-process. Giltighet 24 månader.',
    required: false,
    auto_proposed: false,
  },

  // ── Aktieägaravtal ───────────────────────────────────────────────────────
  {
    id: 'sha-001',
    type: 'shareholder_agreement',
    title: 'Aktieägaravtal — QuiXzoom Inc',
    party_a: 'erik-svensson',
    party_b: 'wavult-group',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-26',
    description: 'Reglerar rättigheter och skyldigheter mellan aktieägare i QuiXzoom Inc. Inkluderar drag-along, tag-along och pre-emption rights.',
    required: true,
    auto_proposed: false,
  },

  // ── Founder Agreement ─────────────────────────────────────────────────────
  {
    id: 'fa-001',
    type: 'founder_agreement',
    title: 'Founder Agreement — Erik Svensson & Wavult Group',
    party_a: 'erik-svensson',
    party_b: 'wavult-group',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Grundaravtal som reglerar Eriks roll, ägarandel, vesting-schema och beslutsmandat inom Wavult-koncernen.',
    required: true,
    auto_proposed: false,
  },

  // ── Optionsavtal (ESOP) ───────────────────────────────────────────────────
  {
    id: 'opt-001',
    type: 'option_agreement',
    title: 'Optionsavtal (ESOP) — QuiXzoom Inc',
    party_a: 'quixzoom-inc',
    party_b: 'esop-pool',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-26',
    description: 'Employee Stock Option Plan för QuiXzoom Inc. 10% optionspool reserverad för nyckelpersoner. 4-årig vesting med 1-årig cliff.',
    required: false,
    auto_proposed: false,
  },

  // ── GDPR Integritetspolicy ────────────────────────────────────────────────
  {
    id: 'gdpr-001',
    type: 'gdpr_policy',
    title: 'GDPR Integritetspolicy — quiXzoom',
    party_a: 'quixzoom-inc',
    party_b: 'end-users',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'signed',
    created_at: '2026-03-20',
    signed_at: '2026-03-20',
    description: 'Integritetspolicy för quiXzoom-plattformen. Beskriver insamling, lagring och behandling av personuppgifter enligt GDPR och CCPA.',
    required: true,
    auto_proposed: false,
  },

  // ── Användarvillkor ────────────────────────────────────────────────────────
  {
    id: 'tos-001',
    type: 'terms_of_service',
    title: 'Användarvillkor — quiXzoom',
    party_a: 'quixzoom-inc',
    party_b: 'end-users',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'signed',
    created_at: '2026-03-20',
    signed_at: '2026-03-20',
    description: 'Användarvillkor för quiXzoom-plattformen. Reglerar fotografers och köpares rättigheter, ansvarsbegränsningar och betalningsvillkor.',
    required: true,
    auto_proposed: false,
  },

  // ── Styrelsebeslut ────────────────────────────────────────────────────────
  {
    id: 'br-001',
    type: 'board_resolution',
    title: 'Styrelsebeslut — Namnbyte Landvex AB',
    party_a: 'landvex-ab',
    party_b: 'landvex-ab',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'signed',
    created_at: '2026-03-25',
    signed_at: '2026-03-25',
    description: 'Styrelsebeslut om godkännande av bolagets namnbyte till Landvex AB. Protokoll undertecknat av styrelseledamöter.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'br-002',
    type: 'board_resolution',
    title: 'Styrelsebeslut — Bolagsbildning QuiXzoom Inc',
    party_a: 'wavult-group',
    party_b: 'quixzoom-inc',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'signed',
    created_at: '2026-03-25',
    signed_at: '2026-03-25',
    description: 'Styrelsebeslut om bildande av QuiXzoom Inc som Delaware C-Corp. Godkännande av bolagsordning och utgivande av grundaraktier.',
    required: true,
    auto_proposed: false,
  },

  // ── Konsultavtal ──────────────────────────────────────────────────────────
  {
    id: 'cons-001',
    type: 'consulting_agreement',
    title: 'Konsultavtal — Revisor (PwC/Deloitte)',
    party_a: 'landvex-ab',
    party_b: 'pwc-deloitte',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-26',
    description: 'Konsultavtal med revisionsbolag för revision, skatterådgivning och löpande redovisningstjänster för Landvex AB. Revisorsoffert skickad 25 mars till 8 byråer (PwC, Deloitte, KPMG, EY, Grant Thornton, BDO, Mazars, Advisense).',
    required: true,
    auto_proposed: false,
  },

  // ── Bolagsbildning — pågående processer ───────────────────────────────────
  {
    id: 'inc-001',
    type: 'board_resolution',
    title: 'QuiXzoom Inc — Stripe Atlas Delaware C-Corp',
    party_a: 'quixzoom-inc',
    party_b: 'stripe-atlas',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'Delaware C Corporation via Stripe Atlas. Ansökan inlämnad, väntar på pass-verifiering (same-day review). Cap table: Erik 70% / Wavult Group 20% / Option Pool 10%. KRITISKT: 83(b) election måste skickas in inom 30 dagar från registreringsdatum. Mercury Bank kopplas efter godkännande.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'inc-002',
    type: 'board_resolution',
    title: 'Landvex Inc — Texas Corporation SOSDirect',
    party_a: 'landvex-inc',
    party_b: 'sos-texas',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-25',
    description: 'Texas Corporation via SOSDirect Form 201. HALVKLAR — kvarstår: (1) Adress: Åvägen 9, 135 48 Tyresö på Director + Organizer, (2) Article 4: 10M aktier, kryssa B (no par value), (3) Initial Mailing: Northwest-adress Austin TX 78731, (4) Effectiveness: kryssa A, (5) Betala $300 + $25 expedited på sos.state.tx.us.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'inc-003',
    type: 'board_resolution',
    title: 'Wavult Group FZCO — Dubai DMCC Formation',
    party_a: 'wavult-group',
    party_b: 'dmcc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-25',
    description: 'Dubai Multi Commodities Centre (DMCC) Free Zone holding company. Business plan klar. Ansökan EJ påbörjad — starta på dmcc.ae/apply. Behövs för Dubai holding + IP-struktur. Skattefördel: 0% bolagsskatt på IP-royalties.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'inc-004',
    type: 'board_resolution',
    title: 'Landvex AB — Namnbyte från Sommarliden Holding AB',
    party_a: 'landvex-ab',
    party_b: 'bolagsverket',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'pending_signature',
    created_at: '2026-03-23',
    description: 'Namnbyte: Sommarliden Holding AB (org.nr 559141-7042) → Landvex AB. Inlämnat till Bolagsverket. Väntar på registrering (~1-2 veckor). Bolagets status: vilande, 100% ordning. Adress: Åvägen 9, 135 48 Tyresö.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'inc-005',
    type: 'board_resolution',
    title: 'QuiXzoom UAB — Weedle UAB Litauen',
    party_a: 'quixzoom-uab',
    party_b: 'weedle-uab',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'pending_signature',
    created_at: '2026-03-25',
    description: 'EU-bolag i Vilnius, Litauen via Weedle UAB. Compliance-förfrågan skickad till 6 byråer. Väntar på svar — besluta om rehabilitera befintlig eller bilda nytt bolag. GDPR-compliant, lägre bolagsskatt inom EU.',
    required: true,
    auto_proposed: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 1: INTERCOMPANY-AVTAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'ic-001',
    type: 'ip_license',
    title: 'IP-licensavtal — Wavult DevOps FZCO → QuiXzoom Inc (Delaware)',
    party_a: 'wavult-operations',
    party_b: 'quixzoom-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Sublicens av quiXzoom-plattformens IP från Wavult DevOps FZCO till QuiXzoom Inc. Täcker mjukvara, algoritmer och varumärket quiXzoom i USA. Royalty 6% av bruttointäkter. Arm\'s length-villkor per OECD Transfer Pricing Guidelines.',
    required: true,
    auto_proposed: true,
    royalty_rate: 6,
  },
  {
    id: 'ic-002',
    type: 'management_agreement',
    title: 'Management Services Agreement — Wavult Group FZCO → QuiXzoom Inc',
    party_a: 'wavult-group',
    party_b: 'quixzoom-inc',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Dubai Holding tillhandahåller strategisk ledning, finanskontroll, juridik och HR-support till QuiXzoom Inc. Fast månadsavgift + prestationsbaserad komponent. Dokumenterar internprisättning för skatteändamål.',
    required: true,
    auto_proposed: true,
    amount: 5000,
    currency: 'USD',
  },
  {
    id: 'ic-003',
    type: 'management_agreement',
    title: 'Management Services Agreement — Wavult Group FZCO → QuiXzoom UAB',
    party_a: 'wavult-group',
    party_b: 'quixzoom-uab',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Dubai Holding tillhandahåller strategisk ledning och kompetensöverföring till det litauiska bolaget. Månadsarvode 3 000 EUR. Kritiskt för att motivera vinstdistribution uppåt i strukturen.',
    required: true,
    auto_proposed: true,
    amount: 3000,
    currency: 'EUR',
  },
  {
    id: 'ic-004',
    type: 'management_agreement',
    title: 'Management Services Agreement — Wavult Group FZCO → Landvex AB',
    party_a: 'wavult-group',
    party_b: 'landvex-ab',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Holdingbolaget i Dubai fakturerar Landvex AB för strategisk ledning, styrelsekompetens och IP-förvaltning. 25 000 SEK/mån. Viktigt för internprisättning och skattemässig optimering.',
    required: true,
    auto_proposed: true,
    amount: 25000,
    currency: 'SEK',
  },
  {
    id: 'ic-005',
    type: 'management_agreement',
    title: 'Management Services Agreement — Wavult Group FZCO → Landvex Inc',
    party_a: 'wavult-group',
    party_b: 'landvex-inc',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Dubai Holding tillhandahåller lednings- och supporttjänster till det texanska bolaget. USD 4 000/mån. Arm\'s length-motiverat via comparable uncontrolled price-metoden.',
    required: true,
    auto_proposed: true,
    amount: 4000,
    currency: 'USD',
  },
  {
    id: 'ic-006',
    type: 'intercompany_loan',
    title: 'Koncernlånsavtal — Wavult Group FZCO → Landvex AB',
    party_a: 'wavult-group',
    party_b: 'landvex-ab',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Revolverande koncernlån upp till 500 000 SEK. Ränta 2,5% (STIBOR + marginal). Löptid 24 månader med möjlighet till förlängning. Dokumenterar arm\'s length-villkor för Skatteverket.',
    required: false,
    auto_proposed: true,
    amount: 500000,
    currency: 'SEK',
  },
  {
    id: 'ic-007',
    type: 'transfer_pricing_policy',
    title: 'Transfer Pricing Policy — Wavult Group koncernen',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Koncernövergripande policy för internprisättning enligt OECD Transfer Pricing Guidelines. Dokumenterar CUP-, cost-plus- och profit-split-metoderna per transaktionstyp. Obligatorisk för skattemässig försvarbarhet i Sverige, Litauen och USA.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'ic-008',
    type: 'trademark_license',
    title: 'Varumärkeslicensavtal — "Wavult" — Wavult Group → alla dotterbolag',
    party_a: 'wavult-group',
    party_b: 'wavult-operations',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Icke-exklusiv licens att använda varumärket "Wavult" i respektive jurisdiktion. Täcker logotyp, domännamn och produktnamn. Ingen royalty (ingår i Management Fee). Giltighet: obestämd med 6 månaders uppsägningstid.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'ic-009',
    type: 'trademark_license',
    title: 'Varumärkeslicensavtal — "quiXzoom" — Wavult Group → QuiXzoom Inc & UAB',
    party_a: 'wavult-group',
    party_b: 'quixzoom-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Licens för varumärket "quiXzoom" till QuiXzoom Inc (USA) och QuiXzoom UAB (EU). Täcker alla registrerade och orregistrerade rättigheter. Royaltyfri inom befintlig IP-licensstruktur.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'ic-010',
    type: 'trademark_license',
    title: 'Varumärkeslicensavtal — "Landvex" — Wavult Group → Landvex AB & Inc',
    party_a: 'wavult-group',
    party_b: 'landvex-ab',
    signing_level: 'L3',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Licens för varumärket "Landvex" till Landvex AB (Sverige) och Landvex Inc (USA). Ingår i övergripande IP-licensavtal. Separat varumärkesdokument för tydlighet vid revision.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'ic-011',
    type: 'data_processing_agreement',
    title: 'Koncernintern DPA — Wavult Group FZCO ↔ samtliga dotterbolag',
    party_a: 'wavult-group',
    party_b: 'quixzoom-uab',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Ramavtal för behandling av personuppgifter inom koncernen. Täcker dataflöden mellan Dubai (tredjeland), EU (LT, SE) och USA. Inkluderar standardavtalsklausuler (SCCs) per EU 2021/914. Obligatorisk under GDPR Art. 28.',
    required: true,
    auto_proposed: true,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 2: PERSONALAVTAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'hr-001',
    type: 'employment_contract',
    title: 'Anställningsavtal mall — Sverige (kollektivavtal-kompatibelt)',
    party_a: 'landvex-ab',
    party_b: 'employee-template-se',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Standardmall för anställningsavtal i Sverige. Kompatibel med Almega IT-avtalet. Inkluderar: arbetstid 40h/v, 6 månaders provanställning, 25 semesterdagar, konkurrensklausul (12 mån), sekretess, IP-överlåtelse.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'hr-002',
    type: 'contractor_agreement',
    title: 'Uppdragsavtal mall — Externa konsulter',
    party_a: 'landvex-ab',
    party_b: 'external-consultant',
    signing_level: 'L2',
    sign_method: 'email_otp',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Standardmall för uppdragsavtal med externa konsulter. Inkluderar: timpris/fast arvode, leveransspecifikation, sekretess, IP-överlåtelse (all kod ägs av bolaget), 30 dagars uppsägningstid, ansvarsbegränsning 3x fakturerat belopp.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'hr-003',
    type: 'nda',
    title: 'NDA Anställda — Sverige (Sekretessavtal)',
    party_a: 'landvex-ab',
    party_b: 'employee-se',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Sekretessavtal för anställda i Sverige. Gäller under anställning och 3 år efter. Täcker affärshemligheter, kundlistor, teknisk IP och finansiell information. Inget vite — skadestånd per avtal.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'hr-004',
    type: 'nda',
    title: 'NDA Anställda — USA (Delaware/Texas)',
    party_a: 'quixzoom-inc',
    party_b: 'employee-us',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Confidentiality Agreement för anställda i USA. Anpassad för Delaware och Texas lag. Inkluderar trade secrets per Defend Trade Secrets Act (DTSA). Gäller under anställning och 2 år efter. Arbitration clause inkluderad.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'hr-005',
    type: 'nda',
    title: 'NDA Anställda — Litauen (QuiXzoom UAB)',
    party_a: 'quixzoom-uab',
    party_b: 'employee-lt',
    signing_level: 'L2',
    sign_method: 'eid_eidas',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Konfidentialitetsavtal för anställda i Litauen. Anpassad till litauisk arbetsrätt (Labour Code 2016). Gäller under anställning och 2 år efter. Vite vid brott: 3 månaders lön.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'hr-006',
    type: 'non_compete',
    title: 'Konkurrensklausul — Sverige (Landvex AB)',
    party_a: 'landvex-ab',
    party_b: 'employee-se',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Konkurrensklausul per Bemanningsavtalet och Almega IT. Karenstid max 18 månader. Kompensation: 60% av lön under karenstiden. Geografisk begränsning: Norden. Branschbegränsning: crowdsourcad datainsamling och B2G SaaS.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'hr-007',
    type: 'non_compete',
    title: 'Non-Compete Agreement — USA (Delaware/Texas)',
    party_a: 'quixzoom-inc',
    party_b: 'employee-us',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Non-compete agreement anpassad till Delaware och Texas lag. OBS: California förbjuder non-competes — anpassas per stat. Giltighet 12 månader efter anställning. Begränsad till direkt konkurrenter inom crowdsourced imaging.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'hr-008',
    type: 'equity_plan',
    title: 'VSOP-plan — Wavult Group (Virtual Stock Option Program)',
    party_a: 'wavult-group',
    party_b: 'key-employees',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Virtual Stock Option Program (phantom equity) för nyckelpersoner i hela koncernen. Inga riktiga aktier — kontantbonus kopplad till bolagsvärdering vid exit eller likviditetsevent. 4-årig vesting, 1-årig cliff. Pool: 10% av hypotetisk värdering.',
    required: false,
    auto_proposed: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 3: ZOOMER-AVTAL (quiXzoom)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'zo-001',
    type: 'platform_agreement',
    title: 'Zoomer Platform Agreement — Villkor för att vara Zoomer',
    party_a: 'quixzoom-inc',
    party_b: 'zoomer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Ramavtal för fotografer (Zoomers) på quiXzoom-plattformen. Klassificering som oberoende uppdragstagare. Inkluderar: plattformsregler, kvalitetskrav, godkännandeprocess, konton och betalning, sanktioner vid regelbrott.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'zo-002',
    type: 'mission_terms',
    title: 'Mission Acceptance Terms — Villkor per uppdrag (Zoomer)',
    party_a: 'quixzoom-inc',
    party_b: 'zoomer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Specifika villkor som Zoomers accepterar per uppdrag (mission). Täcker: platsbeskrivning, leveranskrav, tidsram, ersättning per bild/mission, avvisningsrätt, kvalitetskontroll. Automatisk accept vid uppdragsstart i appen.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'zo-003',
    type: 'payout_terms',
    title: 'Payout Terms & Conditions — Zoomer-utbetalningar',
    party_a: 'quixzoom-inc',
    party_b: 'zoomer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Utbetalningsvillkor för Zoomers. Betalning via Stripe Connect eller lokal betallösning. Minsta utbetalning: $10. Utbetalningsfrekvens: veckovis. Skatteansvarsklausul: Zoomers ansvarar själva för deklaration. KYC-verifiering krävs.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'zo-004',
    type: 'ip_assignment',
    title: 'IP-överlåtelse — Bilder & Data (Zoomer → quiXzoom)',
    party_a: 'zoomer',
    party_b: 'quixzoom-inc',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Automatisk överlåtelse av upphovsrätt till alla bilder och metadata som laddas upp via plattformen. Zoomern behåller ej rättigheter. quiXzoom kan sublicensiera till kunder. Globalt, oåterkalleligt, royaltyfritt. Inkluderar träningsdata för AI-modeller.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'zo-005',
    type: 'data_processing_agreement',
    title: 'GDPR-biträdesavtal — quiXzoom ↔ Zoomers (Behandlar personuppgifter)',
    party_a: 'quixzoom-uab',
    party_b: 'zoomer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Biträdesavtal per GDPR Art. 28 för Zoomers som fotograferar på offentliga platser och kan fånga identifierbara personer. Täcker: ändamålsbegränsning, radering av personuppgifter, säkerhetsåtgärder. Obligatorisk för EU-Zoomers.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'zo-006',
    type: 'contractor_agreement',
    title: 'Zoomer Contractor Agreement — Egenföretagarklassificering',
    party_a: 'quixzoom-inc',
    party_b: 'zoomer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Avtal som säkerställer korrekt klassificering av Zoomers som oberoende uppdragstagare (ej anställda). Per jurisdiktion: USA (IRS Form W-9/W-8BEN), EU (lokala regler), SE (F-skatt). Kritiskt för att undvika felklassificering och retroaktiva arbetsgivaravgifter.',
    required: true,
    auto_proposed: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 4: KUNDAVTAL (B2B)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'cust-001',
    type: 'enterprise_agreement',
    title: 'Landvex Enterprise Agreement — SaaS-avtal för kommuner/myndigheter',
    party_a: 'landvex-ab',
    party_b: 'municipality-customer',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Master SaaS-avtal för offentlig sektor (kommuner, Trafikverket, länsstyrelser). Inkluderar: licensvillkor, drifttid-garantier, dataskydd, LOU-compliance (lagen om offentlig upphandling), handläggningstider och prissättningsmodell. Anpassat för ramavtal.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'cust-002',
    type: 'data_processing_agreement',
    title: 'DPA Landvex — Landvex AB ↔ Kund (Offentlig sektor)',
    party_a: 'landvex-ab',
    party_b: 'municipality-customer',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Personuppgiftsbiträdesavtal per GDPR Art. 28 för kommuner och myndigheter som använder Landvex. Täcker behandling av medborgares uppgifter, tekniska och organisatoriska säkerhetsåtgärder, rätt till granskning, underbiträden.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'cust-003',
    type: 'sla',
    title: 'SLA — Landvex Plattform (Service Level Agreement)',
    party_a: 'landvex-ab',
    party_b: 'municipality-customer',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'SLA för Landvex-plattformen. Garantier: 99.5% drifttid/månad, max 4h planerat underhåll/mån, svarstid < 500ms (P95). Incidentklassificering P1-P4. P1-respons: 15 min. Vite vid brott: 1% av månadsavgift per timme nertid (max 20%).',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'cust-004',
    type: 'pilot_agreement',
    title: 'Pilotavtal — Landvex Proof of Concept (PoC)',
    party_a: 'landvex-ab',
    party_b: 'pilot-customer',
    signing_level: 'L2',
    sign_method: 'bankid',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'PoC-avtal för 3-månaders pilot med kommuner/myndigheter. Reducerat pris eller gratis. Definierar: framgångskriterier, datahantering, övergång till fullständigt Enterprise Agreement, äganderätt till pilotdata. Ingen automatisk förlängning.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'cust-005',
    type: 'nda',
    title: 'NDA med kund — Landvex AB ↔ Prospektiv kund',
    party_a: 'landvex-ab',
    party_b: 'prospect-customer',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Ömsesidigt sekretessavtal med prospektiva kunder inför demo och offertprocess. Enkel klick-signatur räcker för detta stadium. Giltighet 12 månader. Täcker teknisk information, prissättning och affärsplaner.',
    required: false,
    auto_proposed: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 5: LEVERANTÖRSAVTAL
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'vend-001',
    type: 'vendor_contract',
    title: 'Cloud Vendor Agreement — AWS (Amazon Web Services)',
    party_a: 'wavult-operations',
    party_b: 'aws',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'signed',
    created_at: '2026-03-27',
    signed_at: '2026-03-27',
    description: 'Referensdokument för AWS Enterprise Agreement. Täcker: AWS Customer Agreement, BAA (Business Associate Agreement) om relevant, reserverade instanser och prisåtaganden. Intern dokumentation av åtaganden och kostnadsoptimering.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'vend-002',
    type: 'vendor_contract',
    title: 'Software License Agreement — Tredjepartslicenser',
    party_a: 'wavult-operations',
    party_b: 'software-vendor',
    signing_level: 'L2',
    sign_method: 'email_otp',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Ramavtal för tredjepartslicenser (SaaS-verktyg, bibliotek med kommersiell licens). Inventering av befintliga licenser. Compliance-check mot GPL/AGPL som kan orsaka copyleft-problem i proprietär kod.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'vend-003',
    type: 'subcontractor_agreement',
    title: 'Underleverantörsavtal — Teknisk partner/Subcontractor',
    party_a: 'wavult-operations',
    party_b: 'subcontractor',
    signing_level: 'L2',
    sign_method: 'email_otp',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Avtal med tekniska underleverantörer (t.ex. UX-byråer, backend-konsulter). Inkluderar: IP-överlåtelse (all kod tillfaller Wavult), sekretess, leveranskrav, betalningsplan, försäkringskrav. Flow-down av kundkrav där tillämpligt.',
    required: false,
    auto_proposed: false,
  },
  {
    id: 'vend-004',
    type: 'payment_processing',
    title: 'Payment Processing Agreement — Stripe/Revolut',
    party_a: 'quixzoom-inc',
    party_b: 'stripe',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'signed',
    created_at: '2026-03-27',
    signed_at: '2026-03-27',
    description: 'Intern dokumentation av Stripe Connected Accounts-villkor och Revolut Business-avtal. Täcker: transaktionsavgifter, utbetalningsschema, KYC-krav, reservhållning, tvisthantering och krav vid hög chargeback-frekvens.',
    required: true,
    auto_proposed: false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 6: BOLAGSSTRUKTUR & GOVERNANCE
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'gov-001',
    type: 'shareholder_agreement',
    title: 'Aktieägaravtal — Landvex AB',
    party_a: 'erik-svensson',
    party_b: 'wavult-group',
    signing_level: 'L3',
    sign_method: 'bankid',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Aktieägaravtal för Landvex AB. Reglerar: ägarstruktur, styrelsens sammansättning, beslutsgränser (vetorätt vid strategiska beslut), drag-along/tag-along, rätt till utdelning, hembudsklausul, lösenpris vid utträde.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'gov-002',
    type: 'shareholder_agreement',
    title: 'Shareholders Agreement — QuiXzoom UAB (Litauen)',
    party_a: 'wavult-group',
    party_b: 'quixzoom-uab',
    signing_level: 'L3',
    sign_method: 'eid_eidas',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Bolagsstyrningsavtal för det litauiska bolaget. Anpassat till litauisk bolagsrätt (Civil Code). Reglerar direktörsmandat, vinstdistribution, kapitaltillskott och exitvillkor.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'gov-003',
    type: 'board_resolution',
    title: 'Styrelsebeslutsmall — Löpande koncernbeslut',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Standardmall för styrelsebeslut (per capsulam och konstituerande). Täcker vanliga beslutstyper: teckna avtal, utse firmatecknare, kapitaltillskott, godkänna årsredovisning. Separata mallar per jurisdiktion.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'gov-004',
    type: 'articles_of_association',
    title: 'Bolagsordning — Landvex AB (Sverige)',
    party_a: 'landvex-ab',
    party_b: 'landvex-ab',
    signing_level: 'L3',
    sign_method: 'bankid',
    status: 'signed',
    created_at: '2026-03-27',
    signed_at: '2026-03-27',
    description: 'Bolagsordning för Landvex AB registrerad hos Bolagsverket. Täcker: firma, säte, verksamhet, aktiekapital, antal aktier, styrelse och revisor. Uppdateras vid namnbyte och kapitalförändringar.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'gov-005',
    type: 'articles_of_association',
    title: 'Certificate of Incorporation / Bylaws — QuiXzoom Inc (Delaware)',
    party_a: 'quixzoom-inc',
    party_b: 'quixzoom-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Delaware C-Corp Certificate of Incorporation och Bylaws. Täcker: authorized shares (10M common + 5M preferred), board composition, stockholder voting rights, officer roles. Klar via Stripe Atlas-processen.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'gov-006',
    type: 'articles_of_association',
    title: 'Steigungsurkunde / Articles — QuiXzoom UAB (Litauen)',
    party_a: 'quixzoom-uab',
    party_b: 'quixzoom-uab',
    signing_level: 'L3',
    sign_method: 'eid_eidas',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Litauisk UAB:s bolagsordning (Steigimo sutartis). Registreras hos Juridinių asmenų registras. Minsta kapital: 2 500 EUR. Kräver notariatverifiering vid bildandet. Framtas av Weedle UAB.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'gov-007',
    type: 'articles_of_association',
    title: 'Memorandum & Articles of Association — Wavult Group FZCO (Dubai DMCC)',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'DMCC Free Zone Company (FZCO) Memorandum och Articles of Association. Registreras hos DMCC. Minsta kapital: AED 50 000. Täcker: verksamhetsbeskrivning (IP holding, software development), aktiestruktur och direktörsmandat.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'gov-008',
    type: 'convertible_loan',
    title: 'Konvertibellånsavtal — Extern investerare → QuiXzoom Inc',
    party_a: 'external-investor',
    party_b: 'quixzoom-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Konvertibellån som konverterar till eget kapital vid nästa kvalificerade finansieringsrunda (min. $1M). Ränta 6% p.a. Löptid 18 månader. 20% konverteringsrabatt. Valuation cap: $5M. Anpassad till Delaware-rätt.',
    required: false,
    auto_proposed: false,
    amount: 250000,
    currency: 'USD',
  },
  {
    id: 'gov-009',
    type: 'safe_agreement',
    title: 'SAFE Agreement — YC Standard (Simple Agreement for Future Equity)',
    party_a: 'external-investor',
    party_b: 'quixzoom-inc',
    signing_level: 'L3',
    sign_method: 'docusign',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Y Combinator Post-Money SAFE. Valuation cap: $5M post-money. No discount. Pro-rata rights inkluderat. Most Favored Nation (MFN) klausul. Automatisk konvertering vid Equity Financing, Liquidity Event eller Dissolution. Standarddokument - minimal förhandling.',
    required: false,
    auto_proposed: false,
    amount: 100000,
    currency: 'USD',
  },

  // ══════════════════════════════════════════════════════════════════════════
  // NYA DOKUMENT — KAT. 7: COMPLIANCE & REGULATORISKT
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'comp-001',
    type: 'gdpr_compliance_framework',
    title: 'GDPR Compliance Framework — Wavult-koncernen',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Övergripande GDPR-ramverk för hela koncernen. Dokumenterar: personuppgiftsansvarig per bolag, behandlingsregister (RoPA), dataflödeskartor, rättslig grund per behandling, DPIA-process, incidenthantering, DPO-roll (om tillämpligt). Obligatorisk under GDPR Art. 30.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'comp-002',
    type: 'privacy_policy',
    title: 'Privacy Policy — quiXzoom (Extern, användarvänlig)',
    party_a: 'quixzoom-inc',
    party_b: 'end-users',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Extern, användarvänlig integritetspolicy för quiXzoom-plattformen. Täcker: insamlade uppgifter, ändamål, lagringstid, tredjepartdelning, användarrättigheter (rätt till access, rättelse, radering), kontaktinformation. GDPR + CCPA-kompatibel.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'comp-003',
    type: 'privacy_policy',
    title: 'Privacy Policy — Landvex (Extern, B2G)',
    party_a: 'landvex-ab',
    party_b: 'end-users',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Integritetspolicy för Landvex-plattformen anpassad för offentlig sektor (B2G). Betonar: ingen kommersiell datadelning, svenska dataskyddskrav, Integritetsskyddsmyndighetens (IMY) riktlinjer, myndighetsspecifika rättigheter.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'comp-004',
    type: 'cookie_policy',
    title: 'Cookie Policy — quiXzoom & Landvex',
    party_a: 'quixzoom-inc',
    party_b: 'end-users',
    signing_level: 'L1',
    sign_method: 'click',
    status: 'draft',
    created_at: '2026-03-27',
    description: 'Cookie-policy per ePrivacy-direktivet och GDPR. Kategoriserar cookies: nödvändiga, funktionella, analytiska, marknadsföring. Implementerar samtyckehantering (Cookiebot/OneTrust-kompatibel). Separata policyer per domän och plattform.',
    required: true,
    auto_proposed: false,
  },
  {
    id: 'comp-005',
    type: 'aml_policy',
    title: 'Anti-Money Laundering (AML) Policy — Wavult Group',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'AML-policy för koncernen. Krav: identifiering av verklig huvudman (UBO), riskbaserad kundkännedom (KYC), transaktionsövervakning, rapportering till FIU (Finanspolisen/FinCEN). Kritisk för DMCC-licens och bankrelationer.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'comp-006',
    type: 'kyc_procedures',
    title: 'KYC-rutiner — Zoomer- och Kundverifiering',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Know Your Customer-procedurer för Zoomers (fotografer) och B2B-kunder. Täcker: identitetsverifiering (passfoton/ID), adressverifiering, PEP-screening, sanktionskontroll (OFAC, EU-sanktioner). Integreras med Stripe Identity eller Onfido.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'comp-007',
    type: 'whistleblower_policy',
    title: 'Visselblåsarpolicy — Wavult Group (EU-direktiv 2019/1937)',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Visselblåsarpolicy per EU-direktiv 2019/1937 (implementerat i Sverige via lagen om skydd för visselblåsare 2021:890). Obligatorisk för bolag med fler än 50 anställda. Täcker: rapporteringskanal, anonymitetsskydd, utredningsprocess, skydd mot repressalier.',
    required: true,
    auto_proposed: true,
  },
  {
    id: 'comp-008',
    type: 'information_security_policy',
    title: 'Informationssäkerhetspolicy — ISO 27001-inspirerad',
    party_a: 'wavult-group',
    party_b: 'wavult-group',
    signing_level: 'L2',
    sign_method: 'docusign',
    status: 'proposed',
    created_at: '2026-03-27',
    description: 'Informationssäkerhetspolicy för hela koncernen. Baserad på ISO 27001-ramverket. Täcker: klassificering av information, åtkomstkontroll, krypteringskrav, incidenthantering, backup-policy, leverantörssäkerhet, säkerhetstestning. Krävs av offentliga kunder (Trafikverket, kommuner).',
    required: true,
    auto_proposed: true,
  },
]
