-- ============================================================================
-- Hypbit OMS — Supplier Management
-- File: 22_supplier_management.sql
-- Run: AFTER 19_erp_integration.sql in Supabase (PostgreSQL)
--
-- Complete supplier management schema per ISO 9001:2015 clause 8.4
-- (Control of externally provided processes, products and services).
-- Covers supplier qualification, approved supplier list, periodic evaluation,
-- supplier audit results, and NC linkage.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. ENUM TYPES
-- ============================================================================

DO $$ BEGIN
  CREATE TYPE supplier_status AS ENUM (
    'PROSPECT',
    'UNDER_EVALUATION',
    'CONDITIONALLY_APPROVED',
    'APPROVED',
    'ON_WATCH',
    'SUSPENDED',
    'BLOCKED',
    'DEACTIVATED'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE supplier_category AS ENUM (
    'PRODUCT',
    'SERVICE',
    'SUBCONTRACTOR',
    'CONSULTANT',
    'IT_VENDOR',
    'LOGISTICS',
    'FACILITY',
    'RAW_MATERIAL',
    'CRITICAL_COMPONENT',
    'OTHER'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE supplier_criticality AS ENUM (
    'CRITICAL',
    'HIGH',
    'MEDIUM',
    'LOW'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE qualification_method AS ENUM (
    'AUDIT',
    'QUESTIONNAIRE',
    'SAMPLE_TEST',
    'REFERENCE_CHECK',
    'CERTIFICATION_VERIFIED',
    'TRIAL_PERIOD',
    'COMBINATION'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE evaluation_type AS ENUM (
    'INITIAL_QUALIFICATION',
    'PERIODIC',
    'AFTER_NC',
    'AFTER_COMPLAINT',
    'REAPPROVAL',
    'SPECIAL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE overall_rating AS ENUM (
    'A',
    'B',
    'C',
    'D',
    'F'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE evaluation_decision AS ENUM (
    'MAINTAIN_APPROVED',
    'CONDITIONALLY_APPROVED',
    'PLACE_ON_WATCH',
    'SUSPEND',
    'BLOCK',
    'REQUALIFY'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE supplier_audit_type AS ENUM (
    'ON_SITE',
    'REMOTE',
    'DOCUMENT_REVIEW',
    'PRODUCT_AUDIT',
    'PROCESS_AUDIT'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE audit_result AS ENUM (
    'PASS',
    'CONDITIONAL_PASS',
    'FAIL'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================================
-- 2. SEQUENCE
-- ============================================================================

CREATE SEQUENCE IF NOT EXISTS supplier_number_seq START 1;

-- ============================================================================
-- 3. TABLES
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 3.1 suppliers — Approved Supplier List master record per ISO 8.4.1
-- Tracks full supplier lifecycle from prospect through approval, periodic
-- re-evaluation, and deactivation.  Performance KPIs are maintained in-place
-- and updated by triggers when evaluations or NCs are recorded.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
  id                            UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                        UUID            REFERENCES organizations(id),
  company_id                    UUID            NOT NULL REFERENCES companies(id),

  -- Identity
  supplier_code                 TEXT            NOT NULL, -- auto-generated by trigger
  status                        supplier_status DEFAULT 'PROSPECT',
  category                      supplier_category NOT NULL,
  criticality                   supplier_criticality NOT NULL DEFAULT 'MEDIUM',

  -- Approval
  approved_at                   TIMESTAMPTZ,
  approved_by                   UUID            REFERENCES profiles(id),
  approval_valid_until          DATE,
  approval_conditions           TEXT,
  reapproval_interval_months    INTEGER         DEFAULT 12,
  next_reapproval_date          DATE,

  -- Qualification
  qualification_date            DATE,
  qualification_method          qualification_method,
  qualification_score           NUMERIC(5,2),
  qualification_notes           TEXT,
  qualification_document_id     UUID            REFERENCES documents(id),

  -- Certifications & compliance
  certifications                JSONB           DEFAULT '[]',

  -- Commercial
  contract_start                DATE,
  contract_end                  DATE,
  contract_value_annual         NUMERIC(12,2),
  contract_currency             TEXT            DEFAULT 'EUR',
  payment_terms                 TEXT,
  lead_time_days                INTEGER,
  minimum_order                 TEXT,

  -- Performance KPIs (maintained by triggers / periodic jobs)
  current_rating                NUMERIC(3,2)    DEFAULT 0 CHECK (current_rating >= 0 AND current_rating <= 5),
  delivery_performance_pct      NUMERIC(5,2)    DEFAULT 0,
  quality_performance_pct       NUMERIC(5,2)    DEFAULT 0,
  total_nc_count                INTEGER         DEFAULT 0,
  total_complaints_from_supplier INTEGER        DEFAULT 0,
  total_spend_eur               NUMERIC(12,2)   DEFAULT 0,

  -- Risk
  risk_level                    supplier_criticality,
  risk_notes                    TEXT,
  alternative_supplier_ids      UUID[]          DEFAULT '{}',
  single_source                 BOOLEAN         DEFAULT false,

  -- Contacts & ownership
  responsible_id                UUID            REFERENCES profiles(id),
  quality_contact               TEXT,
  quality_contact_email         TEXT,
  commercial_contact            TEXT,

  -- Meta
  metadata                      JSONB           DEFAULT '{}',
  created_at                    TIMESTAMPTZ     DEFAULT now(),
  updated_at                    TIMESTAMPTZ     DEFAULT now(),
  created_by                    UUID            REFERENCES profiles(id),

  UNIQUE(org_id, supplier_code)
);

-- ----------------------------------------------------------------------------
-- 3.2 supplier_evaluations — Periodic and event-driven supplier evaluations
-- Per ISO 8.4.1: organisations must evaluate and re-evaluate external providers.
-- Weighted scoring across six criteria produces a computed overall_rating.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_evaluations (
  id                        UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                    UUID            REFERENCES organizations(id),
  supplier_id               UUID            NOT NULL REFERENCES suppliers(id),

  -- Evaluation header
  evaluation_type           evaluation_type NOT NULL,
  evaluation_date           DATE            NOT NULL,
  evaluator_id              UUID            NOT NULL REFERENCES profiles(id),
  period_from               DATE,
  period_to                 DATE,

  -- Scored criteria (1–5 scale)
  quality_score             INTEGER         CHECK (quality_score BETWEEN 1 AND 5),
  quality_weight            NUMERIC(3,2)    DEFAULT 0.30,

  delivery_score            INTEGER         CHECK (delivery_score BETWEEN 1 AND 5),
  delivery_weight           NUMERIC(3,2)    DEFAULT 0.25,

  responsiveness_score      INTEGER         CHECK (responsiveness_score BETWEEN 1 AND 5),
  responsiveness_weight     NUMERIC(3,2)    DEFAULT 0.15,

  compliance_score          INTEGER         CHECK (compliance_score BETWEEN 1 AND 5),
  compliance_weight         NUMERIC(3,2)    DEFAULT 0.15,

  price_score               INTEGER         CHECK (price_score BETWEEN 1 AND 5),
  price_weight              NUMERIC(3,2)    DEFAULT 0.10,

  innovation_score          INTEGER         CHECK (innovation_score BETWEEN 1 AND 5),
  innovation_weight         NUMERIC(3,2)    DEFAULT 0.05,

  -- Extensible custom criteria (array of {name, score, weight})
  custom_criteria           JSONB           DEFAULT '[]',

  -- Computed columns
  weighted_score            NUMERIC(5,2)    GENERATED ALWAYS AS (
    COALESCE(quality_score       * quality_weight,       0) +
    COALESCE(delivery_score      * delivery_weight,      0) +
    COALESCE(responsiveness_score * responsiveness_weight, 0) +
    COALESCE(compliance_score    * compliance_weight,    0) +
    COALESCE(price_score         * price_weight,         0) +
    COALESCE(innovation_score    * innovation_weight,    0)
  ) STORED,

  overall_rating            overall_rating  GENERATED ALWAYS AS (
    CASE
      WHEN (
        COALESCE(quality_score       * quality_weight,       0) +
        COALESCE(delivery_score      * delivery_weight,      0) +
        COALESCE(responsiveness_score * responsiveness_weight, 0) +
        COALESCE(compliance_score    * compliance_weight,    0) +
        COALESCE(price_score         * price_weight,         0) +
        COALESCE(innovation_score    * innovation_weight,    0)
      ) >= 4.5 THEN 'A'::overall_rating
      WHEN (
        COALESCE(quality_score       * quality_weight,       0) +
        COALESCE(delivery_score      * delivery_weight,      0) +
        COALESCE(responsiveness_score * responsiveness_weight, 0) +
        COALESCE(compliance_score    * compliance_weight,    0) +
        COALESCE(price_score         * price_weight,         0) +
        COALESCE(innovation_score    * innovation_weight,    0)
      ) >= 3.5 THEN 'B'::overall_rating
      WHEN (
        COALESCE(quality_score       * quality_weight,       0) +
        COALESCE(delivery_score      * delivery_weight,      0) +
        COALESCE(responsiveness_score * responsiveness_weight, 0) +
        COALESCE(compliance_score    * compliance_weight,    0) +
        COALESCE(price_score         * price_weight,         0) +
        COALESCE(innovation_score    * innovation_weight,    0)
      ) >= 2.5 THEN 'C'::overall_rating
      WHEN (
        COALESCE(quality_score       * quality_weight,       0) +
        COALESCE(delivery_score      * delivery_weight,      0) +
        COALESCE(responsiveness_score * responsiveness_weight, 0) +
        COALESCE(compliance_score    * compliance_weight,    0) +
        COALESCE(price_score         * price_weight,         0) +
        COALESCE(innovation_score    * innovation_weight,    0)
      ) >= 1.5 THEN 'D'::overall_rating
      ELSE 'F'::overall_rating
    END
  ) STORED,

  -- Objective performance data for the evaluation period
  nc_count_period           INTEGER         DEFAULT 0,
  complaint_count_period    INTEGER         DEFAULT 0,
  deliveries_total          INTEGER         DEFAULT 0,
  deliveries_on_time        INTEGER         DEFAULT 0,
  returns_count             INTEGER         DEFAULT 0,

  -- Decision & follow-up
  decision                  evaluation_decision,
  decision_rationale        TEXT,
  action_required           TEXT,
  follow_up_date            DATE,

  -- Linkages
  linked_nc_ids             UUID[]          DEFAULT '{}',
  linked_audit_id           UUID            REFERENCES audits(id),
  linked_improvement_id     UUID            REFERENCES improvements(id),
  notes                     TEXT,

  created_at                TIMESTAMPTZ     DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 3.3 supplier_audit_results — Records from supplier audits per ISO 8.4.2
-- Links to the main audits table for scheduling while capturing supplier-
-- specific findings, result, and corrective action deadlines.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_audit_results (
  id                        UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                    UUID            REFERENCES organizations(id),
  supplier_id               UUID            REFERENCES suppliers(id),
  audit_id                  UUID            REFERENCES audits(id),

  -- Audit details
  audit_date                DATE            NOT NULL,
  audit_type                supplier_audit_type NOT NULL,
  auditor_id                UUID            REFERENCES profiles(id),
  external_auditor          TEXT,
  scope                     TEXT,

  -- Findings summary
  findings_count            INTEGER         DEFAULT 0,
  major_findings            INTEGER         DEFAULT 0,
  minor_findings            INTEGER         DEFAULT 0,
  observations              INTEGER         DEFAULT 0,
  findings                  JSONB           DEFAULT '[]',  -- [{id, type, description, clause, status}]

  -- Result
  overall_result            audit_result,
  conditions                TEXT,
  corrective_action_deadline DATE,
  follow_up_audit_date      DATE,
  linked_nc_ids             UUID[]          DEFAULT '{}',
  report_document_id        UUID            REFERENCES documents(id),
  next_audit_date           DATE,
  notes                     TEXT,

  created_at                TIMESTAMPTZ     DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 3.4 supplier_nc_register — Links non-conformances to their supplier source
-- Per ISO 8.4.3: organisations must communicate requirements to external
-- providers and manage non-conforming externally provided outputs.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS supplier_nc_register (
  id                            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                        UUID        REFERENCES organizations(id),
  supplier_id                   UUID        NOT NULL REFERENCES suppliers(id),
  nc_id                         UUID        NOT NULL REFERENCES non_conformances(id),

  -- Impact
  impact_description            TEXT,

  -- Supplier communication
  supplier_notified_at          TIMESTAMPTZ,
  supplier_response             TEXT,
  supplier_responded_at         TIMESTAMPTZ,

  -- Corrective action
  corrective_action_required    BOOLEAN     DEFAULT false,
  corrective_action_received    BOOLEAN     DEFAULT false,
  corrective_action_accepted    BOOLEAN,

  -- Financial recovery
  credit_claimed                BOOLEAN     DEFAULT false,
  credit_amount                 NUMERIC(10,2),
  credit_received               BOOLEAN     DEFAULT false,

  created_at                    TIMESTAMPTZ DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- 3.5 approved_supplier_list — Point-in-time snapshots of the ASL
-- Per ISO 8.4.1: a controlled list of approved external providers must be
-- maintained.  Each row is an immutable snapshot; only one row is is_current.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS approved_supplier_list (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID        REFERENCES organizations(id),
  generated_at    TIMESTAMPTZ DEFAULT now(),
  generated_by    UUID        REFERENCES profiles(id),
  valid_from      DATE        NOT NULL,
  valid_until     DATE,
  suppliers       JSONB       NOT NULL,   -- snapshot array of approved supplier data
  document_id     UUID        REFERENCES documents(id),
  is_current      BOOLEAN     DEFAULT true
);

-- ============================================================================
-- 4. TRIGGERS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 4.1 Auto-generate supplier_code on INSERT
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_set_supplier_code()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.supplier_code IS NULL OR NEW.supplier_code = '' THEN
    NEW.supplier_code := 'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0');
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_supplier_code ON suppliers;
CREATE TRIGGER set_supplier_code
  BEFORE INSERT ON suppliers
  FOR EACH ROW EXECUTE FUNCTION trg_set_supplier_code();

-- ----------------------------------------------------------------------------
-- 4.2 updated_at maintenance for suppliers
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_suppliers_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS suppliers_updated_at ON suppliers;
CREATE TRIGGER suppliers_updated_at
  BEFORE UPDATE ON suppliers
  FOR EACH ROW EXECUTE FUNCTION trg_suppliers_updated_at();

-- ----------------------------------------------------------------------------
-- 4.3 Supplier NC counter + auto-watch escalation
-- When a new supplier_nc_register row is inserted:
--   a) increment suppliers.total_nc_count
--   b) if the supplier has >= 3 NCs in the last 90 days AND status = 'APPROVED'
--      automatically escalate status to 'ON_WATCH'
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_supplier_nc_inserted()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_recent_nc_count INTEGER;
  v_current_status  supplier_status;
BEGIN
  -- a) Increment total NC counter
  UPDATE suppliers
  SET total_nc_count = total_nc_count + 1,
      updated_at     = now()
  WHERE id = NEW.supplier_id;

  -- b) Check recent NC frequency and escalate if threshold exceeded
  SELECT COUNT(*)
  INTO   v_recent_nc_count
  FROM   supplier_nc_register
  WHERE  supplier_id = NEW.supplier_id
    AND  created_at  >= now() - INTERVAL '90 days';

  SELECT status
  INTO   v_current_status
  FROM   suppliers
  WHERE  id = NEW.supplier_id;

  IF v_recent_nc_count >= 3 AND v_current_status = 'APPROVED' THEN
    UPDATE suppliers
    SET    status     = 'ON_WATCH',
           updated_at = now()
    WHERE  id = NEW.supplier_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS supplier_nc_inserted ON supplier_nc_register;
CREATE TRIGGER supplier_nc_inserted
  AFTER INSERT ON supplier_nc_register
  FOR EACH ROW EXECUTE FUNCTION trg_supplier_nc_inserted();

-- ============================================================================
-- 5. VIEWS
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 5.1 v_supplier_performance — per-supplier performance dashboard
-- Joins suppliers + companies and lateral-fetches the most recent evaluation
-- to expose live KPIs alongside reapproval status.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_supplier_performance AS
SELECT
  s.id                        AS supplier_id,
  s.org_id,
  s.supplier_code,
  c.name                      AS supplier_name,
  s.status,
  s.category,
  s.criticality,
  s.current_rating,
  s.delivery_performance_pct,
  s.quality_performance_pct,
  s.total_nc_count,
  s.single_source,
  s.next_reapproval_date,
  CASE
    WHEN s.next_reapproval_date IS NULL            THEN 'OK'
    WHEN s.next_reapproval_date < CURRENT_DATE     THEN 'OVERDUE'
    WHEN s.next_reapproval_date <= CURRENT_DATE + 30 THEN 'DUE_SOON'
    ELSE 'OK'
  END                         AS reapproval_status,
  latest_eval.weighted_score  AS latest_score,
  latest_eval.overall_rating  AS latest_rating,
  latest_eval.evaluation_date AS latest_evaluation_date,
  latest_eval.decision        AS latest_decision
FROM suppliers s
JOIN companies c ON c.id = s.company_id
LEFT JOIN LATERAL (
  SELECT
    se.weighted_score,
    se.overall_rating,
    se.evaluation_date,
    se.decision
  FROM supplier_evaluations se
  WHERE se.supplier_id = s.id
  ORDER BY se.evaluation_date DESC, se.created_at DESC
  LIMIT 1
) latest_eval ON true;

-- ----------------------------------------------------------------------------
-- 5.2 v_supplier_risk — org-level risk aggregation
-- Provides a single-row summary per org_id for management dashboards and
-- ISO 8.4 risk monitoring reports.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW v_supplier_risk AS
SELECT
  s.org_id,
  COUNT(*)                                                          AS total_suppliers,
  COUNT(*) FILTER (WHERE s.status = 'APPROVED')                    AS approved,
  COUNT(*) FILTER (WHERE s.status = 'ON_WATCH')                    AS on_watch,
  COUNT(*) FILTER (WHERE s.status = 'SUSPENDED')                   AS suspended,
  COUNT(*) FILTER (
    WHERE s.single_source = true
      AND s.criticality IN ('CRITICAL', 'HIGH')
  )                                                                 AS single_source_critical,
  COUNT(*) FILTER (
    WHERE s.next_reapproval_date IS NOT NULL
      AND s.next_reapproval_date < CURRENT_DATE
      AND s.status NOT IN ('DEACTIVATED', 'BLOCKED')
  )                                                                 AS reapproval_overdue,
  COUNT(*) FILTER (WHERE s.current_rating < 2.5)                   AS underperforming,
  ROUND(AVG(s.current_rating)::NUMERIC, 2)                         AS avg_rating
FROM suppliers s
GROUP BY s.org_id;

-- ============================================================================
-- 6. INDEXES
-- ============================================================================

-- suppliers
CREATE INDEX IF NOT EXISTS idx_suppliers_org_id
  ON suppliers(org_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_company_id
  ON suppliers(company_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_status
  ON suppliers(status);
CREATE INDEX IF NOT EXISTS idx_suppliers_criticality
  ON suppliers(criticality);
CREATE INDEX IF NOT EXISTS idx_suppliers_next_reapproval_date
  ON suppliers(next_reapproval_date);
CREATE INDEX IF NOT EXISTS idx_suppliers_responsible_id
  ON suppliers(responsible_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_approved_by
  ON suppliers(approved_by);
CREATE INDEX IF NOT EXISTS idx_suppliers_created_by
  ON suppliers(created_by);
CREATE INDEX IF NOT EXISTS idx_suppliers_qualification_document_id
  ON suppliers(qualification_document_id);

-- supplier_evaluations
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_org_id
  ON supplier_evaluations(org_id);
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_supplier_id
  ON supplier_evaluations(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_evaluator_id
  ON supplier_evaluations(evaluator_id);
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_linked_audit_id
  ON supplier_evaluations(linked_audit_id);
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_linked_improvement_id
  ON supplier_evaluations(linked_improvement_id);
CREATE INDEX IF NOT EXISTS idx_supplier_evaluations_evaluation_date
  ON supplier_evaluations(evaluation_date DESC);

-- supplier_audit_results
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_org_id
  ON supplier_audit_results(org_id);
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_supplier_id
  ON supplier_audit_results(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_audit_id
  ON supplier_audit_results(audit_id);
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_auditor_id
  ON supplier_audit_results(auditor_id);
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_report_document_id
  ON supplier_audit_results(report_document_id);
CREATE INDEX IF NOT EXISTS idx_supplier_audit_results_audit_date
  ON supplier_audit_results(audit_date DESC);

-- supplier_nc_register
CREATE INDEX IF NOT EXISTS idx_supplier_nc_register_org_id
  ON supplier_nc_register(org_id);
CREATE INDEX IF NOT EXISTS idx_supplier_nc_register_supplier_id
  ON supplier_nc_register(supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_nc_register_nc_id
  ON supplier_nc_register(nc_id);
CREATE INDEX IF NOT EXISTS idx_supplier_nc_register_created_at
  ON supplier_nc_register(created_at DESC);

-- approved_supplier_list
CREATE INDEX IF NOT EXISTS idx_approved_supplier_list_org_id
  ON approved_supplier_list(org_id);
CREATE INDEX IF NOT EXISTS idx_approved_supplier_list_generated_by
  ON approved_supplier_list(generated_by);
CREATE INDEX IF NOT EXISTS idx_approved_supplier_list_document_id
  ON approved_supplier_list(document_id);
CREATE INDEX IF NOT EXISTS idx_approved_supplier_list_is_current
  ON approved_supplier_list(is_current) WHERE is_current = true;

-- ============================================================================
-- 7. ROW-LEVEL SECURITY
-- ============================================================================

ALTER TABLE suppliers                ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_evaluations     ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_audit_results   ENABLE ROW LEVEL SECURITY;
ALTER TABLE supplier_nc_register     ENABLE ROW LEVEL SECURITY;
ALTER TABLE approved_supplier_list   ENABLE ROW LEVEL SECURITY;

-- suppliers
DROP POLICY IF EXISTS rls_suppliers_org ON suppliers;
CREATE POLICY rls_suppliers_org ON suppliers
  USING (org_id = (current_setting('app.current_org_id', true))::UUID);

-- supplier_evaluations
DROP POLICY IF EXISTS rls_supplier_evaluations_org ON supplier_evaluations;
CREATE POLICY rls_supplier_evaluations_org ON supplier_evaluations
  USING (org_id = (current_setting('app.current_org_id', true))::UUID);

-- supplier_audit_results
DROP POLICY IF EXISTS rls_supplier_audit_results_org ON supplier_audit_results;
CREATE POLICY rls_supplier_audit_results_org ON supplier_audit_results
  USING (org_id = (current_setting('app.current_org_id', true))::UUID);

-- supplier_nc_register
DROP POLICY IF EXISTS rls_supplier_nc_register_org ON supplier_nc_register;
CREATE POLICY rls_supplier_nc_register_org ON supplier_nc_register
  USING (org_id = (current_setting('app.current_org_id', true))::UUID);

-- approved_supplier_list
DROP POLICY IF EXISTS rls_approved_supplier_list_org ON approved_supplier_list;
CREATE POLICY rls_approved_supplier_list_org ON approved_supplier_list
  USING (org_id = (current_setting('app.current_org_id', true))::UUID);

-- ============================================================================
-- 8. SEED DATA — Wavult Groups tech supplier portfolio
-- ============================================================================

DO $$
DECLARE
  v_org_id          UUID;
  v_system_user_id  UUID;

  -- company IDs
  v_company_supabase   UUID;
  v_company_aws        UUID;
  v_company_stripe     UUID;
  v_company_vercel     UUID;
  v_company_github     UUID;
  v_company_anthropic  UUID;
  v_company_revolut    UUID;
  v_company_triggerdev UUID;
  v_company_expo       UUID;

BEGIN
  -- Resolve Wavult Groups org and a system user (first admin found, or NULL)
  SELECT id INTO v_org_id
  FROM organizations
  WHERE name ILIKE '%wavult%'
  LIMIT 1;

  SELECT id INTO v_system_user_id
  FROM profiles
  WHERE org_id = v_org_id
  ORDER BY created_at
  LIMIT 1;

  -- -------------------------------------------------------------------------
  -- 8.1 Companies — insert once, ignore conflicts on name
  -- -------------------------------------------------------------------------

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Supabase, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_supabase FROM companies
  WHERE name = 'Supabase, Inc.' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Amazon Web Services, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_aws FROM companies
  WHERE name = 'Amazon Web Services, Inc.' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Stripe, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_stripe FROM companies
  WHERE name = 'Stripe, Inc.' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Vercel, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_vercel FROM companies
  WHERE name = 'Vercel, Inc.' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'GitHub, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_github FROM companies
  WHERE name = 'GitHub, Inc.' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Anthropic, PBC', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_anthropic FROM companies
  WHERE name = 'Anthropic, PBC' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Revolut Ltd', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_revolut FROM companies
  WHERE name = 'Revolut Ltd' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Trigger.dev Ltd', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_triggerdev FROM companies
  WHERE name = 'Trigger.dev Ltd' AND org_id = v_org_id LIMIT 1;

  INSERT INTO companies (id, name, org_id, created_at)
  VALUES (gen_random_uuid(), 'Expo, Inc.', v_org_id, now())
  ON CONFLICT DO NOTHING;
  SELECT id INTO v_company_expo FROM companies
  WHERE name = 'Expo, Inc.' AND org_id = v_org_id LIMIT 1;

  -- -------------------------------------------------------------------------
  -- 8.2 Suppliers
  -- -------------------------------------------------------------------------

  -- Supabase — IT_VENDOR, HIGH, APPROVED, rating 5.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_supabase,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'HIGH',
    now() - INTERVAL '6 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '6 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '6 months')::DATE,
    (CURRENT_DATE - INTERVAL '6 months')::DATE, 'CERTIFICATION_VERIFIED',
    95.00, 'Open-source PostgreSQL BaaS — SOC 2 Type II certified, ISO 27001 compliant.',
    5.00, 99.90, 100.00, false,
    v_system_user_id, 'support@supabase.io', 'EUR',
    '[{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"},{"name":"ISO27001","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://supabase.com","tier":"Growth"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- AWS — IT_VENDOR, CRITICAL, APPROVED, rating 5.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_aws,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'CRITICAL',
    now() - INTERVAL '12 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '12 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '12 months')::DATE,
    (CURRENT_DATE - INTERVAL '12 months')::DATE, 'CERTIFICATION_VERIFIED',
    99.00, 'Global cloud infrastructure provider — multiple ISO, SOC and FedRAMP certifications. Primary cloud platform.',
    5.00, 99.95, 100.00, false,
    v_system_user_id, 'aws-compliance@amazon.com', 'EUR',
    '[{"name":"ISO27001","issued":"2024-01-01","expires":"2025-01-01"},{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"},{"name":"ISO9001","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://aws.amazon.com","regions":["eu-west-1","eu-central-1"]}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Stripe — IT_VENDOR, CRITICAL, APPROVED, rating 5.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_stripe,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'CRITICAL',
    now() - INTERVAL '10 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '14 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '14 months')::DATE,
    (CURRENT_DATE - INTERVAL '10 months')::DATE, 'CERTIFICATION_VERIFIED',
    98.00, 'Payment processing platform — PCI DSS Level 1, SOC 2 Type II. Primary payment provider.',
    5.00, 99.99, 100.00, false,
    v_system_user_id, 'security@stripe.com', 'EUR',
    '[{"name":"PCI-DSS-L1","issued":"2024-01-01","expires":"2025-01-01"},{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://stripe.com","account":"wavult"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Vercel — IT_VENDOR, HIGH, APPROVED, rating 4.5
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_vercel,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'HIGH',
    now() - INTERVAL '8 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '4 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '4 months')::DATE,
    (CURRENT_DATE - INTERVAL '8 months')::DATE, 'CERTIFICATION_VERIFIED',
    90.00, 'Frontend deployment and edge network platform — SOC 2 Type II. Hosts web frontends.',
    4.50, 99.80, 99.00, false,
    v_system_user_id, 'security@vercel.com', 'EUR',
    '[{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://vercel.com","plan":"Enterprise"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- GitHub — IT_VENDOR, HIGH, APPROVED, rating 5.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_github,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'HIGH',
    now() - INTERVAL '18 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '6 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '6 months')::DATE,
    (CURRENT_DATE - INTERVAL '18 months')::DATE, 'CERTIFICATION_VERIFIED',
    97.00, 'Source code management and CI/CD platform — SOC 2 Type II, ISO 27001. Primary VCS.',
    5.00, 99.95, 100.00, false,
    v_system_user_id, 'security@github.com', 'EUR',
    '[{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"},{"name":"ISO27001","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://github.com","plan":"Enterprise"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Anthropic — IT_VENDOR, HIGH, APPROVED, rating 5.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_anthropic,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'HIGH',
    now() - INTERVAL '4 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '8 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '8 months')::DATE,
    (CURRENT_DATE - INTERVAL '4 months')::DATE, 'CERTIFICATION_VERIFIED',
    96.00, 'AI safety company — Claude API provider. SOC 2 Type II. Powers AI-assisted QMS features.',
    5.00, 99.90, 100.00, false,
    v_system_user_id, 'security@anthropic.com', 'EUR',
    '[{"name":"SOC2TypeII","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://anthropic.com","model":"claude-sonnet-4-6"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Revolut — IT_VENDOR, CRITICAL, APPROVED, rating 4.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_revolut,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'CRITICAL',
    now() - INTERVAL '5 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '7 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '7 months')::DATE,
    (CURRENT_DATE - INTERVAL '5 months')::DATE, 'CERTIFICATION_VERIFIED',
    85.00, 'Business banking and financial services platform — FCA regulated, ISO 27001. Business accounts and FX.',
    4.00, 98.00, 95.00, false,
    v_system_user_id, 'business-support@revolut.com', 'EUR',
    '[{"name":"ISO27001","issued":"2024-01-01","expires":"2025-01-01"},{"name":"PCI-DSS-L1","issued":"2024-01-01","expires":"2025-01-01"}]',
    '{"website":"https://revolut.com/business","plan":"Scale"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Trigger.dev — IT_VENDOR, MEDIUM, APPROVED, rating 4.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_triggerdev,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'MEDIUM',
    now() - INTERVAL '3 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '9 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '9 months')::DATE,
    (CURRENT_DATE - INTERVAL '3 months')::DATE, 'QUESTIONNAIRE',
    80.00, 'Background job and workflow orchestration platform. SOC 2 in progress. Used for async QMS workflows.',
    4.00, 97.00, 96.00, false,
    v_system_user_id, 'support@trigger.dev', 'EUR',
    '[]',
    '{"website":"https://trigger.dev","plan":"Pro"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

  -- Expo — IT_VENDOR, HIGH, APPROVED, rating 4.0
  INSERT INTO suppliers (
    org_id, company_id, supplier_code, status, category, criticality,
    approved_at, approved_by, approval_valid_until, reapproval_interval_months,
    next_reapproval_date, qualification_date, qualification_method,
    qualification_score, qualification_notes, current_rating,
    delivery_performance_pct, quality_performance_pct, single_source,
    responsible_id, quality_contact_email, contract_currency,
    certifications, metadata, created_by, created_at, updated_at
  ) VALUES (
    v_org_id, v_company_expo,
    'SUP-' || LPAD(nextval('supplier_number_seq')::TEXT, 3, '0'),
    'APPROVED', 'IT_VENDOR', 'HIGH',
    now() - INTERVAL '7 months', v_system_user_id,
    (CURRENT_DATE + INTERVAL '5 months')::DATE, 12,
    (CURRENT_DATE + INTERVAL '5 months')::DATE,
    (CURRENT_DATE - INTERVAL '7 months')::DATE, 'QUESTIONNAIRE',
    82.00, 'React Native application platform — EAS Build and EAS Submit. Powers mobile OMS applications.',
    4.00, 97.50, 96.00, false,
    v_system_user_id, 'support@expo.dev', 'EUR',
    '[]',
    '{"website":"https://expo.dev","plan":"Production"}',
    v_system_user_id, now(), now()
  ) ON CONFLICT (org_id, supplier_code) DO NOTHING;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'Supplier seed data skipped: % — %', SQLSTATE, SQLERRM;
END $$;

-- ============================================================================
-- 9. ISO 9001:2015 §8.4 COMPLIANCE REQUIREMENTS SEED
-- ============================================================================

-- §8.4.1 — General: type and extent of controls on external providers
DO $$
DECLARE
  v_org_id UUID;
BEGIN
  SELECT id INTO v_org_id FROM organizations WHERE name ILIKE '%wavult%' LIMIT 1;

  INSERT INTO iso_compliance_requirements (
    org_id,
    clause,
    clause_title,
    requirement_text,
    implementation_notes,
    evidence_type,
    applicable,
    created_at
  ) VALUES (
    v_org_id,
    '8.4.1',
    'Control of externally provided processes, products and services — General',
    'The organisation shall ensure that externally provided processes, products and services '
    'conform to requirements. The organisation shall determine the controls to be applied to '
    'externally provided processes, products and services when: (a) products and services from '
    'external providers are intended for incorporation into the organisation''s own products and '
    'services; (b) products and services are provided directly to the customer(s) by external '
    'providers on behalf of the organisation; (c) a process, or part of a process, is provided '
    'by an external provider as a result of a decision by the organisation. The organisation '
    'shall determine and apply criteria for the evaluation, selection, monitoring of performance, '
    'and re-evaluation of external providers, based on their ability to provide processes or '
    'products and services in accordance with requirements. The organisation shall retain '
    'documented information of these activities and any necessary actions arising from '
    'the evaluations.',
    'Implemented via: suppliers table (master record), supplier_evaluations (periodic scoring), '
    'v_supplier_performance (monitoring dashboard), approved_supplier_list (controlled ASL snapshots). '
    'Supplier selection criteria captured in qualification_method and qualification_score. '
    'Re-evaluation controlled via next_reapproval_date and reapproval_interval_months. '
    'Auto-escalation to ON_WATCH when >= 3 NCs in 90 days.',
    'APPROVED_SUPPLIER_LIST,EVALUATION_RECORDS,QUALIFICATION_DOCUMENTS',
    true,
    now()
  ) ON CONFLICT DO NOTHING;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'ISO §8.4.1 seed skipped: % — %', SQLSTATE, SQLERRM;
END $$;

-- §8.4.2 — Type and extent of control
DO $$
DECLARE
  v_org_id UUID;
BEGIN
  SELECT id INTO v_org_id FROM organizations WHERE name ILIKE '%wavult%' LIMIT 1;

  INSERT INTO iso_compliance_requirements (
    org_id,
    clause,
    clause_title,
    requirement_text,
    implementation_notes,
    evidence_type,
    applicable,
    created_at
  ) VALUES (
    v_org_id,
    '8.4.2',
    'Control of externally provided processes, products and services — Type and extent of control',
    'The organisation shall ensure that externally provided processes, products and services do not '
    'adversely affect the organisation''s ability to consistently deliver conforming products and '
    'services to its customers. The organisation shall: (a) ensure that externally provided processes '
    'remain within the control of its quality management system; (b) define both the controls that '
    'it intends to apply to an external provider and those it intends to apply to the resulting '
    'output; (c) take into consideration the potential impact of the externally provided processes, '
    'products and services on the organisation''s ability to consistently meet customer and '
    'applicable statutory and regulatory requirements; (d) determine the verification, or other '
    'activities, necessary to ensure that the externally provided processes, products and services '
    'meet requirements.',
    'Implemented via: supplier_criticality (CRITICAL/HIGH/MEDIUM/LOW) drives control intensity. '
    'supplier_audit_results records on-site, remote, document-review and process audits. '
    'supplier_nc_register links every NC to its external provider source. '
    'risk_level and single_source flags identify high-impact dependencies. '
    'alternative_supplier_ids tracks contingency sourcing options.',
    'AUDIT_REPORTS,NC_REGISTER,RISK_ASSESSMENTS,RECEIVING_INSPECTION_RECORDS',
    true,
    now()
  ) ON CONFLICT DO NOTHING;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'ISO §8.4.2 seed skipped: % — %', SQLSTATE, SQLERRM;
END $$;

-- §8.4.3 — Information for external providers
DO $$
DECLARE
  v_org_id UUID;
BEGIN
  SELECT id INTO v_org_id FROM organizations WHERE name ILIKE '%wavult%' LIMIT 1;

  INSERT INTO iso_compliance_requirements (
    org_id,
    clause,
    clause_title,
    requirement_text,
    implementation_notes,
    evidence_type,
    applicable,
    created_at
  ) VALUES (
    v_org_id,
    '8.4.3',
    'Control of externally provided processes, products and services — Information for external providers',
    'The organisation shall communicate to external providers its requirements for: (a) the '
    'processes, products and services to be provided; (b) the approval of: products and services, '
    'methods, processes and equipment, the release of products and services; (c) competence, '
    'including any required qualification of persons; (d) the external providers'' interactions '
    'with the organisation; (e) control and monitoring of the external providers'' performance '
    'to be applied by the organisation; (f) verification or validation activities that the '
    'organisation, or its customer, intends to perform at the external providers'' premises.',
    'Implemented via: approval_conditions (documented requirements communicated to supplier). '
    'quality_contact and quality_contact_email (named communication channel). '
    'supplier_nc_register.supplier_notified_at / supplier_response (evidence of two-way communication). '
    'corrective_action_required / corrective_action_accepted tracks 8D/CAPA exchange. '
    'qualification_document_id and report_document_id store evidence of communicated requirements. '
    'certifications JSONB records required certifications that suppliers must maintain.',
    'PURCHASE_ORDERS,QUALITY_AGREEMENTS,SUPPLIER_COMMUNICATIONS,CORRECTIVE_ACTION_RECORDS',
    true,
    now()
  ) ON CONFLICT DO NOTHING;

EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'ISO §8.4.3 seed skipped: % — %', SQLSTATE, SQLERRM;
END $$;

COMMIT;
