export type MaturityLevel =
  | 'skeleton'      // Struktur finns, inga features aktiva
  | 'alpha'         // Grundfunktioner, mockdata, ej produktionsklar
  | 'beta'          // Kärnfunktioner live, viss mockdata, används av teamet
  | 'production'    // Fullt funktionell, live data, stabil
  | 'enterprise'    // Battle-tested, SLA, audit trail, multi-entity

export interface ModuleMaturity {
  id: string
  name: string
  path: string
  icon: string
  level: MaturityLevel
  phase: number        // 1-4
  liveFeatures: string[]
  mockFeatures: string[]
  plannedFeatures: string[]
  dataSource: 'mock' | 'partial' | 'live'
  lastUpdated: string
  notes?: string
}

export const MATURITY_COLORS: Record<MaturityLevel, string> = {
  skeleton:   '#374151',  // grå
  alpha:      '#92400E',  // mörkbrun/orange
  beta:       '#1E40AF',  // blå
  production: '#065F46',  // mörkgrön
  enterprise: '#4C1D95',  // lila (premium)
}

export const MATURITY_BG: Record<MaturityLevel, string> = {
  skeleton:   '#1F2937',
  alpha:      '#1C1107',
  beta:       '#0D1B3E',
  production: '#022C22',
  enterprise: '#1E0A3C',
}

export const MATURITY_LABELS: Record<MaturityLevel, string> = {
  skeleton:   'SKELETON',
  alpha:      'ALPHA',
  beta:       'BETA',
  production: 'PRODUCTION',
  enterprise: 'ENTERPRISE',
}

export const MATURITY_DESCRIPTION: Record<MaturityLevel, string> = {
  skeleton:   'Arkitektur definierad. Inga live-features.',
  alpha:      'Grundfunktioner byggda med mockdata.',
  beta:       'Kärnfunktioner live. Används av teamet.',
  production: 'Fullt funktionell med live-data.',
  enterprise: 'Battle-tested. SLA, audit trail, multi-entity.',
}

// ALLA MODULER MED RÄTT MOGNADSGRAD
export const MODULE_REGISTRY: ModuleMaturity[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    path: '/dashboard',
    icon: '⬛',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Systemstatus', 'Team-aktivitet', 'Thailand countdown', 'Quick links'],
    mockFeatures: ['GitHub CI/CD status', 'Uptime-diagram'],
    plannedFeatures: ['Live alerts', 'Realtime metrics'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'crm',
    name: 'CRM',
    path: '/crm',
    icon: '🎯',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Pipeline-vy', 'Prospect-lista', 'Kontakter', 'Aktivitetslogg'],
    mockFeatures: ['Alla prospects och deals (mockdata)', 'Thailand targets'],
    plannedFeatures: ['Live Supabase-koppling', 'Email-integration', 'Deal-automation'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'finance',
    name: 'Finance',
    path: '/finance',
    icon: '💰',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Kontoplan', 'Transaktionsvy', 'Fakturalista', 'Kassaflödesdiagram'],
    mockFeatures: ['Alla siffror är mockdata', 'Intercompany-flöden'],
    plannedFeatures: ['Revolut API-koppling', 'Stripe-fakturor', 'Live ledger mot Supabase'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'payroll',
    name: 'Lön & Personal',
    path: '/payroll',
    icon: '👥',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Löneoversikt', 'Anställningslista', 'Lönespecar', 'Semesterspårning'],
    mockFeatures: ['Alla lönebelopp (mockdata)', 'AGI-status'],
    plannedFeatures: ['BankID-signering', 'Fortnox-integration', 'Skattemyndigheten API'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'legal',
    name: 'Legal Hub',
    path: '/legal',
    icon: '⚖',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Dokumentlista', '23 dokument', 'Signeringsflöden', 'Skapa dokument-modal'],
    mockFeatures: ['Signeringsstatus (ej live BankID)'],
    plannedFeatures: ['Live BankID-integration', 'DocuSign webhook', 'Auto-contract generation'],
    dataSource: 'partial',
    lastUpdated: '2026-03-27',
  },
  {
    id: 'corporate',
    name: 'Bolagsadmin',
    path: '/corporate',
    icon: '⚖️',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Ägarstruktur', 'Jurisdiktionsöversikt', 'Compliance-tracker'],
    mockFeatures: ['Alla deadlines (mockdata)', 'Dokumentvalv'],
    plannedFeatures: ['Bolagsverket API', 'DMCC-portal integration', 'Auto-compliance alerts'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'milestones',
    name: 'Milestones',
    path: '/milestones',
    icon: '🚀',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Thailand prep checklista', 'Bolagsstruktur tracker', 'Roadmap Q2-Q4'],
    mockFeatures: ['quiXzoom launch tracker'],
    plannedFeatures: ['Automatisk milestone-extraktion från tasks', 'Gantt-integration'],
    dataSource: 'partial',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'communications',
    name: 'Kommunikation',
    path: '/communications',
    icon: '📡',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Inbox UI', 'API-statusöversikt', 'Webhook-logg UI'],
    mockFeatures: ['Alla meddelanden (mockdata)', 'SMS-logg'],
    plannedFeatures: ['46elks live SMS', 'Slack/Teams webhook', 'Realtime inbox via Supabase'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'procurement',
    name: 'Inköp',
    path: '/procurement',
    icon: '🛒',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Leverantörslista', 'Inköpsordrar UI', 'Godkännandeflöde UI'],
    mockFeatures: ['Alla leverantörer och kontrakt (mockdata)'],
    plannedFeatures: ['Live leverantörskontrakt', 'PO-automation', 'Fortnox-integration'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'reports',
    name: 'Rapporter',
    path: '/reports',
    icon: '📊',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Executive Summary UI', 'P&L-vy', 'Säljrapport UI'],
    mockFeatures: ['Alla siffror (mockdata)'],
    plannedFeatures: ['Live data från Finance + CRM', 'PDF-export', 'Scheduled reports'],
    dataSource: 'mock',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'settings',
    name: 'Inställningar',
    path: '/settings',
    icon: '⚙️',
    level: 'beta',
    phase: 2,
    liveFeatures: ['API-nyckelöversikt', 'Rollhantering UI', 'System-info'],
    mockFeatures: ['Alla API-statusar (mockdata)'],
    plannedFeatures: ['Live API-key management', 'SSO/OAuth2', 'Audit log'],
    dataSource: 'partial',
    lastUpdated: '2026-03-26',
  },
  {
    id: 'media',
    name: 'Media & Ads',
    path: '/media',
    icon: '📡',
    level: 'skeleton',
    phase: 1,
    liveFeatures: [],
    mockFeatures: ['Kampanjstruktur', 'Channel-lista', 'Budget-UI'],
    plannedFeatures: ['Spotify Ads API', 'Google Ads API', 'Meta Ads API', 'The Trade Desk', 'Auto-budget'],
    dataSource: 'mock',
    lastUpdated: '2026-03-27',
    notes: 'Fas 1 — Skeleton. Alla integrationer planerade för Fas 2+',
  },
  {
    id: 'org',
    name: 'Corporate Graph',
    path: '/org',
    icon: '🏗',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Org-graf', 'Org Hierarchy', 'Entity-switcher'],
    mockFeatures: ['KPI-data per person'],
    plannedFeatures: ['Live HR-data', 'Realtime org-changes'],
    dataSource: 'partial',
    lastUpdated: '2026-03-25',
  },
  {
    id: 'knowledge',
    name: 'Knowledge Hub',
    path: '/knowledge',
    icon: '📚',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Kunskapsbas (12 dokument)', 'Kunskapsgraf D3', 'Academy (5 kurser)', 'Zoomer-certifiering'],
    mockFeatures: ['Alla dokument lokala', 'Progress i localStorage'],
    plannedFeatures: ['Live Supabase sync', 'Dokumentredigering', 'Team-progress dashboard', 'AI-sökning'],
    dataSource: 'mock',
    lastUpdated: '2026-03-27',
  },
  {
    id: 'people-intelligence',
    name: 'People Intelligence',
    path: '/people-intelligence',
    icon: '🧠',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['DISC-profiler för hela teamet', 'Energi & fokus-tracking', 'Beslutsarkitektur per roll', 'Kommunikationstips'],
    mockFeatures: ['Alla DISC-scores statiska', 'Energi-data mockad'],
    plannedFeatures: ['Live DISC-assessment', 'AI-rekommendationer baserat på DISC', 'Supabase sync', 'Team-dynamikanalys'],
    dataSource: 'mock',
    lastUpdated: '2026-03-27',
    notes: 'Fas 1 — DISC-data baserad på profil-bedömning. Integrerar certified-spark-engine/DISCPlus',
  },
  {
    id: 'talent-radar',
    name: 'Talent Radar',
    path: '/talent-radar',
    icon: '🎯',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['OpenClaw elite target list', 'GitHub star rankings', 'Status pipeline'],
    mockFeatures: ['Outreach automation', 'Activity monitoring'],
    plannedFeatures: ['GitHub API live activity feed', 'Auto-outreach via email', 'Reddit signal tracking'],
    dataSource: 'mock',
    lastUpdated: '2026-03-27',
    notes: 'Fas 1 — Manual talent pipeline för OpenClaw-elit. Live GitHub data planerat fas 2.',
  },
  {
    id: 'system-intelligence',
    name: 'System Intelligence',
    path: '/system-intelligence',
    icon: '📡',
    level: 'alpha',
    phase: 1,
    liveFeatures: ['Koncernhälsa-oscilloskop', 'Strategisk riskmatris', 'Beslutslogg', 'Marknadssignaler'],
    mockFeatures: ['Alla hälsopoäng statiska', 'Riskdata manuellt inmatad'],
    plannedFeatures: ['Live data från Supabase', 'AI-riskanalys', 'Automatiska marknadsignaler', 'Lambda-integration'],
    dataSource: 'mock',
    lastUpdated: '2026-03-27',
    notes: 'Fas 1 — Inspirerad av dissg/Lambda System. Anpassad för Wavult Group-koncernen.',
  },
  {
    id: 'api-hub',
    name: 'API Hub',
    path: '/api-hub',
    icon: '🔌',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Integrationskatalog (100+ APIs)', 'Aktiva integrationer (10 live)', 'Provider-nyheter', 'Sök och filter per kategori'],
    mockFeatures: ['Provider-nyheter (statisk demo)', 'uapix live-koppling ej aktiv'],
    plannedFeatures: ['Live uapix Supabase provider_updates', 'API-nyckelhantering', 'Realtidsstatus per integration', 'Webhook-logg'],
    dataSource: 'partial',
    lastUpdated: '2026-03-27',
    notes: 'Fas 2 — Extraherat från uapix (wolfoftyreso-debug/uapix). 34 kategorier, 100+ integrationer.',
  },
  {
    id: 'llm-hub',
    name: 'LLM Hub',
    path: '/llm-hub',
    icon: '🧠',
    level: 'beta',
    phase: 2,
    liveFeatures: [
      'Chat-gränssnitt (user/assistant bubblor)',
      'Playground (system + user prompt)',
      'Provider-status panel',
      'Fallback-kedja: GPT-4.6 → Claude Sonnet → Graceful Error',
      'Provider-badge per svar',
      'Latens-mätning i Playground',
    ],
    mockFeatures: [],
    plannedFeatures: [
      'Konversationshistorik i Supabase',
      'Streaming-svar',
      'gpt-4.6 när modellen blir tillgänglig via API',
      'Custom system-promptar per modul',
    ],
    dataSource: 'live',
    lastUpdated: '2026-03-27',
    notes: 'Beta — Live LLM-integration med OpenAI + Anthropic. Fallback-strategi implementerad.',
  },
  {
    id: 'insurance',
    name: 'Insurance Hub',
    path: '/insurance',
    icon: '🛡',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Försäkringskatalog (9 policies)', 'Veckorevision med score', 'Entity-täckningsöversikt', 'Kritiska gap-notifieringar'],
    mockFeatures: ['Revisionshistorik (mockad)', 'Alla försäkringsdata statiska'],
    plannedFeatures: ['Live förnyelsedatum-tracking', 'Integration med leverantörs-API', 'Auto-påminnelse vid förfall', 'Dokumentarkiv per policy'],
    dataSource: 'mock',
    lastUpdated: '2026-03-28',
    notes: 'Beta — Statisk datakatalog med automatisk veckorevision. Kritiska gap identifierade för hela koncernen.',
  },
  {
    id: 'whoop',
    name: 'WHOOP Team Pulse',
    path: '/whoop',
    icon: '⌚',
    level: 'beta',
    phase: 2,
    liveFeatures: [
      'OAuth2-koppling per teammedlem',
      'Recovery score med färgkodning',
      'Sömn & strain-data',
      'Team-aggregering med genomsnitt',
    ],
    mockFeatures: [],
    plannedFeatures: [
      'Historisk trend per person',
      'Workload-rekommendationer baserat på recovery',
      'Notifiering vid låg recovery',
      'Integration med kalender/milestones',
    ],
    dataSource: 'live',
    lastUpdated: '2026-03-27',
    notes: 'Beta — WHOOP Developer API OAuth2. Kräver WHOOP_CLIENT_ID + WHOOP_CLIENT_SECRET i env.',
  },
  {
    id: 'team-map',
    name: 'Team Map',
    path: '/team-map',
    icon: '🗺',
    level: 'beta',
    phase: 2,
    liveFeatures: ['Mapbox dark-v11 karta', 'Teammedlemmar som avatar-bubblor', 'Realtid via 30s-poll mot Supabase'],
    mockFeatures: ['Alla koordinater är mockdata', 'Positioner uppdateras ej automatiskt'],
    plannedFeatures: [
      'Supabase Realtime subscription',
      'Push-uppdatering av position via bakgrundsprocess',
      'Geofencing-notifieringar',
      'Historisk rörelsekarta',
    ],
    dataSource: 'mock',
    lastUpdated: '2026-03-28',
    notes: 'Beta — Mapbox GL JS med mockdata i Supabase. Browser Geolocation API för dela position.',
  },
]
