-- ============================================================================
-- QuixZoom — Tasks, Images, Assignments
-- File: 42_quixzoom_tasks.sql
-- Depends: 41_quixzoom_users.sql
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. TASK TEMPLATES (what types of tasks exist)
-- ============================================================================
CREATE TABLE IF NOT EXISTS qz_task_templates (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug            TEXT        NOT NULL UNIQUE,
  title           TEXT        NOT NULL,
  description     TEXT,
  category        TEXT        NOT NULL CHECK (category IN (
                    'storefront', 'facade', 'signage', 'interior',
                    'landscape', 'infrastructure', 'vehicle', 'event', 'custom'
                  )),
  required_images INTEGER     NOT NULL DEFAULT 1,
  min_level_tier  INTEGER     NOT NULL DEFAULT 1,  -- minimum level ordinal
  base_payout     NUMERIC(10,2) NOT NULL,
  time_limit_mins INTEGER     DEFAULT 60,
  instructions    JSONB       DEFAULT '[]',  -- step-by-step capture guide
  ai_requirements JSONB       DEFAULT '{}',  -- what AI should detect
  active          BOOLEAN     NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- 2. TASKS (concrete instances, may be generated by demand engine)
-- ============================================================================
CREATE TABLE IF NOT EXISTS qz_tasks (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  template_id     UUID        REFERENCES qz_task_templates(id),
  title           TEXT        NOT NULL,
  description     TEXT,
  category        TEXT        NOT NULL,
  required_images INTEGER     NOT NULL DEFAULT 1,
  payout_amount   NUMERIC(10,2) NOT NULL,
  currency        TEXT        NOT NULL DEFAULT 'SEK',
  tier            INTEGER     NOT NULL DEFAULT 1,

  -- Geospatial
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  radius_meters   INTEGER     DEFAULT 200,
  address         TEXT,
  area_name       TEXT,        -- "Södermalm", "Långsjövägen"
  city            TEXT,
  country         TEXT        DEFAULT 'SE',

  -- Source (who/what generated this task)
  source          TEXT        NOT NULL DEFAULT 'system'
                    CHECK (source IN ('system', 'demand', 'manual', 'ai_generated', 'ir_gap')),
  demand_id       UUID,       -- if generated from a demand query

  -- State
  status          TEXT        NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open','assigned','in_progress','review','completed','expired','cancelled')),
  max_assignees   INTEGER     NOT NULL DEFAULT 1,
  assigned_count  INTEGER     NOT NULL DEFAULT 0,
  priority        INTEGER     NOT NULL DEFAULT 0,  -- higher = more urgent
  expires_at      TIMESTAMPTZ,

  metadata        JSONB       DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_qz_tasks_status ON qz_tasks(status);
CREATE INDEX IF NOT EXISTS idx_qz_tasks_category ON qz_tasks(category);
CREATE INDEX IF NOT EXISTS idx_qz_tasks_tier ON qz_tasks(tier);
CREATE INDEX IF NOT EXISTS idx_qz_tasks_geo ON qz_tasks(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_qz_tasks_area ON qz_tasks(area_name, city);
CREATE INDEX IF NOT EXISTS idx_qz_tasks_expires ON qz_tasks(expires_at) WHERE status = 'open';

-- ============================================================================
-- 3. TASK ASSIGNMENTS (who is working on what)
-- ============================================================================
CREATE TABLE IF NOT EXISTS qz_task_assignments (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id         UUID        NOT NULL REFERENCES qz_tasks(id),
  user_id         UUID        NOT NULL REFERENCES qz_users(id),
  status          TEXT        NOT NULL DEFAULT 'assigned'
                    CHECK (status IN ('assigned','in_progress','submitted','approved','rejected','expired')),
  started_at      TIMESTAMPTZ,
  submitted_at    TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  payout_amount   NUMERIC(10,2),
  streak_multiplier NUMERIC(4,2) DEFAULT 1.00,
  final_payout    NUMERIC(10,2),  -- payout_amount * streak_multiplier
  reviewer        TEXT,
  rejection_reason TEXT,
  metadata        JSONB       DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(task_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_qz_assignments_user ON qz_task_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_qz_assignments_status ON qz_task_assignments(status);

-- ============================================================================
-- 4. IMAGES (captured by creators)
-- ============================================================================
CREATE TABLE IF NOT EXISTS qz_images (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id   UUID        NOT NULL REFERENCES qz_task_assignments(id),
  user_id         UUID        NOT NULL REFERENCES qz_users(id),
  task_id         UUID        NOT NULL REFERENCES qz_tasks(id),

  -- Storage
  storage_key     TEXT        NOT NULL,  -- S3 key
  storage_bucket  TEXT        NOT NULL,
  thumbnail_key   TEXT,
  file_size_bytes BIGINT,
  mime_type       TEXT        DEFAULT 'image/jpeg',

  -- Geolocation (captured from device)
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  altitude        NUMERIC(8,2),
  accuracy_meters NUMERIC(6,2),
  heading         NUMERIC(5,2),

  -- AI Analysis (populated async)
  ai_status       TEXT        NOT NULL DEFAULT 'pending'
                    CHECK (ai_status IN ('pending','processing','completed','failed')),
  ai_labels       JSONB       DEFAULT '[]',    -- [{label, confidence}]
  ai_condition    TEXT,                          -- good, fair, poor, damaged
  ai_category     TEXT,                          -- facade, signage, etc.
  ai_score        NUMERIC(5,2),                  -- quality/opportunity score 0-100
  ai_analysis     JSONB       DEFAULT '{}',     -- full AI response

  -- Validation
  validation_status TEXT      NOT NULL DEFAULT 'pending'
                    CHECK (validation_status IN ('pending','auto_approved','manual_review','approved','rejected')),
  validated_by    TEXT,
  validation_notes TEXT,

  captured_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_qz_images_assignment ON qz_images(assignment_id);
CREATE INDEX IF NOT EXISTS idx_qz_images_user ON qz_images(user_id);
CREATE INDEX IF NOT EXISTS idx_qz_images_task ON qz_images(task_id);
CREATE INDEX IF NOT EXISTS idx_qz_images_ai_status ON qz_images(ai_status);
CREATE INDEX IF NOT EXISTS idx_qz_images_validation ON qz_images(validation_status);

-- ============================================================================
-- 5. DEMAND QUERIES (what buyers/searchers are looking for)
-- ============================================================================
CREATE TABLE IF NOT EXISTS qz_demand_queries (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  query_text      TEXT        NOT NULL,    -- "wooden facades Långsjövägen"
  parsed_intent   JSONB       DEFAULT '{}', -- { objects: ["facade"], material: "wood" }
  parsed_location JSONB       DEFAULT '{}', -- { area: "Långsjövägen", lat, lng }
  category        TEXT,
  latitude        NUMERIC(10,7),
  longitude       NUMERIC(10,7),
  radius_meters   INTEGER     DEFAULT 500,
  requester_id    UUID,       -- could be anonymous
  tasks_generated INTEGER     DEFAULT 0,
  status          TEXT        NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','fulfilled','expired','cancelled')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_qz_demand_status ON qz_demand_queries(status);
CREATE INDEX IF NOT EXISTS idx_qz_demand_geo ON qz_demand_queries(latitude, longitude);

COMMIT;
