#!/usr/bin/env python3
"""
Generate seed_testdata.sql for 6 pixdrift test companies.
Run: python3 gen_seed.py > seed_testdata.sql
"""

import sys
import random
from datetime import date, timedelta

random.seed(42)

# ─── ID blocks (static so the file is idempotent) ────────────────────────────
# Each org gets a prefix block of 4-hex digits to avoid collisions.
# org1 = 0001, org2 = 0002 … org6 = 0006

def uid(org_prefix: int, group: int, seq: int) -> str:
    """Stable UUID: ORG-GROUP-SEQ"""
    return f"{org_prefix:04x}{group:04x}-0000-0000-0000-{seq:012x}"

def d(y, m, day):
    return date(y, m, day).isoformat()

def rand_date(start: date, end: date) -> date:
    return start + timedelta(days=random.randint(0, (end - start).days))

START = date(2025, 3, 1)
END   = date(2026, 2, 28)

MONTHS = []
for yr in [2025, 2026]:
    for mo in range(1, 13):
        d_ = date(yr, mo, 1)
        if START <= d_ <= END:
            MONTHS.append(d_)

lines = []

def L(s=""):
    lines.append(s)

def sql_str(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"

# ─── HEADER ──────────────────────────────────────────────────────────────────
L("-- ============================================================")
L("-- seed_testdata.sql — 6 pixdrift test companies, full year")
L("-- Generated by gen_seed.py — DO NOT EDIT MANUALLY")
L("--")
L("-- Companies:")
L("--   Org 1: Restaurang Björnen AB      (0001xxxx-...)")
L("--   Org 2: Lindqvists Bilverkstad     (0002xxxx-...)")
L("--   Org 3: Novacode AB                (0003xxxx-...)")
L("--   Org 4: Svensson Snickeri          (0004xxxx-...)")
L("--   Org 5: VVS Proffsen               (0005xxxx-...)")
L("--   Org 6: Nordic Shop                (0006xxxx-...)")
L("-- ============================================================")
L()
L("BEGIN;")
L()

# ─── HELPERS ─────────────────────────────────────────────────────────────────

DEAL_STATUSES = ['NEW','QUALIFIED','DEMO','OFFER','NEGOTIATION','WON','LOST']
TASK_STATUSES = ['TODO','IN_PROGRESS','REVIEW','DONE','BLOCKED']
NC_SEVERITIES = ['OBSERVATION','MINOR','MAJOR','CRITICAL']
NC_STATUSES   = ['OPEN','ANALYZING','ACTION_PLANNED','IMPLEMENTING','VERIFYING','CLOSED']
RISK_CATS     = ['OPERATIONAL','TECHNICAL','FINANCIAL','LEGAL','STRATEGIC']
RISK_LEVELS   = ['LOW','MEDIUM','HIGH','CRITICAL']

# ─── ORG DATA DEFINITIONS ────────────────────────────────────────────────────

orgs = [
    {
        "n": 1,
        "name": "Restaurang Björnen AB",
        "slug": "restaurang-bjornen",
        "domain": "bjornen.se",
        "currency": "SEK",
        "industry": "Restaurang/Hospitality",
        "city": "Stockholm",
        "annual_rev": 3_500_000,
        "team": [
            ("Anna", "Bergström",  "ADMIN",   "Restaurangchef"),
            ("Lars", "Ekström",    "OPS",     "Kock"),
            ("Maja", "Lindgren",   "OPS",     "Kock"),
            ("Johan","Nilsson",    "OPS",     "Servitör"),
            ("Sara", "Andersson",  "OPS",     "Servitris"),
            ("Emil", "Johansson",  "OPS",     "Servitör"),
            ("Karin","Svensson",   "FINANCE", "Kassör"),
            ("Mikael","Persson",   "OPS",     "Diskare"),
        ],
        "suppliers": [
            ("Lantmännen Unibake AB",    "Livsmedelsgrossist"),
            ("Martin & Servera AB",      "Restauranggrossist"),
            ("Carlsberg Sverige AB",     "Dryckesleverantör"),
            ("Ekologiska Bönder i Sverige","Ekologiska råvaror"),
            ("Städa Proffsen AB",        "Städtjänster"),
        ],
        "deal_titles": [
            "Företagslunch Spotify AB",
            "Bröllopsmiddag – familjen Lindqvist",
            "Julbord konferens 50 pers",
            "Cateringtjänst stadshuset",
            "Privat middag – 20 pers",
            "Onsdagsbuffé-avtal Accenture",
            "Sommarfest BRF Solbacken",
            "Personalfest Ericsson 80 pers",
            "Midsommarkräftskiva 30 pers",
            "Afterwork-paket månadsvis",
        ],
        "process_names": [
            ("P-001", "Öppning av restaurang"),
            ("P-002", "Stängning av restaurang"),
            ("P-003", "Leveranskontroll råvaror"),
            ("P-004", "Daglig hygienrond"),
            ("P-005", "Bemanningsplanering vecka"),
            ("P-006", "Klagomålshantering gäst"),
            ("P-007", "Kassaavstämning"),
            ("P-008", "Veckobeställning leverantör"),
            ("P-009", "Brandövning personal"),
            ("P-010", "Personalintroduktion"),
        ],
        "nc_titles": [
            ("NC-001", "Felaktigt märkt allergenprodukt", "MAJOR"),
            ("NC-002", "Temperaturavvikelse kylrum", "CRITICAL"),
            ("NC-003", "Missad leveranskontroll", "MINOR"),
            ("NC-004", "Klagomål – för lång väntetid", "OBSERVATION"),
            ("NC-005", "Personalresurs saknas fredagskväll", "MINOR"),
            ("NC-006", "Bryggfel espressomaskin", "MINOR"),
        ],
        "risk_items": [
            ("R-001", "Hög personalomsättning", "OPERATIONAL", 4, 4, "HIGH",
             "Strukturerad onboarding och löneöversyn"),
            ("R-002", "Leverantörsbrist råvaror", "OPERATIONAL", 3, 4, "HIGH",
             "Identifiera backup-leverantörer"),
            ("R-003", "Brandrisk köket", "OPERATIONAL", 2, 5, "HIGH",
             "Månadsvis brandskyddsrond"),
        ],
    },
    {
        "n": 2,
        "name": "Lindqvists Bilverkstad",
        "slug": "lindqvists-bilverkstad",
        "domain": "lindqvistsbil.se",
        "currency": "SEK",
        "industry": "Automotive service",
        "city": "Göteborg",
        "annual_rev": 8_000_000,
        "team": [
            ("Bengt",    "Lindqvist",  "ADMIN",   "Verkstadschef"),
            ("Pär",      "Carlsson",   "SALES",   "Försäljare"),
            ("Gunnar",   "Eriksson",   "OPS",     "Chefsmekaniker"),
            ("Thomas",   "Nilsson",    "OPS",     "Mekaniker"),
            ("Henrik",   "Bergman",    "OPS",     "Mekaniker"),
            ("Sven",     "Holm",       "OPS",     "Mekaniker"),
            ("Eva",      "Persson",    "OPS",     "Mekaniker"),
            ("Annika",   "Larsson",    "FINANCE", "Administratör"),
            ("Rickard",  "Gustafsson", "OPS",     "Mekaniker"),
            ("Magnus",   "Olsson",     "OPS",     "Mekaniker"),
            ("Lena",     "Strand",     "OPS",     "Receptionist"),
            ("Tobias",   "Björk",      "OPS",     "Mekaniker"),
        ],
        "suppliers": [
            ("Autodistribution AB",     "Reservdelshandel"),
            ("Bosch Service AB",        "Diagnosutrustning"),
            ("Delphi Technologies SE",  "Elektronikkomponenter"),
            ("Meca Sverige AB",         "Reservdelar"),
            ("InterCars Sverige AB",    "Reservdelar"),
        ],
        "deal_titles": [
            "Serviceavtal Volvo V90 – fam. Karlsson",
            "Bytarbyte – Toyota Corolla",
            "Karossreparation BMW 3-serie",
            "AC-service och påfyllning",
            "Bromsrenovering Audi A4",
            "Däckbyte + lagring vinter",
            "Rekonditionering Skoda Octavia",
            "Motorgenomgång Saab 9-3",
            "Kalibrering ADAS-sensorer Tesla",
            "Garantireparation VW Passat",
            "Oljebyte + filterbyte flotta",
            "Kamremsbyte Volkswagen Golf",
        ],
        "process_names": [
            ("P-001", "Inbokning arbetsorder"),
            ("P-002", "Diagnos och felsökning"),
            ("P-003", "Reservdelsbeställning"),
            ("P-004", "Kvalitetskontroll efter service"),
            ("P-005", "Kalibrering av mätdon"),
            ("P-006", "Kundkommunikation klar bil"),
            ("P-007", "Reklamationshantering"),
            ("P-008", "Kassa och fakturering"),
            ("P-009", "Lagerhantering reservdelar"),
            ("P-010", "Daglig checklistiga"),
        ],
        "nc_titles": [
            ("NC-001", "Kalibreringsinstrument ej godkänt", "MAJOR"),
            ("NC-002", "Kundreklamation – oljeläcka efter service", "CRITICAL"),
            ("NC-003", "Reservdel beställd fel modell", "MINOR"),
            ("NC-004", "Arbetsorder saknar kundsignatur", "OBSERVATION"),
            ("NC-005", "Försenad kalibrering bromsmätare", "MINOR"),
            ("NC-006", "Kassaavvikelse 450 SEK", "MINOR"),
        ],
        "risk_items": [
            ("R-001", "Kalibreringsstatus utgångna instrument", "TECHNICAL", 3, 4, "HIGH",
             "Halvårlig kalibrering av samtliga mätdon"),
            ("R-002", "Kundreklamation – ryktesrisk", "OPERATIONAL", 3, 3, "MEDIUM",
             "Snabb reklamationsprocess max 48h"),
            ("R-003", "Nyckelpersonsrisk – Gunnar Eriksson", "OPERATIONAL", 2, 5, "HIGH",
             "Kompetensspridning via intern mentorskap"),
        ],
    },
    {
        "n": 3,
        "name": "Novacode AB",
        "slug": "novacode",
        "domain": "novacode.se",
        "currency": "EUR",
        "industry": "SaaS/Tech",
        "city": "Stockholm",
        "annual_rev": 22_000_000,
        "team": [
            ("Erik",    "Svensson",   "ADMIN",   "VD"),
            ("Sofia",   "Lindqvist",  "MANAGER", "CTO"),
            ("Andreas", "Berg",       "MANAGER", "VP Sales"),
            ("Camilla", "Ek",         "OPS",     "Senior Developer"),
            ("Jonas",   "Lund",       "OPS",     "Senior Developer"),
            ("Emma",    "Hög",        "OPS",     "Frontend Developer"),
            ("Kristoffer","Nyman",    "OPS",     "Backend Developer"),
            ("Malin",   "Törnqvist",  "OPS",     "DevOps Engineer"),
            ("Anton",   "Sjögren",    "SALES",   "Account Executive"),
            ("Hanna",   "Wallin",     "SALES",   "Account Executive"),
            ("Patrik",  "Nordin",     "FINANCE", "CFO"),
            ("Lisa",    "Söderberg",  "OPS",     "UX Designer"),
            ("Daniel",  "Åkerman",    "OPS",     "Backend Developer"),
            ("Rebecka", "Hjort",      "OPS",     "QA Engineer"),
            ("Oscar",   "Blom",       "OPS",     "Developer"),
        ],
        "suppliers": [
            ("Amazon Web Services EMEA", "Cloud infrastructure"),
            ("Stripe Inc.",              "Payment processing"),
            ("HubSpot Ireland Ltd",      "CRM platform"),
            ("GitHub Inc.",              "Source control"),
            ("Datadog Inc.",             "Observability"),
        ],
        "deal_titles": [
            "SaaS Enterprise – Scania AB",
            "API Integration – Klarna Bank AB",
            "Platform license – Husqvarna AB",
            "SaaS Starter – Bamboo HR",
            "Custom dev – Nordic Capital",
            "SaaS Growth – ICA Gruppen AB",
            "White-label solution – Länsförsäkringar",
            "Consulting – Veoneer AB",
            "SaaS Enterprise – Sandvik AB",
            "Integration project – Stena Recycling",
            "Annual subscription – Getinge AB",
            "MVP development – Northvolt AB",
        ],
        "process_names": [
            ("P-001", "Sprint planning"),
            ("P-002", "Code review process"),
            ("P-003", "CI/CD deployment"),
            ("P-004", "Customer onboarding"),
            ("P-005", "Bug triage"),
            ("P-006", "Sales pipeline review"),
            ("P-007", "Incident management"),
            ("P-008", "Security audit"),
            ("P-009", "Capability assessment"),
            ("P-010", "Quarterly OKR review"),
        ],
        "nc_titles": [
            ("NC-001", "Produktionsincident – API timeout", "CRITICAL"),
            ("NC-002", "GDPR-brott – loggning PII", "MAJOR"),
            ("NC-003", "Deploy utan code review", "MINOR"),
            ("NC-004", "Missad SLA – Scania", "MAJOR"),
            ("NC-005", "Kapacitetsgap frontend", "OBSERVATION"),
            ("NC-006", "Felaktig FX-konvertering faktura", "MINOR"),
        ],
        "risk_items": [
            ("R-001", "Nyckelutvecklare lämnar", "STRATEGIC", 3, 5, "CRITICAL",
             "Retention-program + dokumentation"),
            ("R-002", "AWS region-outage", "TECHNICAL", 2, 5, "HIGH",
             "Multi-region fallback"),
            ("R-003", "Valutarisk EUR/USD/SEK", "FINANCIAL", 3, 3, "MEDIUM",
             "Hedging via forward-kontrakt"),
            ("R-004", "GDPR compliance-risk", "LEGAL", 2, 5, "HIGH",
             "Halvårlig GDPR-audit"),
        ],
    },
    {
        "n": 4,
        "name": "Svensson Snickeri",
        "slug": "svensson-snickeri",
        "domain": "svenssonsnickeri.se",
        "currency": "SEK",
        "industry": "Hantverkstjänster",
        "city": "Uppsala",
        "annual_rev": 1_800_000,
        "team": [
            ("Göran",  "Svensson", "ADMIN",   "Ägare/Snickare"),
            ("Niklas", "Persson",  "OPS",     "Snickare"),
            ("Helena", "Svensson", "FINANCE", "Administratör"),
        ],
        "suppliers": [
            ("Byggmax AB",          "Byggmaterial"),
            ("Optimera Sverige AB", "Byggvaror"),
            ("Würth Sverige AB",    "Verktyg och fästen"),
            ("Bauhaus AB",          "Byggmaterial"),
            ("K-rauta AB",          "Järnhandel"),
        ],
        "deal_titles": [
            "Kök renovering – fam. Lindgren",
            "Altan byggnad BRF Solbacken",
            "Carport – Villa Rosenlund",
            "Fönsterbyten 12 st – fam. Holm",
            "Inredning sovrum – fam. Berg",
            "Takbyte friggebod – Lars Nilsson",
            "Garagedörr installation",
            "Parkettläggning 80 kvm",
        ],
        "process_names": [
            ("P-001", "Offertprocess"),
            ("P-002", "Materialbeställning"),
            ("P-003", "Arbetsplanering"),
            ("P-004", "Slutbesiktning kund"),
            ("P-005", "Fakturering och uppföljning"),
            ("P-006", "Garantihantering"),
            ("P-007", "Leveranskontroll material"),
            ("P-008", "Arbetsmiljörond"),
            ("P-009", "Löneunderlag"),
            ("P-010", "Kunduppföljning"),
        ],
        "nc_titles": [
            ("NC-001", "Fel material levererat – Byggmax", "MINOR"),
            ("NC-002", "Kund missnöjd ytbehandling golv", "MINOR"),
            ("NC-003", "Saknad skyddsutrustning arbetsplats", "MAJOR"),
            ("NC-004", "Faktura skickad fel belopp", "MINOR"),
            ("NC-005", "Försenad leverans – 3 dagar", "OBSERVATION"),
        ],
        "risk_items": [
            ("R-001", "Sjukfrånvaro litet team", "OPERATIONAL", 4, 4, "HIGH",
             "Anlita timvikarie vid sjukdom"),
            ("R-002", "Materialprisstegring", "FINANCIAL", 3, 3, "MEDIUM",
             "Prisklauser i offerter >3 månader"),
            ("R-003", "Enda bil/verktyg slutar fungera", "OPERATIONAL", 2, 4, "MEDIUM",
             "Servicekontrakt på verktygspark"),
        ],
    },
    {
        "n": 5,
        "name": "VVS Proffsen AB",
        "slug": "vvs-proffsen",
        "domain": "vvsproffsen.se",
        "currency": "SEK",
        "industry": "VVS/Installation",
        "city": "Malmö",
        "annual_rev": 12_000_000,
        "team": [
            ("Christer",  "Magnusson",  "ADMIN",   "VD"),
            ("Susanne",   "Bergström",  "MANAGER", "Projektledare"),
            ("Hans",      "Eliasson",   "FINANCE", "Ekonomichef"),
            ("Björn",     "Pettersson", "OPS",     "Rörläggare"),
            ("Åke",       "Nordin",     "OPS",     "Rörläggare"),
            ("Conny",     "Sjöberg",    "OPS",     "Rörläggare"),
            ("Roger",     "Hansson",    "OPS",     "Rörläggare"),
            ("Marianne",  "Lundqvist",  "OPS",     "Rörläggare"),
            ("Stefan",    "Ek",         "OPS",     "Montör"),
            ("Jimmy",     "Strand",     "OPS",     "Montör"),
            ("Mattias",   "Björk",      "OPS",     "Serviceingenjör"),
            ("Anna-Karin","Fredriksson","OPS",     "Serviceingenjör"),
            ("Peter",     "Lindén",     "OPS",     "Rörläggare"),
            ("Marcus",    "Jonsson",    "OPS",     "Rörläggare"),
            ("Gunilla",   "Åhman",      "OPS",     "Administratör"),
            ("Tommy",     "Berglund",   "OPS",     "Rörläggare"),
            ("Eva-Lena",  "Svensson",   "OPS",     "Rörläggare"),
            ("Lars-Erik", "Johansson",  "SALES",   "Säljare"),
        ],
        "suppliers": [
            ("Beijer Ref AB",          "VVS-material"),
            ("Rörexperten AB",         "Rördelar"),
            ("Komfortgruppen AB",      "Värmepumpar"),
            ("Grundfos Sverige AB",    "Pumpar"),
            ("Uponor AB",              "Rörinstallation"),
        ],
        "deal_titles": [
            "Värmepumpsinstallation – BRF Solhem",
            "Stambyte kvarteret Linden",
            "VVS nyproduktion Malmö Port 24 lgh",
            "Serviceavtal fastighet Klippan",
            "Badrumsrenovering – fam. Persson",
            "Golvvärme 200 kvm – villa Åhus",
            "Vattenläcka akutreparation Emporia",
            "Sprinklerinstallation lagerhall",
            "Fjärrvärmekonvertering kv. Björnen",
            "Ventilationsservice årsavtal",
            "Kylinstallation serverrum",
            "Mark-VVS nybyggnation",
        ],
        "process_names": [
            ("P-001", "Projektplanering VVS"),
            ("P-002", "Materialupphandling"),
            ("P-003", "Besiktning och mätning"),
            ("P-004", "Installation och montering"),
            ("P-005", "Slutbesiktning"),
            ("P-006", "Certifieringskontroll"),
            ("P-007", "Subcontractor-hantering"),
            ("P-008", "Kundrapportering"),
            ("P-009", "Avvikelserapportering"),
            ("P-010", "Löpande serviceavtal"),
        ],
        "nc_titles": [
            ("NC-001", "Läckage koppling efter installation", "CRITICAL"),
            ("NC-002", "Certifikat utgånget – rörmontör", "MAJOR"),
            ("NC-003", "Subcontractor utan KMA-plan", "MAJOR"),
            ("NC-004", "Felaktig dimensionering rör", "MINOR"),
            ("NC-005", "Kund ej informerad om störning", "MINOR"),
            ("NC-006", "Dokumentation saknas slutbesiktning", "MINOR"),
        ],
        "risk_items": [
            ("R-001", "Subcontractor-kvalitet", "OPERATIONAL", 3, 4, "HIGH",
             "Certifieringskrav alla sub-leverantörer"),
            ("R-002", "Certifieringsrisk personal", "LEGAL", 3, 4, "HIGH",
             "Kalender för certifieringsförnyelse"),
            ("R-003", "Prisrisk material (koppar)", "FINANCIAL", 3, 3, "MEDIUM",
             "Terminssäkring koppar 6 månader"),
        ],
    },
    {
        "n": 6,
        "name": "Nordic Shop AB",
        "slug": "nordic-shop",
        "domain": "nordicshop.com",
        "currency": "SEK",
        "industry": "E-commerce",
        "city": "Stockholm",
        "annual_rev": 95_000_000,
        "team": [
            ("Fredrik",  "Almqvist",   "ADMIN",   "VD"),
            ("Cecilia",  "Stark",      "MANAGER", "COO"),
            ("Martin",   "Lövgren",    "FINANCE", "CFO"),
            ("Johanna",  "Kjellberg",  "MANAGER", "CTO"),
            ("Philip",   "Borg",       "SALES",   "CMO"),
            ("Sara",     "Hallberg",   "OPS",     "Lagerchefsansvarig"),
            ("Niklas",   "Dahlgren",   "OPS",     "IT-chef"),
            ("Kerstin",  "Holmström",  "OPS",     "Kundservicechef"),
            ("Per",      "Lindblom",   "OPS",     "Logistikchef"),
            ("Maria",    "Engström",   "SALES",   "E-commerce Manager"),
            ("Viktor",   "Löfgren",    "OPS",     "Senior Developer"),
            ("Amanda",   "Söderström", "OPS",     "UX Lead"),
            ("Jesper",   "Carlberg",   "OPS",     "Data Analyst"),
            ("Therese",  "Nordqvist",  "FINANCE", "Controller"),
            ("Gabriel",  "Åström",     "OPS",     "Warehouse Manager"),
        ],
        "suppliers": [
            ("DHL Express Sweden AB",    "Frakt & logistik"),
            ("PostNord Sverige AB",      "Frakt & logistik"),
            ("Adyen N.V.",               "Betalningsplattform"),
            ("Klarna Bank AB",           "Delbetalning"),
            ("Nshift AB",                "WMS system"),
        ],
        "deal_titles": [
            "B2B-avtal ICA Sverige AB",
            "Wholesale – Coop Sverige",
            "Enterprise marketplace – Amazon EU",
            "B2B textil – H&M Supply",
            "Dropshipping – Stadium AB",
            "Volymavtal – Jollyroom AB",
            "API-integration – Cervera AB",
            "White-label shop – KappAhl AB",
            "Partnership – Dustin AB",
            "Distribution – NetOnNet AB",
            "Affiliate-avtal – Prisjakt AB",
            "Logistics partner – DB Schenker",
        ],
        "process_names": [
            ("P-001", "Order-to-cash"),
            ("P-002", "Returshantering"),
            ("P-003", "Lagerhantering inleverans"),
            ("P-004", "Kundservice eskalering"),
            ("P-005", "Bedrägeridetektering"),
            ("P-006", "Finansiell rapportering"),
            ("P-007", "FX-hantering och hedging"),
            ("P-008", "GDPR-datahantering"),
            ("P-009", "Kampanjplanering"),
            ("P-010", "Leverantörsutvärdering"),
        ],
        "nc_titles": [
            ("NC-001", "Fel artikel levererad – 200 beställningar", "CRITICAL"),
            ("NC-002", "Dataintrång – kunddata exponerad", "CRITICAL"),
            ("NC-003", "Betalningsfel Klarna-integration", "MAJOR"),
            ("NC-004", "FX-felberäkning EUR/SEK fakturor", "MAJOR"),
            ("NC-005", "Lagerfel – negativt saldo SKU-X212", "MINOR"),
            ("NC-006", "SLA brott kundservice – 4h wait", "MINOR"),
        ],
        "risk_items": [
            ("R-001", "Cyberattack/dataintrång", "TECHNICAL", 3, 5, "CRITICAL",
             "SOC2 audit + penetrationstest"),
            ("R-002", "Logistikpartner-avbrott", "OPERATIONAL", 3, 4, "HIGH",
             "Backup-avtal med alternativ speditör"),
            ("R-003", "Valutarisk multi-currency", "FINANCIAL", 4, 4, "HIGH",
             "Hedging policy + FX-dashboard"),
            ("R-004", "GDPR-böter", "LEGAL", 2, 5, "HIGH",
             "DPO anställd + halvårlig audit"),
        ],
    },
]

# ─── GROUP IDs ────────────────────────────────────────────────────────────────
# GRP_ORG=1, GRP_USR=2, GRP_COM=3, GRP_CON=4, GRP_LEAD=5, GRP_DEAL=6,
# GRP_TASK=7, GRP_INV=8, GRP_TXN=9, GRP_PAY=10, GRP_PROC=11, GRP_EXEC=12,
# GRP_NC=13, GRP_RISK=14, GRP_KPI=15, GRP_CAP=16, GRP_GOAL=17, GRP_IMP=18

GRP_ORG  = 1
GRP_USR  = 2
GRP_COM  = 3
GRP_CON  = 4
GRP_LEAD = 5
GRP_DEAL = 6
GRP_TASK = 7
GRP_INV  = 8
GRP_TXN  = 9
GRP_PAY  = 10
GRP_PROC = 11
GRP_EXEC = 12
GRP_NC   = 13
GRP_RISK = 14
GRP_KPI  = 15
GRP_CAP  = 16
GRP_GOAL = 17
GRP_IMP  = 18

# ─── MAIN GENERATOR ──────────────────────────────────────────────────────────

for org in orgs:
    n   = org["n"]
    pfx = n  # 1-6

    org_id   = uid(pfx, GRP_ORG, 1)
    rep_curr = org["currency"]
    ex_rate  = 0.087 if rep_curr == "SEK" else 1.0  # SEK→EUR or EUR→EUR

    L(f"-- ============================================================")
    L(f"-- ORG {n}: {org['name']}")
    L(f"-- ============================================================")
    L()

    # 1. Organization
    L(f"INSERT INTO organizations (id, name, slug, domain, reporting_currency, settings)")
    L(f"VALUES ('{org_id}', {sql_str(org['name'])}, {sql_str(org['slug'])}, {sql_str(org['domain'])}, {sql_str(rep_curr)}, '{{}}'::JSONB)")
    L(f"ON CONFLICT (slug) DO NOTHING;")
    L()

    # 2. Users
    user_ids = []
    admin_id = None
    for i, (fn, ln, role, title) in enumerate(org["team"], 1):
        uid_ = uid(pfx, GRP_USR, i)
        user_ids.append(uid_)
        if role == "ADMIN" and admin_id is None:
            admin_id = uid_
        email = f"{fn.lower().replace('å','a').replace('ä','a').replace('ö','o').replace('-','')}.{ln.lower().replace('å','a').replace('ä','a').replace('ö','o')}@{org['domain']}"
        L(f"INSERT INTO users (id, org_id, email, full_name, role, title)")
        L(f"VALUES ('{uid_}', '{org_id}', {sql_str(email)}, {sql_str(fn+' '+ln)}, '{role}'::user_role, {sql_str(title)})")
        L(f"ON CONFLICT (org_id, email) DO NOTHING;")
    L()
    if admin_id is None:
        admin_id = user_ids[0]

    # 3. Companies (suppliers + extra customers)
    company_ids = []
    for i, (cname, cind) in enumerate(org["suppliers"], 1):
        cid = uid(pfx, GRP_COM, i)
        company_ids.append(cid)
        L(f"INSERT INTO companies (id, org_id, name, industry, country, created_by)")
        L(f"VALUES ('{cid}', '{org_id}', {sql_str(cname)}, {sql_str(cind)}, 'SE', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")

    # Generate 25+ more customer companies
    cust_first = ["AB ", "Företaget ", "Konsult AB ", "Sverige AB ", "Nordic "]
    cust_last  = ["Fastigheter","Bygg","Invest","Handel","Lösningar","Service","Partner","Projekt"]
    for i in range(6, 36):
        cname_ = random.choice(["Nilsson","Karlsson","Persson","Lindgren","Ek","Björn","Holm","Berg"]) + " " + random.choice(cust_last) + " AB"
        cid = uid(pfx, GRP_COM, i)
        company_ids.append(cid)
        L(f"INSERT INTO companies (id, org_id, name, industry, country, city, created_by)")
        L(f"VALUES ('{cid}', '{org_id}', {sql_str(cname_)}, {sql_str(org['industry'])}, 'SE', {sql_str(org['city'])}, '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    # 4. Contacts (30+)
    contact_ids = []
    first_names_f = ["Anna","Maria","Sara","Lena","Eva","Karin","Helena","Kristina","Monica","Linda","Emma","Maja"]
    first_names_m = ["Lars","Johan","Erik","Mikael","Anders","Stefan","Peter","Magnus","Tobias","Daniel","Marcus","Niklas"]
    last_names    = ["Svensson","Johansson","Nilsson","Eriksson","Karlsson","Larsson","Persson","Andersson","Lindqvist","Berg","Holm","Björk","Strand","Ekström","Nyman"]

    for i in range(1, 36):
        cid_ = uid(pfx, GRP_CON, i)
        contact_ids.append(cid_)
        fn_ = random.choice(first_names_f + first_names_m)
        ln_ = random.choice(last_names)
        comp_id_ = random.choice(company_ids)
        email_ = f"{fn_.lower().replace('å','a').replace('ä','a').replace('ö','o')}.{ln_.lower()}@example.com"
        L(f"INSERT INTO contacts (id, org_id, company_id, first_name, last_name, email, created_by)")
        L(f"VALUES ('{cid_}', '{org_id}', '{comp_id_}', {sql_str(fn_)}, {sql_str(ln_)}, {sql_str(email_)}, '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    # 5. Deals (50+)
    deal_titles_extended = org["deal_titles"] * 6  # repeat to get 50+
    deal_ids = []
    currencies_for_org = [rep_curr]
    if n == 3:
        currencies_for_org = ["EUR", "USD", "SEK"]
    elif n == 6:
        currencies_for_org = ["SEK", "EUR", "USD", "GBP", "NOK"]

    fx_map = {"SEK":1.0,"EUR":11.5,"USD":10.6,"GBP":13.2,"NOK":0.95,"DKK":1.55}

    base_amount = org["annual_rev"] / 52  # weekly avg deal

    for i in range(1, 56):
        did = uid(pfx, GRP_DEAL, i)
        deal_ids.append(did)
        title_ = deal_titles_extended[(i-1) % len(deal_titles_extended)] + f" #{i}"
        status_ = random.choice(DEAL_STATUSES)
        curr_   = random.choice(currencies_for_org)
        amount_ = round(random.uniform(0.5, 3.0) * base_amount, 2)
        ex_r    = fx_map.get(curr_, 1.0) / fx_map.get(rep_curr, 1.0)
        rep_amt = round(amount_ * ex_r, 2) if curr_ != rep_curr else amount_
        prob_   = 90 if status_ == "WON" else (10 if status_ == "LOST" else random.randint(20, 80))
        deal_date = rand_date(START, END)
        close_date = rand_date(deal_date, END)
        comp_  = random.choice(company_ids)
        cont_  = random.choice(contact_ids)
        owner_ = random.choice(user_ids)
        closed_at = f"'{deal_date.isoformat()}'" if status_ in ("WON","LOST") else "NULL"
        L(f"INSERT INTO deals (id, org_id, company_id, contact_id, title, status, amount, currency, exchange_rate, reporting_amount, probability, expected_close, closed_at, assigned_to, created_by)")
        L(f"VALUES ('{did}', '{org_id}', '{comp_}', '{cont_}', {sql_str(title_)}, '{status_}'::deal_status, {amount_}, '{curr_}', {ex_r}, {rep_amt}, {prob_}, '{close_date.isoformat()}', {closed_at}, '{owner_}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    # 6. Tasks (20+)
    task_titles = [
        "Förbered kvartalsrapport","Kundmöte bokas","Kontrollera lager","Uppdatera rutinbeskrivning",
        "Följ upp offert","Skicka faktura","Boka service","Genomför riskbedömning",
        "Planera personalsamtal","Uppdatera process-dokumentation","Genomför internrevision",
        "Följ upp NC","Upprätta handlingsplan","Kontakta leverantör","Planera veckoschema",
        "Granska avtal","Uppdatera KPI-tavla","Genomför kompetensbedömning","Boka utbildning",
        "Skicka kundenkät","Uppdatera riskregister","Genomför brandövning","Kalibrering instrument",
        "Följ upp certifiering",
    ]
    for i in range(1, 26):
        tid = uid(pfx, GRP_TASK, i)
        title_ = task_titles[(i-1) % len(task_titles)] + f" #{i}"
        status_ = random.choice(TASK_STATUSES)
        prio_   = random.randint(1, 5)
        due_    = rand_date(START, END)
        done_at = f"'{due_.isoformat()}'" if status_ == "DONE" else "NULL"
        deal_   = random.choice(deal_ids) if random.random() > 0.5 else None
        owner_  = random.choice(user_ids)
        deal_ref = f"'{deal_}'" if deal_ else "NULL"
        L(f"INSERT INTO tasks (id, org_id, title, status, priority, due_date, completed_at, deal_id, assigned_to, created_by)")
        L(f"VALUES ('{tid}', '{org_id}', {sql_str(title_)}, '{status_}'::task_status, {prio_}, '{due_.isoformat()}', {done_at}, {deal_ref}, '{owner_}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    # 7. Invoices (one per month + extras)
    inv_ids = []
    for i, m in enumerate(MONTHS, 1):
        iid = uid(pfx, GRP_INV, i)
        inv_ids.append(iid)
        inv_num = f"INV-{n:02d}-{m.year}-{m.month:02d}"
        amount_ = round(org["annual_rev"] / 12 * random.uniform(0.7, 1.3), 2)
        curr_   = random.choice(currencies_for_org)
        ex_r    = fx_map.get(curr_, 1.0) / fx_map.get(rep_curr, 1.0)
        rep_amt = round(amount_ * ex_r, 2) if curr_ != rep_curr else amount_
        tax_    = round(amount_ * 0.25, 2)
        status_ = random.choice(["PAID","PAID","SENT","OVERDUE"])
        issued  = m.replace(day=5).isoformat()
        due     = m.replace(day=30).isoformat() if m.month != 2 else m.replace(day=28).isoformat()
        paid    = f"'{m.replace(day=28).isoformat()}'" if status_ == "PAID" else "NULL"
        comp_   = random.choice(company_ids)
        L(f"INSERT INTO invoices (id, org_id, invoice_number, company_id, amount, currency, exchange_rate, reporting_amount, tax_amount, status, issued_at, due_at, paid_at, created_by)")
        L(f"VALUES ('{iid}', '{org_id}', {sql_str(inv_num)}, '{comp_}', {amount_}, '{curr_}', {ex_r}, {rep_amt}, {tax_}, '{status_}', '{issued}', '{due}', {paid}, '{admin_id}')")
        L(f"ON CONFLICT (org_id, invoice_number) DO NOTHING;")
    L()

    # 8. Transactions (monthly income + expenses)
    acc_income   = ("3000", "Försäljningsintäkter")
    acc_supplier = ("4000", "Råvaror och förnödenheter")
    acc_salary   = ("7010", "Löner tjänstemän")
    acc_rent     = ("5010", "Lokalhyra")
    acc_misc     = ("6999", "Övriga kostnader")

    txn_i = 0
    for m in MONTHS:
        # Income transaction
        txn_i += 1
        tid_ = uid(pfx, GRP_TXN, txn_i)
        amount_ = round(org["annual_rev"] / 12 * random.uniform(0.85, 1.15), 2)
        curr_   = random.choice(currencies_for_org)
        ex_r    = fx_map.get(curr_, 1.0) / fx_map.get(rep_curr, 1.0)
        inv_ref = f"'{random.choice(inv_ids)}'" if inv_ids else "NULL"
        L(f"INSERT INTO transactions (id, org_id, account_code, account_name, credit, currency, exchange_rate, reporting_credit, description, invoice_id, booked_at, created_by)")
        period_str = m.strftime("%Y-%m")
        L(f"VALUES ('{tid_}', '{org_id}', '{acc_income[0]}', '{acc_income[1]}', {amount_}, '{curr_}', {ex_r}, {round(amount_*ex_r,2)}, 'Månadsomsättning {period_str}', {inv_ref}, '{m.replace(day=15).isoformat()}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")

        # Supplier cost
        txn_i += 1
        tid_ = uid(pfx, GRP_TXN, txn_i)
        cost_ = round(amount_ * 0.35, 2)
        L(f"INSERT INTO transactions (id, org_id, account_code, account_name, debit, currency, exchange_rate, reporting_debit, description, booked_at, created_by)")
        L(f"VALUES ('{tid_}', '{org_id}', '{acc_supplier[0]}', '{acc_supplier[1]}', {cost_}, '{curr_}', {ex_r}, {round(cost_*ex_r,2)}, 'Leverantörskostnader {period_str}', '{m.replace(day=10).isoformat()}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")

        # Salary
        txn_i += 1
        tid_ = uid(pfx, GRP_TXN, txn_i)
        sal_ = round(30000 * len(org["team"]), 2)
        L(f"INSERT INTO transactions (id, org_id, account_code, account_name, debit, currency, exchange_rate, reporting_debit, description, booked_at, created_by)")
        L(f"VALUES ('{tid_}', '{org_id}', '{acc_salary[0]}', '{acc_salary[1]}', {sal_}, '{rep_curr}', 1.0, {sal_}, 'Löner {period_str}', '{m.replace(day=25).isoformat()}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    # 9. Processes (10 per org)
    proc_ids = []
    for i, (code_, name_) in enumerate(org["process_names"], 1):
        pid = uid(pfx, GRP_PROC, i)
        proc_ids.append(pid)
        owner_ = random.choice(user_ids)
        L(f"INSERT INTO processes (id, org_id, code, name, owner_id, is_active, avg_duration_min)")
        L(f"VALUES ('{pid}', '{org_id}', {sql_str(code_)}, {sql_str(name_)}, '{owner_}', TRUE, {random.randint(15,120)})")
        L(f"ON CONFLICT (org_id, code) DO NOTHING;")

        # 3 executions per process
        for j in range(1, 4):
            eid = uid(pfx, GRP_EXEC, (i-1)*4 + j)
            status_e = random.choice(["COMPLETED","COMPLETED","RUNNING","FAILED"])
            start_dt = rand_date(START, END)
            done_dt  = f"'{start_dt.isoformat()}'" if status_e in ("COMPLETED","FAILED") else "NULL"
            L(f"INSERT INTO process_executions (id, org_id, process_id, status, started_at, completed_at, duration_min, executed_by)")
            L(f"VALUES ('{eid}', '{org_id}', '{pid}', '{status_e}'::process_execution_status, '{start_dt.isoformat()}', {done_dt}, {random.randint(10,180)}, '{random.choice(user_ids)}')")
            L(f"ON CONFLICT DO NOTHING;")
    L()

    # 10. Non-conformances
    for i, (code_, title_, sev_) in enumerate(org["nc_titles"], 1):
        nid = uid(pfx, GRP_NC, i)
        status_nc = random.choice(["CLOSED","CLOSED","OPEN","ANALYZING","ACTION_PLANNED"])
        det_date  = rand_date(START, END)
        closed    = f"'{rand_date(det_date, END).isoformat()}'" if status_nc == "CLOSED" else "NULL"
        proc_ref  = f"'{random.choice(proc_ids)}'" if proc_ids else "NULL"
        reporter  = random.choice(user_ids)
        assignee  = random.choice(user_ids)
        L(f"INSERT INTO non_conformances (id, org_id, code, title, severity, status, process_id, reported_by, assigned_to, detected_at, closed_at)")
        L(f"VALUES ('{nid}', '{org_id}', {sql_str(code_)}, {sql_str(title_)}, '{sev_}'::nc_severity, '{status_nc}'::nc_status, {proc_ref}, '{reporter}', '{assignee}', '{det_date.isoformat()}', {closed})")
        L(f"ON CONFLICT (org_id, code) DO NOTHING;")
    L()

    # 11. Risks
    for i, (code_, title_, cat_, prob_, imp_, lvl_, mit_) in enumerate(org["risk_items"], 1):
        rid = uid(pfx, GRP_RISK, i)
        owner_ = random.choice(user_ids)
        proc_ref = f"'{random.choice(proc_ids)}'" if proc_ids else "NULL"
        L(f"INSERT INTO risks (id, org_id, code, title, category, probability, impact, risk_level, mitigation, owner_id, process_id, review_date)")
        L(f"VALUES ('{rid}', '{org_id}', {sql_str(code_)}, {sql_str(title_)}, '{cat_}'::risk_category, {prob_}, {imp_}, '{lvl_}'::risk_level, {sql_str(mit_)}, '{owner_}', {proc_ref}, '{rand_date(START, END).isoformat()}')")
        L(f"ON CONFLICT (org_id, code) DO NOTHING;")
    L()

    # 12. KPIs (monthly)
    kpi_defs = [
        ("Omsättning",   "SEK",  "%",       org["annual_rev"]/12),
        ("Antal deals",  "st",   "st",      40),
        ("Kundnöjdhet",  "%",    "%",       85),
        ("Ledtid",       "dagar","dagar",    5),
        ("Avvikelser",   "st",   "st",       2),
    ]
    kpi_seq = 0
    for m in MONTHS:
        for kname, unit_, _, target_ in kpi_defs:
            kpi_seq += 1
            kid = uid(pfx, GRP_KPI, kpi_seq)
            value_ = round(target_ * random.uniform(0.75, 1.25), 1)
            status_k = "GREEN" if value_ >= target_ * 0.9 else ("YELLOW" if value_ >= target_ * 0.7 else "RED")
            period_  = m.strftime("%Y-%m")
            L(f"INSERT INTO kpis (id, org_id, name, value, target, unit, status, period, measured_at)")
            L(f"VALUES ('{kid}', '{org_id}', {sql_str(kname)}, {value_}, {target_}, {sql_str(unit_)}, '{status_k}', {sql_str(period_)}, '{m.replace(day=28).isoformat()}')")
            L(f"ON CONFLICT DO NOTHING;")
    L()

    # 13. Goals (3 per org)
    goal_defs = [
        (f"Öka omsättning med 15%", org["annual_rev"] * 0.15, "SEK"),
        ("Minska avvikelser till <3/månad", 3, "st"),
        ("Kundnöjdhet > 90%", 90, "%"),
    ]
    for i, (gtitle_, target_, unit_) in enumerate(goal_defs, 1):
        gid = uid(pfx, GRP_GOAL, i)
        owner_ = random.choice(user_ids)
        status_g = random.choice(["ACTIVE","ON_TRACK","AT_RISK"])
        curr_v   = round(target_ * random.uniform(0.4, 0.9), 1)
        L(f"INSERT INTO goals (id, org_id, title, current_value, target_value, unit, status, start_date, end_date, owner_id, created_by)")
        L(f"VALUES ('{gid}', '{org_id}', {sql_str(gtitle_)}, {curr_v}, {target_}, {sql_str(unit_)}, '{status_g}'::goal_status, '2025-03-01', '2026-02-28', '{owner_}', '{admin_id}')")
        L(f"ON CONFLICT DO NOTHING;")
    L()

    L()

# ─── FOOTER ──────────────────────────────────────────────────────────────────
L("COMMIT;")
L()
L("-- End of seed_testdata.sql")

# Write output
output = "\n".join(lines)
with open("/mnt/c/Users/erik/Desktop/hypbit/sql/seed_testdata.sql", "w", encoding="utf-8") as f:
    f.write(output)

total_lines = len(lines)
print(f"Generated {total_lines} lines total", file=sys.stderr)
