// ─── BOS Task Registry — Wavult Group Q2 2026 ────────────────────────────────
// All real tasks with dependencies. If A is not done, B cannot start.

import type { Task, Flow } from './stateEngine'

export const TASKS: Task[] = [
  // ── LEGAL / BOLAGSSTRUKTUR ──────────────────────────────────────────────────
  {
    id: 'legal-001',
    title: 'Bilda Wavult Group FZCO (Dubai)',
    description: 'Ansök om Free Zone Company via DMCC. Business plan klar. Kräver pass, adress i UAE, kapital.',
    owner: 'erik-svensson',
    module: 'legal',
    flow: 'dubai-structure',
    state: 'REQUIRED',
    priority: 'critical',
    deadline: '2026-04-10',
    dependencies: [],
    requiredInputs: ['Pass', 'UAE-adress (via DMCC)', 'Startkapital'],
    outputValidation: 'Certificate of Incorporation mottaget från DMCC',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'legal-002',
    title: 'Bilda Wavult DevOps FZCO (Dubai)',
    description: 'Operativt holdingbolag under Wavult Group FZCO. Bildas parallellt.',
    owner: 'erik-svensson',
    module: 'legal',
    flow: 'dubai-structure',
    state: 'BLOCKED',
    priority: 'critical',
    deadline: '2026-04-10',
    dependencies: ['legal-001'],
    requiredInputs: ['Wavult Group FZCO Certificate of Incorporation'],
    outputValidation: 'Certificate of Incorporation för DevOps FZCO',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
    blockedReason: 'Wavult Group FZCO måste bildas först',
  },
  {
    id: 'legal-003',
    title: 'IP Assignment — överlåt all kod och varumärken till Dubai',
    description: 'Juridiskt dokument som överlåter all IP (kod, varumärken, domäner) från individerna till Wavult Group FZCO.',
    owner: 'dennis-bjarnemark',
    module: 'legal',
    flow: 'dubai-structure',
    state: 'BLOCKED',
    priority: 'critical',
    deadline: '2026-04-11',
    dependencies: ['legal-001'],
    requiredInputs: ['Wavult Group FZCO Certificate of Incorporation', 'Lista på all IP'],
    outputValidation: 'IP Assignment Agreement signerat av alla parter',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
    blockedReason: 'Wavult Group FZCO måste existera för att ta emot IP',
  },
  {
    id: 'legal-004',
    title: 'Välj bokföringsbyrå för Landvex AB',
    description: 'Landvex AB (559141-7042) är aktivt aktiebolag utan bokföring. Personligt straffansvar. Offert från 8 byråer skickad.',
    owner: 'dennis-bjarnemark',
    module: 'legal',
    flow: 'landvex-compliance',
    state: 'REQUIRED',
    priority: 'critical',
    deadline: '2026-04-01',
    dependencies: [],
    requiredInputs: ['Svar från revisorsbyråer'],
    outputValidation: 'Avtal signerat med bokföringsbyrå, org-nr bekräftat',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'legal-005',
    title: 'Slutför Texas LLC (Landvex Inc) — betala SOSDirect $325',
    description: 'SOSDirect Form 201 halvklar. $325 att betala. Expedited (24h): $300 + $25.',
    owner: 'dennis-bjarnemark',
    module: 'legal',
    flow: 'landvex-compliance',
    state: 'REQUIRED',
    priority: 'high',
    deadline: '2026-04-11',
    dependencies: [],
    requiredInputs: ['Kreditkort', 'SOSDirect-konto'],
    outputValidation: 'Certificate of Formation mottaget från Texas SOS',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'legal-006',
    title: 'Landvex AB namnbyte — bekräfta registrering',
    description: 'Namnbyte Sommarliden Holding AB → Landvex AB inlämnat. Bolagsverket: 1-2 veckor.',
    owner: 'dennis-bjarnemark',
    module: 'legal',
    flow: 'landvex-compliance',
    state: 'IN_PROGRESS',
    priority: 'high',
    deadline: '2026-04-07',
    dependencies: [],
    requiredInputs: [],
    outputValidation: 'Registreringsbevis från Bolagsverket med nytt namn',
    assignedAt: '2026-03-27',
    completedAt: null,
    validationRequired: false,
  },

  // ── FINANCE ─────────────────────────────────────────────────────────────────
  {
    id: 'finance-001',
    title: 'Identity Core på RDS — migration klar',
    description: 'Identity Core migration till RDS + DynamoDB — bekräfta att auth-flödet fungerar i produktion.',
    owner: 'winston-bjarnemark',
    module: 'finance',
    flow: 'infra-finance',
    state: 'REQUIRED',
    priority: 'critical',
    deadline: '2026-03-31',
    dependencies: [],
    requiredInputs: ['Kreditkort i Revolut Business'],
    outputValidation: 'Identity Core (RDS) svarar på auth-requests i produktion',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'finance-002',
    title: 'Välj revisor och starta löpande bokföring',
    description: 'Landvex AB kräver bokföring från dag 1. Offert till 8 byråer. Winston ansvarar.',
    owner: 'winston-bjarnemark',
    module: 'finance',
    flow: 'landvex-compliance',
    state: 'REQUIRED',
    priority: 'critical',
    deadline: '2026-04-01',
    dependencies: ['legal-004'],
    requiredInputs: ['Val av byrå', 'Bokföringsprogram (t.ex. Fortnox)'],
    outputValidation: 'Uppdragsavtal signerat, första månadsrapporten planerad',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'finance-003',
    title: 'Sätt upp intercompany faktureringsrutiner',
    description: 'IP-licens (5-15%) och management fee (8-15%) måste faktureras månadsvis mellan bolagen.',
    owner: 'winston-bjarnemark',
    module: 'finance',
    flow: 'intercompany',
    state: 'BLOCKED',
    priority: 'high',
    deadline: '2026-05-01',
    dependencies: ['legal-001', 'legal-002', 'legal-003'],
    requiredInputs: ['Dubai-bolagen bildade', 'IP Assignment klar', 'Intercompany-avtal'],
    outputValidation: 'Första intercompany-faktura skickad och bokförd',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
    blockedReason: 'Dubai-bolagen måste bildas och IP assignas först',
  },

  // ── TECH ────────────────────────────────────────────────────────────────────
  {
    id: 'tech-001',
    title: 'Byt NS på Loopia — aktivera wavult.com via Cloudflare',
    description: 'wavult.com pekar på Loopia DNS. CF Zone skapad. NS: arch.ns.cloudflare.com + gina.ns.cloudflare.com.',
    owner: 'johan-berglund',
    module: 'tech',
    flow: 'dns-activation',
    state: 'REQUIRED',
    priority: 'high',
    deadline: '2026-04-01',
    dependencies: [],
    requiredInputs: ['Loopia-inloggning', 'CF NS-adresser'],
    outputValidation: 'wavult.com svarar via Cloudflare, os.wavult.com live',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'tech-002',
    title: 'Wavult Mobile — EAS Build + TestFlight',
    description: 'Röstintegration (Bernt + Whisper) kod klar. Kräver Apple Developer Account och EAS build.',
    owner: 'johan-berglund',
    module: 'tech',
    flow: 'mobile-launch',
    state: 'REQUIRED',
    priority: 'high',
    deadline: '2026-04-11',
    dependencies: [],
    requiredInputs: ['Apple Developer Account', 'eas build --platform ios'],
    outputValidation: 'App installerbar via TestFlight på teamets iPhones',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },

  // ── OPERATIONS / LAUNCH ─────────────────────────────────────────────────────
  {
    id: 'ops-001',
    title: 'QuiXzoom beta-appen klar för Sverige-lansering',
    description: 'React Native Expo-app. Uppdragsflöde, betalning, zoomer-onboarding. Klart till mitten juni.',
    owner: 'johan-berglund',
    module: 'operations',
    flow: 'quixzoom-launch',
    state: 'IN_PROGRESS',
    priority: 'critical',
    deadline: '2026-06-01',
    dependencies: [],
    requiredInputs: ['Stripe Connect konfigurerat', 'Supabase RLS policies klara'],
    outputValidation: 'App godkänd i TestFlight, 5 zoomers kan ta och leverera ett uppdrag',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'ops-002',
    title: 'Thailand Workcamp — hotellbokning bekräftad',
    description: 'Leon förhandlar med Arthur på Nysa Hotel. 3 rum + ev lokal. 11 april 2026.',
    owner: 'leon-russo',
    module: 'operations',
    flow: 'thailand-workcamp',
    state: 'IN_PROGRESS',
    priority: 'critical',
    deadline: '2026-04-01',
    dependencies: [],
    requiredInputs: ['Bekräftelse från Arthur (Nysa Hotel)', 'Betalning för rum'],
    outputValidation: 'Bokningsbekräftelse mottagen, alla 5 teammedlemmar har rum',
    assignedAt: '2026-03-27',
    completedAt: null,
    validationRequired: false,
  },
  {
    id: 'ops-003',
    title: 'Landvex B2G — boka 3 demos med kommuner',
    description: 'Target: Värmdö, Nacka, Vaxholm. Cold outreach till teknisk chef. Mål: 3 demos bokade vid Workcamp.',
    owner: 'leon-russo',
    module: 'operations',
    flow: 'landvex-sales',
    state: 'REQUIRED',
    priority: 'high',
    deadline: '2026-04-11',
    dependencies: [],
    requiredInputs: ['Landvex demo-material', 'Kontaktinfo till tekniska chefer'],
    outputValidation: '3 demo-möten bokade i kalender',
    assignedAt: '2026-03-28',
    completedAt: null,
    validationRequired: false,
  },
]

export const FLOWS: Flow[] = [
  {
    id: 'dubai-structure',
    title: 'Dubai Bolagsstruktur',
    module: 'legal',
    description: 'Bilda Wavult Group FZCO + DevOps FZCO och assigna all IP',
    tasks: ['legal-001', 'legal-002', 'legal-003'],
    state: 'in_progress',
  },
  {
    id: 'landvex-compliance',
    title: 'Landvex AB Compliance',
    module: 'legal',
    description: 'Bokföring, namnbyte, Texas LLC',
    tasks: ['legal-004', 'legal-005', 'legal-006'],
    state: 'in_progress',
  },
  {
    id: 'infra-finance',
    title: 'Infrastruktur & Finans',
    module: 'finance',
    description: 'Identity Core + intercompany setup',
    tasks: ['finance-001', 'finance-003'],
    state: 'in_progress',
  },
  {
    id: 'thailand-workcamp',
    title: 'Thailand Workcamp',
    module: 'operations',
    description: '11 april 2026 — hela teamet',
    tasks: ['ops-002'],
    state: 'in_progress',
  },
  {
    id: 'quixzoom-launch',
    title: 'QuiXzoom Sverige-lansering',
    module: 'operations',
    description: 'Mitten juni 2026',
    tasks: ['ops-001'],
    state: 'in_progress',
  },
  {
    id: 'dns-activation',
    title: 'DNS & Domain Aktivering',
    module: 'tech',
    description: 'wavult.com via Cloudflare',
    tasks: ['tech-001'],
    state: 'in_progress',
  },
  {
    id: 'mobile-launch',
    title: 'Wavult Mobile Launch',
    module: 'tech',
    description: 'EAS Build + TestFlight',
    tasks: ['tech-002'],
    state: 'in_progress',
  },
  {
    id: 'landvex-sales',
    title: 'Landvex B2G Sales',
    module: 'operations',
    description: '3 demo-möten med kommuner',
    tasks: ['ops-003'],
    state: 'in_progress',
  },
  {
    id: 'intercompany',
    title: 'Intercompany Setup',
    module: 'finance',
    description: 'IP-licens och management fee fakturering',
    tasks: ['finance-002', 'finance-003'],
    state: 'blocked',
  },
]

// Person registry for display purposes
export const PERSONS: Record<string, { name: string; role: string }> = {
  'erik-svensson':    { name: 'Erik Svensson',          role: 'Group CEO / Chairman' },
  'dennis-bjarnemark': { name: 'Dennis Bjarnemark',     role: 'Chief Legal & Operations' },
  'winston-bjarnemark': { name: 'Winston Bjarnemark',   role: 'CFO' },
  'leon-russo':        { name: 'Leon Russo',             role: 'CEO Wavult Operations' },
  'johan-berglund':    { name: 'Johan Berglund',         role: 'Group CTO' },
}
